from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / "QMW_Temporal_Crystal16_CNMAT_Resonator_v1.maxpat"


def box(identifier, maxclass, rect, **values):
    data = {"id": identifier, "maxclass": maxclass, "patching_rect": rect}
    data.update(values)
    return {"box": data}


def line(source, outlet, destination, inlet=0):
    return {
        "patchline": {
            "source": [source, outlet],
            "destination": [destination, inlet],
        }
    }


boxes = [
    box(
        "title",
        "comment",
        [25, 18, 1040, 24],
        text="QMW Temporal Crystal 16 → CNMAT Resonant Body v1",
        fontsize=17,
    ),
    box(
        "subtitle",
        "comment",
        [25, 48, 1120, 38],
        text=(
            "The canonical 16×16 density matrix retunes 256 CNMAT resonances. "
            "Each /qmw/time/chronos/tick excites the stored body independently."
        ),
    ),
    box(
        "port_warning",
        "comment",
        [790, 18, 400, 20],
        text="Close every other Max patch that binds UDP 7400.",
        textcolor=[0.8, 0.18, 0.12, 1.0],
    ),
    box(
        "engine_label",
        "comment",
        [25, 100, 300, 20],
        text="MODEL — canonical QMW density engine",
    ),
    box(
        "engine_udp",
        "newobj",
        [25, 126, 112, 22],
        text="udpreceive 7400",
        numinlets=1,
        numoutlets=1,
        outlettype=[""],
    ),
    box(
        "engine_qmw",
        "newobj",
        [150, 126, 104, 22],
        text="OSC-route /qmw",
        numinlets=1,
        numoutlets=2,
        outlettype=["", ""],
    ),
    box(
        "engine_cnmat",
        "newobj",
        [267, 126, 118, 22],
        text="OSC-route /cnmat",
        numinlets=1,
        numoutlets=2,
        outlettype=["", ""],
    ),
    box(
        "engine_density",
        "newobj",
        [398, 126, 190, 22],
        text="OSC-route /density_resonator",
        numinlets=1,
        numoutlets=2,
        outlettype=["", ""],
    ),
    box(
        "engine_route",
        "newobj",
        [601, 126, 216, 22],
        text="OSC-route /begin /row /end /trigger",
        numinlets=1,
        numoutlets=5,
        outlettype=["", "", "", "", ""],
    ),
    box(
        "mode_control_label",
        "comment",
        [830, 100, 340, 20],
        text="LIVE TEMPORAL MODE → Python control port 7402",
        fontface=1,
    ),
    box("mode_observer", "message", [830, 126, 68, 22], text="observer"),
    box("mode_floquet", "message", [908, 126, 58, 22], text="floquet"),
    box("mode_lfsr", "message", [976, 126, 36, 22], text="lfsr"),
    box(
        "mode_pythagorean",
        "message",
        [1022, 126, 94, 22],
        text="pythagorean",
    ),
    box(
        "mode_pack",
        "newobj",
        [830, 166, 208, 22],
        text="o.pack /qmw/time/control/mode",
        numinlets=1,
        numoutlets=1,
        outlettype=["FullPacket"],
    ),
    box(
        "control_udp",
        "newobj",
        [1050, 166, 145, 22],
        text="udpsend 127.0.0.1 7402",
        numinlets=1,
        numoutlets=0,
    ),
    box(
        "prepend_begin",
        "newobj",
        [560, 166, 92, 22],
        text="prepend begin",
        numinlets=1,
        numoutlets=1,
        outlettype=[""],
    ),
    box(
        "prepend_row",
        "newobj",
        [662, 166, 82, 22],
        text="prepend row",
        numinlets=1,
        numoutlets=1,
        outlettype=[""],
    ),
    box(
        "prepend_end",
        "newobj",
        [754, 166, 82, 22],
        text="prepend end",
        numinlets=1,
        numoutlets=1,
        outlettype=[""],
    ),
    box(
        "prepend_trigger",
        "newobj",
        [846, 166, 100, 22],
        text="prepend trigger",
        numinlets=1,
        numoutlets=1,
        outlettype=[""],
    ),
    box(
        "time_label",
        "comment",
        [25, 215, 560, 20],
        text="TEMPORAL CRYSTAL 16 — logical clock, protocol, and diagnostics",
        fontface=1,
    ),
    box(
        "time_root",
        "newobj",
        [25, 242, 108, 22],
        text="OSC-route /time",
        numinlets=1,
        numoutlets=2,
        outlettype=["", ""],
    ),
    box(
        "time_route",
        "newobj",
        [145, 242, 855, 22],
        text=(
            "OSC-route /enabled /mode /rate_hz /revision /protocol "
            "/chronos /lfsr /spqt /kairos /aion"
        ),
        numinlets=1,
        numoutlets=11,
        outlettype=[""] * 11,
    ),
    box("enabled_value", "number", [25, 285, 55, 22]),
    box("enabled_label", "comment", [25, 310, 70, 20], text="ENABLED"),
    box("mode_set", "newobj", [95, 285, 72, 22], text="prepend set"),
    box("mode_value", "message", [178, 285, 112, 22], text="off"),
    box("mode_label", "comment", [178, 310, 90, 20], text="MODE"),
    box("rate_value", "flonum", [305, 285, 70, 22]),
    box("rate_label", "comment", [305, 310, 90, 20], text="RATE Hz"),
    box("revision_value", "number", [390, 285, 70, 22]),
    box("revision_label", "comment", [390, 310, 90, 20], text="REVISION"),
    box("protocol_set", "newobj", [475, 285, 72, 22], text="prepend set"),
    box(
        "protocol_value",
        "message",
        [558, 285, 330, 22],
        text="waiting for /qmw/time/protocol",
    ),
    box("protocol_label", "comment", [558, 310, 90, 20], text="PROTOCOL"),
    box(
        "chronos_route",
        "newobj",
        [25, 345, 202, 22],
        text="OSC-route /tick /index /phase",
        numinlets=1,
        numoutlets=4,
        outlettype=["", "", "", ""],
    ),
    box(
        "tick_dispatch",
        "newobj",
        [242, 345, 43, 22],
        text="t i b",
        numinlets=1,
        numoutlets=2,
        outlettype=["int", "bang"],
    ),
    box("tick_value", "number", [300, 345, 65, 22]),
    box("tick_label", "comment", [300, 370, 60, 20], text="TICK"),
    box("index_value", "number", [380, 345, 65, 22]),
    box("index_label", "comment", [380, 370, 60, 20], text="INDEX"),
    box("phase_value", "flonum", [460, 345, 85, 22]),
    box("phase_label", "comment", [460, 370, 110, 20], text="PHASE rad"),
    box(
        "tick_trigger",
        "message",
        [575, 345, 82, 22],
        text="trigger 0.45",
    ),
    box(
        "tick_note",
        "comment",
        [670, 347, 300, 20],
        text="bounded Chronos impulse → existing trigger path",
    ),
    box(
        "lfsr_route",
        "newobj",
        [25, 405, 196, 22],
        text="OSC-route /state /bits /phase",
        numinlets=1,
        numoutlets=4,
        outlettype=["", "", "", ""],
    ),
    box("lfsr_state", "number", [235, 405, 60, 22]),
    box("lfsr_label", "comment", [235, 430, 90, 20], text="LFSR STATE"),
    box(
        "spqt_route",
        "newobj",
        [330, 405, 270, 22],
        text="OSC-route /macrocycle_position /macrocycle_length",
        numinlets=1,
        numoutlets=3,
        outlettype=["", "", ""],
    ),
    box("spqt_position", "number", [615, 405, 70, 22]),
    box("spqt_position_label", "comment", [615, 430, 90, 20], text="SPQT POS"),
    box("spqt_length", "number", [700, 405, 70, 22]),
    box("spqt_length_label", "comment", [700, 430, 100, 20], text="SPQT LENGTH"),
    box(
        "kairos_route",
        "newobj",
        [25, 462, 142, 22],
        text="OSC-route /count /event",
        numinlets=1,
        numoutlets=3,
        outlettype=["", "", ""],
    ),
    box("kairos_count", "number", [180, 462, 60, 22]),
    box("kairos_label", "comment", [180, 487, 90, 20], text="KAIROS N"),
    box("kairos_set", "newobj", [255, 462, 72, 22], text="prepend set"),
    box("kairos_event", "message", [340, 462, 380, 22], text="no Kairos event"),
    box(
        "aion_route",
        "newobj",
        [790, 405, 335, 22],
        text="OSC-route /target_frequency /target_amplitude /peak_to_background",
        numinlets=1,
        numoutlets=4,
        outlettype=["", "", "", ""],
    ),
    box("aion_frequency", "flonum", [790, 442, 75, 22]),
    box("aion_amplitude", "flonum", [880, 442, 75, 22]),
    box("aion_peak", "flonum", [970, 442, 85, 22]),
    box("aion_labels", "comment", [790, 467, 330, 20], text="AION target Hz     amplitude        peak/background"),
    box(
        "qtm_label",
        "comment",
        [25, 520, 420, 20],
        text="LEGACY OPTIONAL TRIGGER — QTM v1 density clock",
    ),
    box(
        "qtm_mechanics",
        "newobj",
        [360, 520, 188, 22],
        text="OSC-route /temporal-mechanics",
        numinlets=1,
        numoutlets=2,
        outlettype=["", ""],
    ),
    box(
        "qtm_v1",
        "newobj",
        [560, 520, 92, 22],
        text="OSC-route /v1",
        numinlets=1,
        numoutlets=2,
        outlettype=["", ""],
    ),
    box(
        "qtm_clock",
        "newobj",
        [665, 520, 146, 22],
        text="OSC-route /density-clock",
        numinlets=1,
        numoutlets=2,
        outlettype=["", ""],
    ),
    box(
        "qtm_pulse",
        "newobj",
        [824, 520, 102, 22],
        text="OSC-route /pulse",
        numinlets=1,
        numoutlets=2,
        outlettype=["", ""],
    ),
    box(
        "gain_vector_label",
        "comment",
        [25, 563, 1120, 20],
        text=(
            "CLICK-LATCHED RESONANCE GAINS — 256 ordered relations, row-major: "
            "slider index = 16m + n"
        ),
        fontface=1,
    ),
    box(
        "gain_multislider",
        "multislider",
        [25, 588, 1120, 125],
        numinlets=1,
        numoutlets=2,
        outlettype=["", ""],
        parameter_enable=0,
        size=256,
        setminmax=[0.0, 0.42],
        bgcolor=[0.08, 0.1, 0.14, 1.0],
        slidercolor=[0.34, 0.78, 1.0, 1.0],
    ),
    box(
        "js",
        "newobj",
        [390, 760, 330, 22],
        text="js qmw_temporal_crystal16_cnmat_resonator_v1.js",
        numinlets=3,
        numoutlets=5,
        outlettype=["", "", "", "list", "list"],
    ),
    box(
        "frequency_multiplier_label",
        "comment",
        [745, 735, 370, 20],
        text="GLOBAL RESONANCE FREQUENCY × — applied on next click",
        fontface=1,
    ),
    box(
        "frequency_multiplier",
        "flonum",
        [745, 760, 72, 22],
        minimum=0.03125,
        maximum=8.0,
    ),
    box("frequency_quarter", "message", [830, 760, 42, 22], text="0.25"),
    box("frequency_half", "message", [882, 760, 34, 22], text="0.5"),
    box("frequency_unity", "message", [926, 760, 30, 22], text="1."),
    box(
        "frequency_load",
        "newobj",
        [970, 760, 84, 22],
        text="loadmess 1.",
        numinlets=1,
        numoutlets=1,
        outlettype=[""],
    ),
    box(
        "status",
        "message",
        [390, 796, 530, 22],
        text="waiting for complete density-resonator frame...",
        numinlets=2,
        numoutlets=1,
        outlettype=[""],
    ),
    box(
        "test_button",
        "button",
        [25, 759, 24, 24],
        numinlets=1,
        numoutlets=1,
        outlettype=["bang"],
    ),
    box("test_message", "message", [60, 760, 34, 22], text="test"),
    box("test_note", "comment", [105, 761, 185, 20], text="local model + impulse test"),
    box(
        "manual_button",
        "button",
        [25, 815, 24, 24],
        numinlets=1,
        numoutlets=1,
        outlettype=["bang"],
    ),
    box("manual_amp", "message", [60, 816, 76, 22], text="trigger 0.7"),
    box("manual_note", "comment", [108, 817, 182, 20], text="independent manual impulse"),
    box(
        "click",
        "newobj",
        [515, 856, 42, 22],
        text="click~",
        numinlets=1,
        numoutlets=1,
        outlettype=["signal"],
    ),
    box(
        "resonators",
        "newobj",
        [424, 902, 156, 22],
        text="resonators~ smooth",
        numinlets=1,
        numoutlets=2,
        outlettype=["signal", "list"],
    ),
    box("clear", "message", [605, 870, 40, 22], text="clear"),
    box("squelch", "message", [655, 870, 54, 22], text="squelch"),
    box(
        "sinusoids",
        "newobj",
        [25, 902, 112, 22],
        text="sinusoids~ bwe",
        numinlets=1,
        numoutlets=1,
        outlettype=["signal"],
    ),
    box(
        "sine_gain",
        "newobj",
        [155, 902, 58, 22],
        text="*~ 0.25",
        numinlets=2,
        numoutlets=1,
        outlettype=["signal"],
    ),
    box(
        "sine_level_label",
        "comment",
        [25, 940, 112, 20],
        text="SINE BLEND",
    ),
    box(
        "sine_level",
        "flonum",
        [155, 938, 72, 22],
        minimum=0.0,
        maximum=1.0,
    ),
    box(
        "sine_level_load",
        "newobj",
        [240, 938, 98, 22],
        text="loadmess 0.25",
        numinlets=1,
        numoutlets=1,
        outlettype=[""],
    ),
    box(
        "makeup",
        "newobj",
        [605, 902, 66, 22],
        text="*~ 500.",
        numinlets=2,
        numoutlets=1,
        outlettype=["signal"],
    ),
    box(
        "spectral_mix",
        "newobj",
        [690, 902, 36, 22],
        text="+~",
        numinlets=2,
        numoutlets=1,
        outlettype=["signal"],
    ),
    box(
        "safety_clip",
        "newobj",
        [745, 902, 104, 22],
        text="clip~ -0.98 0.98",
        numinlets=1,
        numoutlets=1,
        outlettype=["signal"],
    ),
    box(
        "makeup_label",
        "comment",
        [605, 940, 78, 20],
        text="MAKEUP ×",
    ),
    box(
        "makeup_value",
        "flonum",
        [690, 938, 76, 22],
        minimum=1.0,
        maximum=1000.0,
    ),
    box(
        "makeup_load",
        "newobj",
        [785, 938, 98, 22],
        text="loadmess 500.",
        numinlets=1,
        numoutlets=1,
        outlettype=[""],
    ),
    box(
        "gain",
        "live.gain~",
        [449, 990, 96, 125],
        numinlets=2,
        numoutlets=5,
        outlettype=["signal", "signal", "", "float", "list"],
        parameter_enable=1,
    ),
    box("dac", "newobj", [458, 1140, 78, 22], text="ezdac~", numinlets=2, numoutlets=0),
    box(
        "architecture",
        "comment",
        [25, 1194, 1120, 45],
        text=(
            "Complete model updates are staged silently. Chronos ticks, "
            "canonical resonance events, optional legacy QTM pulses, and the "
            "manual button commit the newest model immediately before click~. "
            "Adjustable makeup is bounded by clip~ before the output fader."
        ),
    ),
]


lines = [
    line("engine_udp", 0, "engine_qmw"),
    line("engine_qmw", 0, "engine_cnmat"),
    line("engine_cnmat", 0, "engine_density"),
    line("engine_density", 0, "engine_route"),
    line("engine_route", 0, "prepend_begin"),
    line("engine_route", 1, "prepend_row"),
    line("engine_route", 2, "prepend_end"),
    line("engine_route", 3, "prepend_trigger"),
    line("mode_observer", 0, "mode_pack"),
    line("mode_floquet", 0, "mode_pack"),
    line("mode_lfsr", 0, "mode_pack"),
    line("mode_pythagorean", 0, "mode_pack"),
    line("mode_pack", 0, "control_udp"),
    line("prepend_begin", 0, "js"),
    line("prepend_row", 0, "js"),
    line("prepend_end", 0, "js"),
    line("prepend_trigger", 0, "js"),
    line("engine_qmw", 0, "time_root"),
    line("time_root", 0, "time_route"),
    line("time_route", 0, "enabled_value"),
    line("time_route", 1, "mode_set"),
    line("mode_set", 0, "mode_value"),
    line("time_route", 2, "rate_value"),
    line("time_route", 3, "revision_value"),
    line("time_route", 4, "protocol_set"),
    line("protocol_set", 0, "protocol_value"),
    line("time_route", 5, "chronos_route"),
    line("time_route", 6, "lfsr_route"),
    line("time_route", 7, "spqt_route"),
    line("time_route", 8, "kairos_route"),
    line("time_route", 9, "aion_route"),
    line("chronos_route", 0, "tick_dispatch"),
    line("tick_dispatch", 0, "tick_value"),
    line("tick_dispatch", 1, "tick_trigger"),
    line("tick_trigger", 0, "js"),
    line("chronos_route", 1, "index_value"),
    line("chronos_route", 2, "phase_value"),
    line("lfsr_route", 0, "lfsr_state"),
    line("spqt_route", 0, "spqt_position"),
    line("spqt_route", 1, "spqt_length"),
    line("kairos_route", 0, "kairos_count"),
    line("kairos_route", 1, "kairos_set"),
    line("kairos_set", 0, "kairos_event"),
    line("aion_route", 0, "aion_frequency"),
    line("aion_route", 1, "aion_amplitude"),
    line("aion_route", 2, "aion_peak"),
    line("engine_qmw", 0, "qtm_mechanics"),
    line("qtm_mechanics", 0, "qtm_v1"),
    line("qtm_v1", 0, "qtm_clock"),
    line("qtm_clock", 0, "qtm_pulse"),
    line("qtm_pulse", 0, "js", 1),
    line("test_button", 0, "test_message"),
    line("test_message", 0, "js"),
    line("manual_button", 0, "manual_amp"),
    line("manual_amp", 0, "js"),
    line("frequency_quarter", 0, "frequency_multiplier"),
    line("frequency_half", 0, "frequency_multiplier"),
    line("frequency_unity", 0, "frequency_multiplier"),
    line("frequency_load", 0, "frequency_multiplier"),
    line("frequency_multiplier", 0, "js", 2),
    line("js", 0, "resonators"),
    line("js", 1, "click"),
    line("js", 2, "status", 1),
    line("js", 3, "gain_multislider"),
    line("js", 4, "sinusoids"),
    line("click", 0, "resonators"),
    line("clear", 0, "resonators"),
    line("squelch", 0, "resonators"),
    line("resonators", 0, "makeup"),
    line("sinusoids", 0, "sine_gain"),
    line("sine_level_load", 0, "sine_level"),
    line("sine_level", 0, "sine_gain", 1),
    line("makeup_load", 0, "makeup_value"),
    line("makeup_value", 0, "makeup", 1),
    line("makeup", 0, "spectral_mix"),
    line("sine_gain", 0, "spectral_mix", 1),
    line("spectral_mix", 0, "safety_clip"),
    line("safety_clip", 0, "gain", 0),
    line("safety_clip", 0, "gain", 1),
    line("gain", 0, "dac", 0),
    line("gain", 1, "dac", 1),
]


patcher = {
    "patcher": {
        "fileversion": 1,
        "appversion": {
            "major": 9,
            "minor": 0,
            "revision": 5,
            "architecture": "x64",
            "modernui": 1,
        },
        "classnamespace": "box",
        "rect": [80, 50, 1200, 1300],
        "gridsize": [15, 15],
        "boxes": boxes,
        "lines": lines,
        "dependency_cache": [
            {"name": "OSC-route.mxo", "type": "iLaX"},
            {"name": "o.pack.mxo", "type": "iLaX"},
            {"name": "resonators~.mxo", "type": "iLaX"},
            {"name": "sinusoids~.mxo", "type": "iLaX"},
            {
                "name": "qmw_temporal_crystal16_cnmat_resonator_v1.js",
                "type": "TEXT",
            },
        ],
        "autosave": 0,
    }
}

OUTPUT.write_text(json.dumps(patcher, indent=2) + "\n", encoding="utf-8")
print(OUTPUT)
