from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / "QMW_Temporal_Crystal16_Spectral_Wavetable_v1.maxpat"


def box(identifier, maxclass, rect, **values):
    data = {"id": identifier, "maxclass": maxclass, "patching_rect": rect}
    data.update(values)
    return {"box": data}


def line(source, outlet, destination, inlet=0):
    return {
        "patchline": {
            "source": [source, outlet],
            "destination": [destination, inlet],
        }
    }


boxes = [
    box(
        "title",
        "comment",
        [25, 18, 1030, 25],
        text="QMW Temporal Crystal 16 → Spectral Wavetable v1",
        fontsize=17,
    ),
    box(
        "subtitle",
        "comment",
        [25, 49, 1120, 38],
        text=(
            "QAC/QFT-style 16-harmonic rendering of canonical rho. "
            "Tables stage silently and crossfade only on temporal clicks."
        ),
    ),
    box(
        "port_warning",
        "comment",
        [800, 18, 390, 20],
        text="Close every other Max patch that binds UDP 7400.",
        textcolor=[0.8, 0.18, 0.12, 1.0],
    ),
    box(
        "udp",
        "newobj",
        [25, 106, 112, 22],
        text="udpreceive 7400",
        numinlets=1,
        numoutlets=1,
        outlettype=[""],
    ),
    box(
        "qmw",
        "newobj",
        [150, 106, 104, 22],
        text="OSC-route /qmw",
        numinlets=1,
        numoutlets=2,
        outlettype=["", ""],
    ),
    box(
        "density",
        "newobj",
        [267, 106, 118, 22],
        text="OSC-route /density",
        numinlets=1,
        numoutlets=2,
        outlettype=["", ""],
    ),
    box(
        "wavetable",
        "newobj",
        [398, 106, 132, 22],
        text="OSC-route /wavetable",
        numinlets=1,
        numoutlets=2,
        outlettype=["", ""],
    ),
    box(
        "wavetable_route",
        "newobj",
        [543, 106, 258, 22],
        text="OSC-route /begin /chunk /harmonics /end",
        numinlets=1,
        numoutlets=5,
        outlettype=[""] * 5,
    ),
    box("prepend_begin", "newobj", [410, 145, 92, 22], text="prepend begin"),
    box("prepend_chunk", "newobj", [512, 145, 98, 22], text="prepend chunk"),
    box(
        "prepend_harmonics",
        "newobj",
        [620, 145, 122, 22],
        text="prepend harmonics",
    ),
    box("prepend_end", "newobj", [752, 145, 82, 22], text="prepend end"),
    box(
        "mode_label",
        "comment",
        [835, 100, 340, 20],
        text="LIVE TEMPORAL MODE → Python 7402",
        fontface=1,
    ),
    box("mode_observer", "message", [835, 126, 68, 22], text="observer"),
    box("mode_floquet", "message", [913, 126, 58, 22], text="floquet"),
    box("mode_lfsr", "message", [981, 126, 36, 22], text="lfsr"),
    box("mode_pythagorean", "message", [1027, 126, 94, 22], text="pythagorean"),
    box(
        "mode_pack",
        "newobj",
        [835, 166, 208, 22],
        text="o.pack /qmw/time/control/mode",
        numinlets=1,
        numoutlets=1,
        outlettype=["FullPacket"],
    ),
    box(
        "control_udp",
        "newobj",
        [1053, 166, 142, 22],
        text="udpsend 127.0.0.1 7402",
        numinlets=1,
        numoutlets=0,
    ),
    box(
        "receiver",
        "newobj",
        [390, 205, 330, 22],
        text="js qmw_temporal_crystal16_spectral_wavetable_v1.js",
        numinlets=2,
        numoutlets=4,
        outlettype=["list", "", "", "list"],
    ),
    box(
        "status",
        "message",
        [390, 238, 600, 22],
        text="waiting for density-derived wavetable...",
        numinlets=2,
        numoutlets=1,
        outlettype=[""],
    ),
    box("test_button", "button", [25, 204, 24, 24]),
    box("test_message", "message", [60, 205, 34, 22], text="test"),
    box(
        "test_note",
        "comment",
        [105, 207, 235, 20],
        text="local 16-harmonic table + commit",
    ),
    box("commit_button", "button", [25, 240, 24, 24]),
    box(
        "commit_note",
        "comment",
        [60, 242, 260, 20],
        text="manual commit of newest staged table",
    ),
    box(
        "waveform_label",
        "comment",
        [25, 285, 1120, 20],
        text="CLICK-LATCHED 256-SAMPLE WAVETABLE",
        fontface=1,
    ),
    box(
        "waveform",
        "multislider",
        [25, 310, 1120, 165],
        numinlets=1,
        numoutlets=2,
        outlettype=["", ""],
        parameter_enable=0,
        size=256,
        setminmax=[-1.0, 1.0],
        bgcolor=[0.08, 0.1, 0.14, 1.0],
        slidercolor=[0.34, 0.78, 1.0, 1.0],
    ),
    box(
        "harmonic_label",
        "comment",
        [25, 492, 1120, 20],
        text="ENERGY-BASIS HARMONIC AMPLITUDES — sqrt(population), H1…H16",
        fontface=1,
    ),
    box(
        "harmonics",
        "multislider",
        [25, 517, 1120, 90],
        numinlets=1,
        numoutlets=2,
        outlettype=["", ""],
        parameter_enable=0,
        size=16,
        setminmax=[0.0, 1.0],
        bgcolor=[0.08, 0.1, 0.14, 1.0],
        slidercolor=[0.95, 0.58, 0.24, 1.0],
    ),
    box(
        "time_label",
        "comment",
        [25, 630, 500, 20],
        text="TEMPORAL STATE AND CLICK COMMIT",
        fontface=1,
    ),
    box(
        "time_root",
        "newobj",
        [25, 657, 108, 22],
        text="OSC-route /time",
        numinlets=1,
        numoutlets=2,
        outlettype=["", ""],
    ),
    box(
        "time_route",
        "newobj",
        [145, 657, 585, 22],
        text="OSC-route /enabled /mode /rate_hz /protocol /chronos /lfsr /spqt",
        numinlets=1,
        numoutlets=8,
        outlettype=[""] * 8,
    ),
    box("enabled", "number", [25, 700, 55, 22]),
    box("enabled_label", "comment", [25, 725, 70, 20], text="ENABLED"),
    box("mode_set", "newobj", [95, 700, 72, 22], text="prepend set"),
    box("mode", "message", [178, 700, 110, 22], text="off"),
    box("mode_value_label", "comment", [178, 725, 70, 20], text="MODE"),
    box("rate", "flonum", [305, 700, 68, 22]),
    box("rate_label", "comment", [305, 725, 75, 20], text="RATE Hz"),
    box("protocol_set", "newobj", [390, 700, 72, 22], text="prepend set"),
    box(
        "protocol",
        "message",
        [475, 700, 350, 22],
        text="waiting for temporal protocol",
    ),
    box(
        "chronos",
        "newobj",
        [25, 760, 202, 22],
        text="OSC-route /tick /index /phase",
        numinlets=1,
        numoutlets=4,
        outlettype=["", "", "", ""],
    ),
    box(
        "tick_dispatch",
        "newobj",
        [240, 760, 43, 22],
        text="t i b",
        numinlets=1,
        numoutlets=2,
        outlettype=["int", "bang"],
    ),
    box("tick", "number", [295, 760, 62, 22]),
    box("tick_label", "comment", [295, 785, 55, 20], text="TICK"),
    box(
        "lfsr",
        "newobj",
        [385, 760, 116, 22],
        text="OSC-route /state",
        numinlets=1,
        numoutlets=2,
        outlettype=["", ""],
    ),
    box("lfsr_state", "number", [515, 760, 62, 22]),
    box("lfsr_label", "comment", [515, 785, 85, 20], text="LFSR"),
    box(
        "spqt",
        "newobj",
        [615, 760, 214, 22],
        text="OSC-route /macrocycle_position",
        numinlets=1,
        numoutlets=2,
        outlettype=["", ""],
    ),
    box("spqt_position", "number", [845, 760, 72, 22]),
    box("spqt_label", "comment", [845, 785, 90, 20], text="SPQT POS"),
    box(
        "audio_label",
        "comment",
        [25, 825, 430, 20],
        text="QFT-STYLE DOUBLE-BUFFERED WAVETABLE VOICE",
        fontface=1,
    ),
    box(
        "buffer_a",
        "newobj",
        [25, 850, 260, 22],
        text="buffer~ qmw_tc_wave_A @samps 256 @channels 1",
        numinlets=1,
        numoutlets=2,
        outlettype=["float", "bang"],
    ),
    box(
        "buffer_b",
        "newobj",
        [295, 850, 260, 22],
        text="buffer~ qmw_tc_wave_B @samps 256 @channels 1",
        numinlets=1,
        numoutlets=2,
        outlettype=["float", "bang"],
    ),
    box("fundamental_label", "comment", [25, 890, 125, 20], text="FUNDAMENTAL Hz"),
    box(
        "fundamental",
        "flonum",
        [150, 887, 75, 22],
        minimum=10.0,
        maximum=1000.0,
    ),
    box("fundamental_low", "message", [238, 887, 42, 22], text="27.5"),
    box("fundamental_mid", "message", [290, 887, 30, 22], text="55."),
    box("fundamental_high", "message", [330, 887, 38, 22], text="110."),
    box(
        "fundamental_load",
        "newobj",
        [380, 887, 92, 22],
        text="loadmess 55.",
        numinlets=1,
        numoutlets=1,
        outlettype=[""],
    ),
    box("frequency_pack", "newobj", [150, 920, 80, 22], text="pack f 80"),
    box(
        "frequency_line",
        "newobj",
        [242, 920, 42, 22],
        text="line~",
        numinlets=2,
        numoutlets=2,
        outlettype=["signal", "bang"],
    ),
    box(
        "phasor",
        "newobj",
        [295, 920, 52, 22],
        text="phasor~",
        numinlets=2,
        numoutlets=1,
        outlettype=["signal"],
    ),
    box(
        "wave_a",
        "newobj",
        [365, 920, 146, 22],
        text="wave~ qmw_tc_wave_A",
        numinlets=3,
        numoutlets=1,
        outlettype=["signal"],
    ),
    box(
        "wave_b",
        "newobj",
        [525, 920, 146, 22],
        text="wave~ qmw_tc_wave_B",
        numinlets=3,
        numoutlets=1,
        outlettype=["signal"],
    ),
    box("xfade_pack", "newobj", [700, 850, 80, 22], text="pack f 50"),
    box(
        "xfade_line",
        "newobj",
        [790, 850, 42, 22],
        text="line~",
        numinlets=2,
        numoutlets=2,
        outlettype=["signal", "bang"],
    ),
    box(
        "xfade_inverse",
        "newobj",
        [845, 850, 55, 22],
        text="!-~ 1.",
        numinlets=2,
        numoutlets=1,
        outlettype=["signal"],
    ),
    box(
        "wave_a_gain",
        "newobj",
        [420, 960, 36, 22],
        text="*~",
        numinlets=2,
        numoutlets=1,
        outlettype=["signal"],
    ),
    box(
        "wave_b_gain",
        "newobj",
        [570, 960, 36, 22],
        text="*~",
        numinlets=2,
        numoutlets=1,
        outlettype=["signal"],
    ),
    box(
        "wave_sum",
        "newobj",
        [500, 998, 36, 22],
        text="+~",
        numinlets=2,
        numoutlets=1,
        outlettype=["signal"],
    ),
    box(
        "dcblock",
        "newobj",
        [500, 1033, 60, 22],
        text="dcblock~",
        numinlets=1,
        numoutlets=1,
        outlettype=["signal"],
    ),
    box(
        "safety",
        "newobj",
        [500, 1068, 104, 22],
        text="clip~ -0.98 0.98",
        numinlets=1,
        numoutlets=1,
        outlettype=["signal"],
    ),
    box(
        "gain",
        "live.gain~",
        [484, 1105, 96, 125],
        numinlets=2,
        numoutlets=5,
        outlettype=["signal", "signal", "", "float", "list"],
        parameter_enable=1,
    ),
    box(
        "dac",
        "newobj",
        [493, 1240, 78, 22],
        text="ezdac~",
        numinlets=2,
        numoutlets=0,
    ),
]


lines = [
    line("udp", 0, "qmw"),
    line("qmw", 0, "density"),
    line("density", 0, "wavetable"),
    line("wavetable", 0, "wavetable_route"),
    line("wavetable_route", 0, "prepend_begin"),
    line("wavetable_route", 1, "prepend_chunk"),
    line("wavetable_route", 2, "prepend_harmonics"),
    line("wavetable_route", 3, "prepend_end"),
    line("prepend_begin", 0, "receiver"),
    line("prepend_chunk", 0, "receiver"),
    line("prepend_harmonics", 0, "receiver"),
    line("prepend_end", 0, "receiver"),
    line("mode_observer", 0, "mode_pack"),
    line("mode_floquet", 0, "mode_pack"),
    line("mode_lfsr", 0, "mode_pack"),
    line("mode_pythagorean", 0, "mode_pack"),
    line("mode_pack", 0, "control_udp"),
    line("test_button", 0, "test_message"),
    line("test_message", 0, "receiver"),
    line("commit_button", 0, "receiver", 1),
    line("receiver", 0, "waveform"),
    line("receiver", 1, "xfade_pack"),
    line("receiver", 2, "status", 1),
    line("receiver", 3, "harmonics"),
    line("qmw", 0, "time_root"),
    line("time_root", 0, "time_route"),
    line("time_route", 0, "enabled"),
    line("time_route", 1, "mode_set"),
    line("mode_set", 0, "mode"),
    line("time_route", 2, "rate"),
    line("time_route", 3, "protocol_set"),
    line("protocol_set", 0, "protocol"),
    line("time_route", 4, "chronos"),
    line("time_route", 5, "lfsr"),
    line("time_route", 6, "spqt"),
    line("chronos", 0, "tick_dispatch"),
    line("tick_dispatch", 0, "tick"),
    line("tick_dispatch", 1, "receiver", 1),
    line("lfsr", 0, "lfsr_state"),
    line("spqt", 0, "spqt_position"),
    line("fundamental_low", 0, "fundamental"),
    line("fundamental_mid", 0, "fundamental"),
    line("fundamental_high", 0, "fundamental"),
    line("fundamental_load", 0, "fundamental"),
    line("fundamental", 0, "frequency_pack"),
    line("frequency_pack", 0, "frequency_line"),
    line("frequency_line", 0, "phasor"),
    line("phasor", 0, "wave_a"),
    line("phasor", 0, "wave_b"),
    line("xfade_pack", 0, "xfade_line"),
    line("xfade_line", 0, "xfade_inverse"),
    line("xfade_inverse", 0, "wave_a_gain", 1),
    line("xfade_line", 0, "wave_b_gain", 1),
    line("wave_a", 0, "wave_a_gain"),
    line("wave_b", 0, "wave_b_gain"),
    line("wave_a_gain", 0, "wave_sum"),
    line("wave_b_gain", 0, "wave_sum", 1),
    line("wave_sum", 0, "dcblock"),
    line("dcblock", 0, "safety"),
    line("safety", 0, "gain", 0),
    line("safety", 0, "gain", 1),
    line("gain", 0, "dac", 0),
    line("gain", 1, "dac", 1),
]


patcher = {
    "patcher": {
        "fileversion": 1,
        "appversion": {
            "major": 9,
            "minor": 0,
            "revision": 5,
            "architecture": "x64",
            "modernui": 1,
        },
        "classnamespace": "box",
        "rect": [80, 30, 1200, 1300],
        "gridsize": [15, 15],
        "boxes": boxes,
        "lines": lines,
        "dependency_cache": [
            {"name": "OSC-route.mxo", "type": "iLaX"},
            {"name": "o.pack.mxo", "type": "iLaX"},
            {
                "name": "qmw_temporal_crystal16_spectral_wavetable_v1.js",
                "type": "TEXT",
            },
        ],
        "autosave": 0,
    }
}

OUTPUT.write_text(json.dumps(patcher, indent=2) + "\n", encoding="utf-8")
print(OUTPUT)
