{
  "patcher": {
    "fileversion": 1,
    "appversion": { "major": 9, "minor": 0, "revision": 5, "architecture": "x64", "modernui": 1 },
    "classnamespace": "box",
    "rect": [100.0, 100.0, 980.0, 700.0],
    "openinpresentation": 0,
    "gridsize": [15.0, 15.0],
    "boxes": [
      { "box": { "id": "title", "maxclass": "comment", "fontsize": 22.0, "text": "QMW · ERV WILSON CPS SYNTHESIS LAB v2", "patching_rect": [30.0, 22.0, 620.0, 30.0] } },
      { "box": { "id": "subtitle", "maxclass": "comment", "text": "Four qubits → complete 0)4…4)4 1-3-5-7 CPS lattice; 2)4 = Hexany", "patching_rect": [31.0, 55.0, 650.0, 22.0] } },
      { "box": { "id": "instructions", "maxclass": "comment", "linecount": 3, "text": "1. Start examples/qmw_synthesis_max_demo_v2_erv_wilson.py\n2. Select one MPE MIDI output for noteout, midiout, and ctlout\n3. Set pitch-bend range ±2 semitones; click a synthesis family", "patching_rect": [30.0, 90.0, 500.0, 58.0] } },

      { "box": { "id": "qft", "maxclass": "message", "text": "qft", "patching_rect": [30.0, 170.0, 90.0, 30.0] } },
      { "box": { "id": "evolution", "maxclass": "message", "text": "evolution", "patching_rect": [135.0, 170.0, 100.0, 30.0] } },
      { "box": { "id": "clifford", "maxclass": "message", "text": "clifford", "patching_rect": [250.0, 170.0, 100.0, 30.0] } },
      { "box": { "id": "permutation", "maxclass": "message", "text": "permutation", "patching_rect": [365.0, 170.0, 110.0, 30.0] } },
      { "box": { "id": "osc_pack", "maxclass": "newobj", "text": "o.pack /qmw/synthesis/demo", "patching_rect": [30.0, 220.0, 205.0, 22.0] } },
      { "box": { "id": "send", "maxclass": "newobj", "text": "udpsend 127.0.0.1 7403", "patching_rect": [30.0, 260.0, 180.0, 22.0] } },

      { "box": { "id": "receive_label", "maxclass": "comment", "text": "SYNTHESIS STATUS FROM PYTHON", "patching_rect": [530.0, 95.0, 260.0, 22.0] } },
      { "box": { "id": "receive", "maxclass": "newobj", "text": "udpreceive 7410", "patching_rect": [530.0, 125.0, 125.0, 22.0] } },
      { "box": { "id": "route_qmw", "maxclass": "newobj", "text": "OSC-route /qmw", "patching_rect": [530.0, 175.0, 110.0, 22.0] } },
      { "box": { "id": "route_domain", "maxclass": "newobj", "text": "OSC-route /circuit /synthesis", "patching_rect": [530.0, 220.0, 180.0, 22.0] } },
      { "box": { "id": "route_circuit", "maxclass": "newobj", "text": "OSC-route /load /op_count /qasm3", "patching_rect": [500.0, 270.0, 220.0, 22.0] } },
      { "box": { "id": "route_load", "maxclass": "newobj", "text": "OSC-route /accepted /error", "patching_rect": [445.0, 320.0, 180.0, 22.0] } },
      { "box": { "id": "accepted_label", "maxclass": "comment", "text": "accepted revision · kind · operations · qubits", "patching_rect": [405.0, 382.0, 275.0, 22.0] } },
      { "box": { "id": "accepted", "maxclass": "message", "text": "waiting for synthesis…", "patching_rect": [405.0, 410.0, 360.0, 24.0] } },
      { "box": { "id": "error", "maxclass": "message", "text": "no errors", "patching_rect": [405.0, 450.0, 360.0, 24.0] } },
      { "box": { "id": "route_synthesis", "maxclass": "newobj", "text": "OSC-route /demo", "patching_rect": [720.0, 270.0, 105.0, 22.0] } },
      { "box": { "id": "route_demo", "maxclass": "newobj", "text": "OSC-route /summary /error /gate /performance /wilson_note", "patching_rect": [650.0, 320.0, 330.0, 22.0] } },
      { "box": { "id": "summary", "maxclass": "message", "text": "summary", "patching_rect": [720.0, 382.0, 225.0, 24.0] } },
      { "box": { "id": "gate_unpack", "maxclass": "newobj", "text": "unpack i i s s i i i f i f f f f", "patching_rect": [430.0, 500.0, 285.0, 22.0] } },
      { "box": { "id": "gate_label", "maxclass": "message", "text": "gate", "patching_rect": [430.0, 535.0, 165.0, 24.0] } },
      { "box": { "id": "state_unpack", "maxclass": "newobj", "text": "unpack i i i i i i i i f f i i i i i", "patching_rect": [350.0, 575.0, 330.0, 22.0] } },
      { "box": { "id": "midi_pitch_label", "maxclass": "comment", "text": "pitch", "patching_rect": [630.0, 510.0, 55.0, 20.0] } },
      { "box": { "id": "midi_pitch", "maxclass": "number", "patching_rect": [630.0, 535.0, 55.0, 22.0] } },
      { "box": { "id": "midi_velocity_label", "maxclass": "comment", "text": "velocity", "patching_rect": [705.0, 510.0, 65.0, 20.0] } },
      { "box": { "id": "midi_velocity", "maxclass": "number", "patching_rect": [705.0, 535.0, 55.0, 22.0] } },
      { "box": { "id": "midi_duration_label", "maxclass": "comment", "text": "duration ms", "patching_rect": [780.0, 510.0, 90.0, 20.0] } },
      { "box": { "id": "midi_duration", "maxclass": "number", "patching_rect": [780.0, 535.0, 65.0, 22.0] } },
      { "box": { "id": "makenote", "maxclass": "newobj", "text": "makenote 64 120 2", "patching_rect": [630.0, 615.0, 130.0, 22.0] } },
      { "box": { "id": "noteout", "maxclass": "newobj", "text": "noteout 1", "patching_rect": [630.0, 655.0, 82.0, 22.0] } },
      { "box": { "id": "xbendout", "maxclass": "newobj", "text": "xbendout", "patching_rect": [800.0, 615.0, 75.0, 22.0] } },
      { "box": { "id": "midiout", "maxclass": "newobj", "text": "midiout", "patching_rect": [800.0, 655.0, 65.0, 22.0] } },
      { "box": { "id": "phase_ctlout", "maxclass": "newobj", "text": "ctlout 74", "patching_rect": [890.0, 615.0, 75.0, 22.0] } },
      { "box": { "id": "midi_note", "maxclass": "comment", "text": "Wilson ratio → 14-bit bend; phase → CC74; GM percussion channel 10 excluded", "patching_rect": [30.0, 655.0, 520.0, 22.0] } },
      { "box": { "id": "print", "maxclass": "newobj", "text": "print QMW_SYNTHESIS", "patching_rect": [620.0, 195.0, 150.0, 22.0] } },

      { "box": { "id": "op_label", "maxclass": "comment", "text": "operation count", "patching_rect": [30.0, 330.0, 130.0, 22.0] } },
      { "box": { "id": "op_count", "maxclass": "number", "patching_rect": [30.0, 360.0, 70.0, 22.0] } },
      { "box": { "id": "audio_note", "maxclass": "comment", "text": "MIDI now follows the simulated quantum-state trajectory", "patching_rect": [30.0, 400.0, 340.0, 22.0] } },
      { "box": { "id": "basis_label", "maxclass": "comment", "text": "expected basis", "patching_rect": [30.0, 435.0, 95.0, 20.0] } },
      { "box": { "id": "basis_value", "maxclass": "flonum", "patching_rect": [30.0, 458.0, 75.0, 22.0] } },
      { "box": { "id": "dominant_label", "maxclass": "comment", "text": "dominant", "patching_rect": [120.0, 435.0, 70.0, 20.0] } },
      { "box": { "id": "dominant_value", "maxclass": "number", "patching_rect": [120.0, 458.0, 55.0, 22.0] } },
      { "box": { "id": "coherence_label", "maxclass": "comment", "text": "coherence", "patching_rect": [190.0, 435.0, 75.0, 20.0] } },
      { "box": { "id": "coherence_value", "maxclass": "flonum", "patching_rect": [190.0, 458.0, 65.0, 22.0] } },
      { "box": { "id": "entropy_label", "maxclass": "comment", "text": "population H", "patching_rect": [270.0, 435.0, 90.0, 20.0] } },
      { "box": { "id": "entropy_value", "maxclass": "flonum", "patching_rect": [270.0, 458.0, 65.0, 22.0] } },
      { "box": { "id": "entanglement_label", "maxclass": "comment", "text": "entanglement", "patching_rect": [350.0, 435.0, 90.0, 20.0] } },
      { "box": { "id": "entanglement_value", "maxclass": "flonum", "patching_rect": [350.0, 458.0, 65.0, 22.0] } },
      { "box": { "id": "phase_label", "maxclass": "comment", "text": "relative phase", "patching_rect": [430.0, 435.0, 90.0, 20.0] } },
      { "box": { "id": "phase_value", "maxclass": "flonum", "patching_rect": [430.0, 458.0, 70.0, 22.0] } }
    ],
    "lines": [
      { "patchline": { "source": ["qft", 0], "destination": ["osc_pack", 0] } },
      { "patchline": { "source": ["evolution", 0], "destination": ["osc_pack", 0] } },
      { "patchline": { "source": ["clifford", 0], "destination": ["osc_pack", 0] } },
      { "patchline": { "source": ["permutation", 0], "destination": ["osc_pack", 0] } },
      { "patchline": { "source": ["osc_pack", 0], "destination": ["send", 0] } },

      { "patchline": { "source": ["receive", 0], "destination": ["route_qmw", 0] } },
      { "patchline": { "source": ["receive", 0], "destination": ["print", 0] } },
      { "patchline": { "source": ["route_qmw", 0], "destination": ["route_domain", 0] } },
      { "patchline": { "source": ["route_domain", 0], "destination": ["route_circuit", 0] } },
      { "patchline": { "source": ["route_domain", 1], "destination": ["route_synthesis", 0] } },
      { "patchline": { "source": ["route_circuit", 0], "destination": ["route_load", 0] } },
      { "patchline": { "source": ["route_circuit", 1], "destination": ["op_count", 0] } },
      { "patchline": { "source": ["route_load", 0], "destination": ["accepted", 1] } },
      { "patchline": { "source": ["route_load", 1], "destination": ["error", 1] } },
      { "patchline": { "source": ["route_synthesis", 0], "destination": ["route_demo", 0] } },
      { "patchline": { "source": ["route_demo", 0], "destination": ["summary", 1] } },
      { "patchline": { "source": ["route_demo", 1], "destination": ["error", 1] } },
      { "patchline": { "source": ["route_demo", 2], "destination": ["gate_unpack", 0] } },
      { "patchline": { "source": ["route_demo", 4], "destination": ["state_unpack", 0] } },
      { "patchline": { "source": ["gate_unpack", 2], "destination": ["gate_label", 1] } },
      { "patchline": { "source": ["state_unpack", 5], "destination": ["midi_pitch", 0] } },
      { "patchline": { "source": ["state_unpack", 6], "destination": ["midi_velocity", 0] } },
      { "patchline": { "source": ["state_unpack", 7], "destination": ["midi_duration", 0] } },
      { "patchline": { "source": ["state_unpack", 12], "destination": ["xbendout", 0] } },
      { "patchline": { "source": ["state_unpack", 13], "destination": ["phase_ctlout", 0] } },
      { "patchline": { "source": ["state_unpack", 14], "destination": ["xbendout", 1] } },
      { "patchline": { "source": ["state_unpack", 14], "destination": ["phase_ctlout", 2] } },
      { "patchline": { "source": ["state_unpack", 14], "destination": ["makenote", 3] } },
      { "patchline": { "source": ["gate_unpack", 7], "destination": ["basis_value", 0] } },
      { "patchline": { "source": ["gate_unpack", 8], "destination": ["dominant_value", 0] } },
      { "patchline": { "source": ["gate_unpack", 9], "destination": ["coherence_value", 0] } },
      { "patchline": { "source": ["gate_unpack", 10], "destination": ["entropy_value", 0] } },
      { "patchline": { "source": ["gate_unpack", 11], "destination": ["entanglement_value", 0] } },
      { "patchline": { "source": ["gate_unpack", 12], "destination": ["phase_value", 0] } },
      { "patchline": { "source": ["midi_pitch", 0], "destination": ["makenote", 0] } },
      { "patchline": { "source": ["midi_velocity", 0], "destination": ["makenote", 1] } },
      { "patchline": { "source": ["midi_duration", 0], "destination": ["makenote", 2] } },
      { "patchline": { "source": ["makenote", 0], "destination": ["noteout", 0] } },
      { "patchline": { "source": ["makenote", 1], "destination": ["noteout", 1] } },
      { "patchline": { "source": ["makenote", 2], "destination": ["noteout", 2] } },
      { "patchline": { "source": ["xbendout", 0], "destination": ["midiout", 0] } }
    ]
  }
}
