{
  "patcher": {
    "fileversion": 1,
    "appversion": {"major":8,"minor":0,"revision":0,"architecture":"x64","modernui":1},
    "classnamespace": "box",
    "rect": [120.0,120.0,1180.0,700.0],
    "gridsize": [15.0,15.0],
    "boxes": [
      {"box":{"id":"in1","maxclass":"inlet","index":1,"comment":"qubit 0 audio","numinlets":0,"numoutlets":1,"outlettype":["signal"],"patching_rect":[40.0,40.0,30.0,30.0]}},
      {"box":{"id":"in2","maxclass":"inlet","index":2,"comment":"qubit 1 audio","numinlets":0,"numoutlets":1,"outlettype":["signal"],"patching_rect":[90.0,40.0,30.0,30.0]}},
      {"box":{"id":"in3","maxclass":"inlet","index":3,"comment":"qubit 2 audio","numinlets":0,"numoutlets":1,"outlettype":["signal"],"patching_rect":[140.0,40.0,30.0,30.0]}},
      {"box":{"id":"in4","maxclass":"inlet","index":4,"comment":"qubit 3 audio","numinlets":0,"numoutlets":1,"outlettype":["signal"],"patching_rect":[190.0,40.0,30.0,30.0]}},
      {"box":{"id":"global_l","maxclass":"inlet","index":5,"comment":"global/convolution left","numinlets":0,"numoutlets":1,"outlettype":["signal"],"patching_rect":[250.0,40.0,30.0,30.0]}},
      {"box":{"id":"global_r","maxclass":"inlet","index":6,"comment":"global/convolution right","numinlets":0,"numoutlets":1,"outlettype":["signal"],"patching_rect":[300.0,40.0,30.0,30.0]}},
      {"box":{"id":"ctrl1","maxclass":"inlet","index":7,"comment":"qubit 0 Bloch XYZ","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[370.0,40.0,30.0,30.0]}},
      {"box":{"id":"ctrl2","maxclass":"inlet","index":8,"comment":"qubit 1 Bloch XYZ","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[420.0,40.0,30.0,30.0]}},
      {"box":{"id":"ctrl3","maxclass":"inlet","index":9,"comment":"qubit 2 Bloch XYZ","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[470.0,40.0,30.0,30.0]}},
      {"box":{"id":"ctrl4","maxclass":"inlet","index":10,"comment":"qubit 3 Bloch XYZ","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[520.0,40.0,30.0,30.0]}},
      {"box":{"id":"rate_in","maxclass":"inlet","index":11,"comment":"Spat update interval (ms)","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[580.0,40.0,30.0,30.0]}},
      {"box":{"id":"open_in","maxclass":"inlet","index":12,"comment":"open Spat5 window","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[1030.0,40.0,30.0,30.0]}},
      {"box":{"id":"title","maxclass":"comment","text":"Six sources → Spat5 VBAP2D → eight-speaker ring","patching_rect":[370.0,15.0,460.0,20.0]}},
      {"box":{"id":"c1","maxclass":"newobj","text":"qmw_qubit_spat_control /source/1/aed /source/1/aperture /source/1/yaw","patching_rect":[370.0,85.0,430.0,22.0]}},
      {"box":{"id":"c2","maxclass":"newobj","text":"qmw_qubit_spat_control /source/2/aed /source/2/aperture /source/2/yaw","patching_rect":[370.0,120.0,430.0,22.0]}},
      {"box":{"id":"c3","maxclass":"newobj","text":"qmw_qubit_spat_control /source/3/aed /source/3/aperture /source/3/yaw","patching_rect":[370.0,155.0,430.0,22.0]}},
      {"box":{"id":"c4","maxclass":"newobj","text":"qmw_qubit_spat_control /source/4/aed /source/4/aperture /source/4/yaw","patching_rect":[370.0,190.0,430.0,22.0]}},
      {"box":{"id":"oper","maxclass":"newobj","text":"spat5.oper @initwith \"/source/number 6, /source/1/label q0, /source/2/label q1, /source/3/label q2, /source/4/label q3, /source/5/label global-L, /source/6/label global-R, /source/5/aed 45 0 1, /source/6/aed -45 0 1, /source/5/aperture 100, /source/6/aperture 100, /speaker/number 8, /speakers/az 0 45 90 135 180 225 270 315, /speaker/*/vumeter/visible 1, /source/*/aperture/visible 1, /source/*/constraint/circular 0\"","patching_rect":[370.0,245.0,760.0,55.0]}},
      {"box":{"id":"renderer","maxclass":"newobj","text":"spat5.spat~ @inputs 6 @internals 8 @outputs 8 @rooms 1 @initwith \"/panning/type vbap2d\"","patching_rect":[370.0,335.0,650.0,22.0]}},
      {"box":{"id":"loadbang","maxclass":"newobj","text":"loadbang","patching_rect":[815.0,85.0,60.0,22.0]}},
      {"box":{"id":"delay","maxclass":"newobj","text":"delay 750","patching_rect":[885.0,85.0,70.0,22.0]}},
      {"box":{"id":"open","maxclass":"message","text":"/window/open","patching_rect":[885.0,120.0,95.0,22.0]}},
      {"box":{"id":"out1","maxclass":"outlet","index":1,"comment":"speaker 1, 0 degrees","numinlets":1,"numoutlets":0,"patching_rect":[370.0,430.0,30.0,30.0]}},
      {"box":{"id":"out2","maxclass":"outlet","index":2,"comment":"speaker 2, 45 degrees","numinlets":1,"numoutlets":0,"patching_rect":[430.0,430.0,30.0,30.0]}},
      {"box":{"id":"out3","maxclass":"outlet","index":3,"comment":"speaker 3, 90 degrees","numinlets":1,"numoutlets":0,"patching_rect":[490.0,430.0,30.0,30.0]}},
      {"box":{"id":"out4","maxclass":"outlet","index":4,"comment":"speaker 4, 135 degrees","numinlets":1,"numoutlets":0,"patching_rect":[550.0,430.0,30.0,30.0]}},
      {"box":{"id":"out5","maxclass":"outlet","index":5,"comment":"speaker 5, 180 degrees","numinlets":1,"numoutlets":0,"patching_rect":[610.0,430.0,30.0,30.0]}},
      {"box":{"id":"out6","maxclass":"outlet","index":6,"comment":"speaker 6, 225 degrees","numinlets":1,"numoutlets":0,"patching_rect":[670.0,430.0,30.0,30.0]}},
      {"box":{"id":"out7","maxclass":"outlet","index":7,"comment":"speaker 7, 270 degrees","numinlets":1,"numoutlets":0,"patching_rect":[730.0,430.0,30.0,30.0]}},
      {"box":{"id":"out8","maxclass":"outlet","index":8,"comment":"speaker 8, 315 degrees","numinlets":1,"numoutlets":0,"patching_rect":[790.0,430.0,30.0,30.0]}}
    ],
    "lines": [
      {"patchline":{"source":["ctrl1",0],"destination":["c1",0]}},
      {"patchline":{"source":["ctrl2",0],"destination":["c2",0]}},
      {"patchline":{"source":["ctrl3",0],"destination":["c3",0]}},
      {"patchline":{"source":["ctrl4",0],"destination":["c4",0]}},
      {"patchline":{"source":["rate_in",0],"destination":["c1",1]}},
      {"patchline":{"source":["rate_in",0],"destination":["c2",1]}},
      {"patchline":{"source":["rate_in",0],"destination":["c3",1]}},
      {"patchline":{"source":["rate_in",0],"destination":["c4",1]}},
      {"patchline":{"source":["c1",0],"destination":["oper",0]}},
      {"patchline":{"source":["c2",0],"destination":["oper",0]}},
      {"patchline":{"source":["c3",0],"destination":["oper",0]}},
      {"patchline":{"source":["c4",0],"destination":["oper",0]}},
      {"patchline":{"source":["oper",0],"destination":["renderer",0]}},
      {"patchline":{"source":["in1",0],"destination":["renderer",0]}},
      {"patchline":{"source":["in2",0],"destination":["renderer",1]}},
      {"patchline":{"source":["in3",0],"destination":["renderer",2]}},
      {"patchline":{"source":["in4",0],"destination":["renderer",3]}},
      {"patchline":{"source":["global_l",0],"destination":["renderer",4]}},
      {"patchline":{"source":["global_r",0],"destination":["renderer",5]}},
      {"patchline":{"source":["loadbang",0],"destination":["delay",0]}},
      {"patchline":{"source":["delay",0],"destination":["open",0]}},
      {"patchline":{"source":["open_in",0],"destination":["open",0]}},
      {"patchline":{"source":["open",0],"destination":["oper",0]}},
      {"patchline":{"source":["renderer",0],"destination":["out1",0]}},
      {"patchline":{"source":["renderer",1],"destination":["out2",0]}},
      {"patchline":{"source":["renderer",2],"destination":["out3",0]}},
      {"patchline":{"source":["renderer",3],"destination":["out4",0]}},
      {"patchline":{"source":["renderer",4],"destination":["out5",0]}},
      {"patchline":{"source":["renderer",5],"destination":["out6",0]}},
      {"patchline":{"source":["renderer",6],"destination":["out7",0]}},
      {"patchline":{"source":["renderer",7],"destination":["out8",0]}}
    ],
    "autosave": 0
  }
}
