{
  "patcher": {
    "fileversion": 1,
    "appversion": { "major": 9, "minor": 0, "revision": 5, "architecture": "x64", "modernui": 1 },
    "classnamespace": "box",
    "rect": [ 100.0, 100.0, 820.0, 500.0 ],
    "boxes": [
      { "box": { "id": "in-audio", "maxclass": "inlet", "comment": "audio", "patching_rect": [ 45.0, 35.0, 30.0, 30.0 ] } },
      { "box": { "id": "in-mix", "maxclass": "inlet", "comment": "spatial mix 0..1", "patching_rect": [ 330.0, 35.0, 30.0, 30.0 ] } },
      { "box": { "id": "in-decay", "maxclass": "inlet", "comment": "decay 0..1", "patching_rect": [ 600.0, 35.0, 30.0, 30.0 ] } },
      { "box": { "id": "clip-mix", "maxclass": "newobj", "text": "clip 0. 1.", "patching_rect": [ 330.0, 85.0, 65.0, 22.0 ] } },
      { "box": { "id": "dry-expr", "maxclass": "newobj", "text": "expr cos($f1 * 1.5707963)", "patching_rect": [ 265.0, 125.0, 165.0, 22.0 ] } },
      { "box": { "id": "wet-expr", "maxclass": "newobj", "text": "expr sin($f1 * 1.5707963)", "patching_rect": [ 440.0, 125.0, 165.0, 22.0 ] } },
      { "box": { "id": "dry-sig", "maxclass": "newobj", "text": "sig~", "patching_rect": [ 285.0, 165.0, 32.0, 22.0 ] } },
      { "box": { "id": "wet-sig", "maxclass": "newobj", "text": "sig~", "patching_rect": [ 470.0, 165.0, 32.0, 22.0 ] } },
      { "box": { "id": "clip-decay", "maxclass": "newobj", "text": "clip 0. 1.", "patching_rect": [ 600.0, 85.0, 65.0, 22.0 ] } },
      { "box": { "id": "decay-scale", "maxclass": "newobj", "text": "* 0.84", "patching_rect": [ 600.0, 125.0, 45.0, 22.0 ] } },
      { "box": { "id": "decay-sig", "maxclass": "newobj", "text": "sig~", "patching_rect": [ 600.0, 165.0, 32.0, 22.0 ] } },
      { "box": { "id": "feedback-add", "maxclass": "newobj", "text": "+~", "patching_rect": [ 70.0, 130.0, 32.0, 22.0 ] } },
      { "box": { "id": "tapin", "maxclass": "newobj", "text": "tapin~ 1000", "patching_rect": [ 70.0, 175.0, 78.0, 22.0 ] } },
      { "box": { "id": "tapout", "maxclass": "newobj", "text": "tapout~ 137 211", "numoutlets": 2, "outlettype": [ "signal", "signal" ], "patching_rect": [ 70.0, 220.0, 105.0, 22.0 ] } },
      { "box": { "id": "damp-l", "maxclass": "newobj", "text": "onepole~ 0.42", "patching_rect": [ 45.0, 265.0, 88.0, 22.0 ] } },
      { "box": { "id": "damp-r", "maxclass": "newobj", "text": "onepole~ 0.37", "patching_rect": [ 155.0, 265.0, 88.0, 22.0 ] } },
      { "box": { "id": "feedback-sum", "maxclass": "newobj", "text": "+~", "patching_rect": [ 100.0, 305.0, 32.0, 22.0 ] } },
      { "box": { "id": "feedback-half", "maxclass": "newobj", "text": "*~ 0.5", "patching_rect": [ 100.0, 340.0, 48.0, 22.0 ] } },
      { "box": { "id": "feedback-gain", "maxclass": "newobj", "text": "*~", "patching_rect": [ 100.0, 380.0, 32.0, 22.0 ] } },
      { "box": { "id": "dry-l", "maxclass": "newobj", "text": "*~", "patching_rect": [ 300.0, 235.0, 32.0, 22.0 ] } },
      { "box": { "id": "dry-r", "maxclass": "newobj", "text": "*~", "patching_rect": [ 400.0, 235.0, 32.0, 22.0 ] } },
      { "box": { "id": "wet-l", "maxclass": "newobj", "text": "*~", "patching_rect": [ 300.0, 300.0, 32.0, 22.0 ] } },
      { "box": { "id": "wet-r", "maxclass": "newobj", "text": "*~", "patching_rect": [ 400.0, 300.0, 32.0, 22.0 ] } },
      { "box": { "id": "sum-l", "maxclass": "newobj", "text": "+~", "patching_rect": [ 300.0, 355.0, 32.0, 22.0 ] } },
      { "box": { "id": "sum-r", "maxclass": "newobj", "text": "+~", "patching_rect": [ 400.0, 355.0, 32.0, 22.0 ] } },
      { "box": { "id": "out-l", "maxclass": "outlet", "comment": "left", "patching_rect": [ 300.0, 420.0, 30.0, 30.0 ] } },
      { "box": { "id": "out-r", "maxclass": "outlet", "comment": "right", "patching_rect": [ 400.0, 420.0, 30.0, 30.0 ] } }
    ],
    "lines": [
      { "patchline": { "source": [ "in-audio", 0 ], "destination": [ "feedback-add", 0 ] } },
      { "patchline": { "source": [ "feedback-gain", 0 ], "destination": [ "feedback-add", 1 ] } },
      { "patchline": { "source": [ "feedback-add", 0 ], "destination": [ "tapin", 0 ] } },
      { "patchline": { "source": [ "tapin", 0 ], "destination": [ "tapout", 0 ] } },
      { "patchline": { "source": [ "tapout", 0 ], "destination": [ "damp-l", 0 ] } },
      { "patchline": { "source": [ "tapout", 1 ], "destination": [ "damp-r", 0 ] } },
      { "patchline": { "source": [ "damp-l", 0 ], "destination": [ "feedback-sum", 0 ] } },
      { "patchline": { "source": [ "damp-r", 0 ], "destination": [ "feedback-sum", 1 ] } },
      { "patchline": { "source": [ "feedback-sum", 0 ], "destination": [ "feedback-half", 0 ] } },
      { "patchline": { "source": [ "feedback-half", 0 ], "destination": [ "feedback-gain", 0 ] } },
      { "patchline": { "source": [ "decay-sig", 0 ], "destination": [ "feedback-gain", 1 ] } },
      { "patchline": { "source": [ "in-mix", 0 ], "destination": [ "clip-mix", 0 ] } },
      { "patchline": { "source": [ "clip-mix", 0 ], "destination": [ "dry-expr", 0 ] } },
      { "patchline": { "source": [ "clip-mix", 0 ], "destination": [ "wet-expr", 0 ] } },
      { "patchline": { "source": [ "dry-expr", 0 ], "destination": [ "dry-sig", 0 ] } },
      { "patchline": { "source": [ "wet-expr", 0 ], "destination": [ "wet-sig", 0 ] } },
      { "patchline": { "source": [ "in-decay", 0 ], "destination": [ "clip-decay", 0 ] } },
      { "patchline": { "source": [ "clip-decay", 0 ], "destination": [ "decay-scale", 0 ] } },
      { "patchline": { "source": [ "decay-scale", 0 ], "destination": [ "decay-sig", 0 ] } },
      { "patchline": { "source": [ "in-audio", 0 ], "destination": [ "dry-l", 0 ] } },
      { "patchline": { "source": [ "in-audio", 0 ], "destination": [ "dry-r", 0 ] } },
      { "patchline": { "source": [ "dry-sig", 0 ], "destination": [ "dry-l", 1 ] } },
      { "patchline": { "source": [ "dry-sig", 0 ], "destination": [ "dry-r", 1 ] } },
      { "patchline": { "source": [ "damp-l", 0 ], "destination": [ "wet-l", 0 ] } },
      { "patchline": { "source": [ "damp-r", 0 ], "destination": [ "wet-r", 0 ] } },
      { "patchline": { "source": [ "wet-sig", 0 ], "destination": [ "wet-l", 1 ] } },
      { "patchline": { "source": [ "wet-sig", 0 ], "destination": [ "wet-r", 1 ] } },
      { "patchline": { "source": [ "dry-l", 0 ], "destination": [ "sum-l", 0 ] } },
      { "patchline": { "source": [ "wet-l", 0 ], "destination": [ "sum-l", 1 ] } },
      { "patchline": { "source": [ "dry-r", 0 ], "destination": [ "sum-r", 0 ] } },
      { "patchline": { "source": [ "wet-r", 0 ], "destination": [ "sum-r", 1 ] } },
      { "patchline": { "source": [ "sum-l", 0 ], "destination": [ "out-l", 0 ] } },
      { "patchline": { "source": [ "sum-r", 0 ], "destination": [ "out-r", 0 ] } }
    ],
    "autosave": 0
  }
}
