{
  "patcher": {
    "fileversion": 1,
    "appversion": {"major":9,"minor":0,"revision":5,"architecture":"x64","modernui":1},
    "classnamespace": "box",
    "rect": [120.0,120.0,1040.0,620.0],
    "gridsize": [15.0,15.0],
    "boxes": [
      {"box":{"id":"in1","maxclass":"inlet","index":1,"comment":"qubit 0 audio","numinlets":0,"numoutlets":1,"outlettype":["signal"],"patching_rect":[40.0,40.0,30.0,30.0]}},
      {"box":{"id":"in2","maxclass":"inlet","index":2,"comment":"qubit 1 audio","numinlets":0,"numoutlets":1,"outlettype":["signal"],"patching_rect":[110.0,40.0,30.0,30.0]}},
      {"box":{"id":"in3","maxclass":"inlet","index":3,"comment":"qubit 2 audio","numinlets":0,"numoutlets":1,"outlettype":["signal"],"patching_rect":[180.0,40.0,30.0,30.0]}},
      {"box":{"id":"in4","maxclass":"inlet","index":4,"comment":"qubit 3 audio","numinlets":0,"numoutlets":1,"outlettype":["signal"],"patching_rect":[250.0,40.0,30.0,30.0]}},
      {"box":{"id":"ctrl1","maxclass":"inlet","index":5,"comment":"qubit 0 Bloch XYZ","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[330.0,40.0,30.0,30.0]}},
      {"box":{"id":"ctrl2","maxclass":"inlet","index":6,"comment":"qubit 1 Bloch XYZ","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[390.0,40.0,30.0,30.0]}},
      {"box":{"id":"ctrl3","maxclass":"inlet","index":7,"comment":"qubit 2 Bloch XYZ","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[450.0,40.0,30.0,30.0]}},
      {"box":{"id":"ctrl4","maxclass":"inlet","index":8,"comment":"qubit 3 Bloch XYZ","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[510.0,40.0,30.0,30.0]}},
      {"box":{"id":"open_in","maxclass":"inlet","index":9,"comment":"open Spat5 window","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[900.0,40.0,30.0,30.0]}},
      {"box":{"id":"rate_in","maxclass":"inlet","index":10,"comment":"Spat update interval (ms)","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[570.0,40.0,30.0,30.0]}},
      {"box":{"id":"title","maxclass":"comment","text":"Four independent reduced-qubit sources → Spat5 binaural renderer","patching_rect":[330.0,20.0,470.0,20.0]}},
      {"box":{"id":"c1","maxclass":"newobj","text":"qmw_qubit_spat_control /source/1/aed /source/1/aperture /source/1/yaw","patching_rect":[330.0,80.0,430.0,22.0]}},
      {"box":{"id":"c2","maxclass":"newobj","text":"qmw_qubit_spat_control /source/2/aed /source/2/aperture /source/2/yaw","patching_rect":[330.0,115.0,430.0,22.0]}},
      {"box":{"id":"c3","maxclass":"newobj","text":"qmw_qubit_spat_control /source/3/aed /source/3/aperture /source/3/yaw","patching_rect":[330.0,150.0,430.0,22.0]}},
      {"box":{"id":"c4","maxclass":"newobj","text":"qmw_qubit_spat_control /source/4/aed /source/4/aperture /source/4/yaw","patching_rect":[330.0,185.0,430.0,22.0]}},
      {"box":{"id":"oper","maxclass":"newobj","text":"spat5.oper @initwith \"/source/number 4, /source/1/label q0, /source/2/label q1, /source/3/label q2, /source/4/label q3, /source/*/aperture/visible 1, /source/*/constraint/circular 0\"","patching_rect":[330.0,240.0,680.0,42.0]}},
      {"box":{"id":"renderer","maxclass":"newobj","text":"spat5.spat~ @inputs 4 @internals 8 @outputs 2 @rooms 1 @initwith \"/panning/type binaural\"","patching_rect":[330.0,320.0,610.0,22.0]}},
      {"box":{"id":"loadbang","maxclass":"newobj","text":"loadbang","patching_rect":[760.0,80.0,60.0,22.0]}},
      {"box":{"id":"delay","maxclass":"newobj","text":"delay 750","patching_rect":[830.0,80.0,70.0,22.0]}},
      {"box":{"id":"open","maxclass":"message","text":"/window/open","patching_rect":[830.0,115.0,95.0,22.0]}},
      {"box":{"id":"out_l","maxclass":"outlet","index":1,"comment":"binaural left","numinlets":1,"numoutlets":0,"patching_rect":[420.0,410.0,30.0,30.0]}},
      {"box":{"id":"out_r","maxclass":"outlet","index":2,"comment":"binaural right","numinlets":1,"numoutlets":0,"patching_rect":[500.0,410.0,30.0,30.0]}}
    ],
    "lines": [
      {"patchline":{"source":["ctrl1",0],"destination":["c1",0]}},
      {"patchline":{"source":["ctrl2",0],"destination":["c2",0]}},
      {"patchline":{"source":["ctrl3",0],"destination":["c3",0]}},
      {"patchline":{"source":["ctrl4",0],"destination":["c4",0]}},
      {"patchline":{"source":["rate_in",0],"destination":["c1",1]}},
      {"patchline":{"source":["rate_in",0],"destination":["c2",1]}},
      {"patchline":{"source":["rate_in",0],"destination":["c3",1]}},
      {"patchline":{"source":["rate_in",0],"destination":["c4",1]}},
      {"patchline":{"source":["c1",0],"destination":["oper",0]}},
      {"patchline":{"source":["c2",0],"destination":["oper",0]}},
      {"patchline":{"source":["c3",0],"destination":["oper",0]}},
      {"patchline":{"source":["c4",0],"destination":["oper",0]}},
      {"patchline":{"source":["oper",0],"destination":["renderer",0]}},
      {"patchline":{"source":["in1",0],"destination":["renderer",0]}},
      {"patchline":{"source":["in2",0],"destination":["renderer",1]}},
      {"patchline":{"source":["in3",0],"destination":["renderer",2]}},
      {"patchline":{"source":["in4",0],"destination":["renderer",3]}},
      {"patchline":{"source":["loadbang",0],"destination":["delay",0]}},
      {"patchline":{"source":["delay",0],"destination":["open",0]}},
      {"patchline":{"source":["open_in",0],"destination":["open",0]}},
      {"patchline":{"source":["open",0],"destination":["oper",0]}},
      {"patchline":{"source":["renderer",0],"destination":["out_l",0]}},
      {"patchline":{"source":["renderer",1],"destination":["out_r",0]}}
    ],
    "autosave": 0
  }
}
