"""Read-only variational diagnostics for QMW quantum-flow observers.

The probability-flow layer observes transport generated by an authoritative
quantum state and Hamiltonian.  This module adds the corresponding
Schrodinger-action diagnostic for *pure* finite-dimensional states.  It never
updates a state, Hamiltonian, or flow frame.

For a normalized state ``|psi(t)>`` the continuous action is

    S = integral [ i hbar <psi|d psi/dt> - <psi|H|psi> ] dt.

Its first term is evaluated between consecutive samples from their overlap;
the second is the midpoint energy contribution.  The result is a diagnostic
of the supplied evolution, not a new classical dynamics for populations.
Mixed density matrices deliberately have no API here: their variational
description needs additional open-system assumptions.
"""

from __future__ import annotations

from dataclasses import dataclass
import math
from typing import Any, Optional

import numpy as np


Array = np.ndarray
EPS = 1.0e-12


def _positive(name: str, value: float) -> float:
    value = float(value)
    if not math.isfinite(value) or value <= 0.0:
        raise ValueError(f"{name} must be finite and greater than zero.")
    return value


def _time(value: float) -> float:
    value = float(value)
    if not math.isfinite(value):
        raise ValueError("time must be finite.")
    return value


def _state(values: Any, *, tolerance: float) -> Array:
    state = np.asarray(values, dtype=np.complex128)
    if state.ndim != 1 or state.size == 0:
        raise ValueError("state must be a nonempty one-dimensional pure-state vector.")
    if not np.all(np.isfinite(state.real)) or not np.all(np.isfinite(state.imag)):
        raise ValueError("state must contain only finite values.")
    norm_squared = float(np.real(np.vdot(state, state)))
    if abs(norm_squared - 1.0) > tolerance:
        raise ValueError("state must be normalized to one within normalization_tolerance.")
    return np.array(state, dtype=np.complex128, copy=True)


def _hamiltonian(values: Any, dimension: int, *, tolerance: float) -> Array:
    matrix = np.asarray(values, dtype=np.complex128)
    if matrix.shape != (dimension, dimension):
        raise ValueError(f"hamiltonian must have shape ({dimension}, {dimension}).")
    if not np.all(np.isfinite(matrix.real)) or not np.all(np.isfinite(matrix.imag)):
        raise ValueError("hamiltonian must contain only finite values.")
    if not np.allclose(matrix, np.conj(matrix.T), rtol=tolerance, atol=tolerance):
        raise ValueError("hamiltonian must be Hermitian within hermitian_tolerance.")
    return np.array(matrix, dtype=np.complex128, copy=True)


@dataclass(frozen=True)
class SchrodingerActionFrame:
    """Read-only action data for one supplied pure quantum state."""

    time: float
    state: Array
    hamiltonian: Array
    energy: float
    action_increment: Optional[float]
    cumulative_action: float
    dt: Optional[float]
    kinematic_action: Optional[float]
    dynamic_action: Optional[float]


def build_schrodinger_action_frame(
    *,
    state: Any,
    hamiltonian: Any,
    time: float = 0.0,
    hbar: float = 1.0,
    previous: Optional[SchrodingerActionFrame] = None,
    normalization_tolerance: float = 1.0e-9,
    hermitian_tolerance: float = 1.0e-9,
) -> SchrodingerActionFrame:
    """Observe a discrete Schrodinger action from prescribed state samples.

    The discrete kinematic term is ``-hbar * arg(<psi_n|psi_n+1>)``.  For an
    energy eigenstate evolved by its supplied Hamiltonian, it cancels the
    dynamic contribution ``-E_midpoint * dt`` up to sampling error.
    """

    hbar = _positive("hbar", hbar)
    normalization_tolerance = _positive(
        "normalization_tolerance", normalization_tolerance
    )
    hermitian_tolerance = _positive("hermitian_tolerance", hermitian_tolerance)
    logical_time = _time(time)
    state_array = _state(state, tolerance=normalization_tolerance)
    hamiltonian_array = _hamiltonian(
        hamiltonian, state_array.size, tolerance=hermitian_tolerance
    )
    energy = float(np.real(np.vdot(state_array, hamiltonian_array @ state_array)))

    if previous is None:
        return SchrodingerActionFrame(
            time=logical_time,
            state=state_array,
            hamiltonian=hamiltonian_array,
            energy=energy,
            action_increment=None,
            cumulative_action=0.0,
            dt=None,
            kinematic_action=None,
            dynamic_action=None,
        )

    if previous.state.shape != state_array.shape:
        raise ValueError("previous frame must have the same state dimension.")
    if not np.allclose(
        previous.hamiltonian, hamiltonian_array, rtol=hermitian_tolerance,
        atol=hermitian_tolerance,
    ):
        raise ValueError("previous frame must use the same Hamiltonian.")
    dt = logical_time - previous.time
    if dt <= 0.0:
        raise ValueError("time must increase relative to the previous frame.")

    overlap = np.vdot(previous.state, state_array)
    if abs(overlap) <= EPS:
        raise ValueError(
            "consecutive states have zero overlap; the discrete action phase is undefined."
        )
    kinematic_action = -hbar * float(np.angle(overlap))
    dynamic_action = -0.5 * (previous.energy + energy) * dt
    action_increment = kinematic_action + dynamic_action
    return SchrodingerActionFrame(
        time=logical_time,
        state=state_array,
        hamiltonian=hamiltonian_array,
        energy=energy,
        action_increment=action_increment,
        cumulative_action=previous.cumulative_action + action_increment,
        dt=dt,
        kinematic_action=kinematic_action,
        dynamic_action=dynamic_action,
    )


class SchrodingerActionObserver:
    """Stateful convenience wrapper for consecutive read-only observations."""

    def __init__(
        self,
        *,
        hbar: float = 1.0,
        normalization_tolerance: float = 1.0e-9,
        hermitian_tolerance: float = 1.0e-9,
    ) -> None:
        self.hbar = _positive("hbar", hbar)
        self.normalization_tolerance = _positive(
            "normalization_tolerance", normalization_tolerance
        )
        self.hermitian_tolerance = _positive("hermitian_tolerance", hermitian_tolerance)
        self._previous: Optional[SchrodingerActionFrame] = None

    @property
    def previous(self) -> Optional[SchrodingerActionFrame]:
        return self._previous

    def reset(self) -> None:
        self._previous = None

    def observe(
        self, *, state: Any, hamiltonian: Any, time: float = 0.0
    ) -> SchrodingerActionFrame:
        frame = build_schrodinger_action_frame(
            state=state,
            hamiltonian=hamiltonian,
            time=time,
            hbar=self.hbar,
            previous=self._previous,
            normalization_tolerance=self.normalization_tolerance,
            hermitian_tolerance=self.hermitian_tolerance,
        )
        self._previous = frame
        return frame
