"""Physical unitary probability current and membrane-crossing mediation."""

from __future__ import annotations

from dataclasses import dataclass
import math

import numpy as np

from .geometry import MembraneGeometry


Array = np.ndarray


@dataclass(frozen=True)
class BoundaryFlux:
    source: int
    destination: int
    direction: int
    signed_current: float
    magnitude: float
    phase: float
    contact_vertex: int
    current_kind: str = "quantum_probability_unitary"


@dataclass(frozen=True)
class BoundaryCrossing:
    time: float
    source: int
    destination: int
    direction: int
    magnitude: float
    phase: float
    contact_vertex: int
    persistence: int
    transported_probability: float
    current_kind: str = "quantum_probability_unitary"


@dataclass(frozen=True)
class EventBus:
    """Discrete flux quanta that may inject energy but do not define pitch."""

    crossings: tuple[BoundaryCrossing, ...]
    transported_probability: float
    threshold: float
    accumulator_peak_fraction: float
    provenance: str = "boundary_flux_energy_injection"


@dataclass(frozen=True)
class FieldBus:
    """Continuous mesoscopic deformation derived read-only from rho and H.

    Magnetization and susceptibility are bounded effective two-qubit material
    coordinates. They are not calibrated SI magnetic observables.
    """

    regional_magnetization: Array
    regional_magnetization_gradient: Array
    regional_hamiltonian_bias: Array
    modal_frequency_offset_fraction: Array
    modal_susceptibility: Array
    modal_damping_ratio: Array
    modal_quality_factor: Array
    intermodal_coupling: Array
    modal_phase_orientation: Array
    spectral_gradient: Array
    provenance: str = "continuous_effective_mesoscopic_field"


@dataclass(frozen=True)
class FlowFrame:
    time: float
    edge_indices: Array
    currents: Array
    divergence: Array
    region_flux: Array
    boundaries: tuple[BoundaryFlux, ...]
    crossings: tuple[BoundaryCrossing, ...]
    max_current: float
    total_transport: float
    event_bus: EventBus
    field_bus: FieldBus
    current_kind: str = "quantum_probability_unitary"


class QuantumMembraneFlow:
    """Accumulate Hamiltonian current into localized surface crossings.

    The current is the unitary contribution generated by ``H``. Lindblad
    population transfer remains part of authoritative ``rho`` evolution but is
    not mislabeled as Hamiltonian probability current.
    """

    def __init__(self, *, threshold: float = 0.003, hbar: float = 1.0) -> None:
        if threshold <= 0.0 or hbar <= 0.0:
            raise ValueError("threshold and hbar must be positive")
        self.threshold = float(threshold)
        self.hbar = float(hbar)
        self.accumulated: dict[tuple[int, int], float] = {}
        self.last_direction: dict[tuple[int, int], int] = {}
        self.persistence: dict[tuple[int, int], int] = {}

    def reset(self) -> None:
        self.accumulated.clear()
        self.last_direction.clear()
        self.persistence.clear()

    def set_threshold(self, value: float) -> float:
        """Change the event quantum while preserving each accumulator's phase."""
        value = float(value)
        if not math.isfinite(value) or not 1.0e-5 <= value <= 0.05:
            raise ValueError("event threshold must lie in [1e-5, 0.05]")
        ratio = value / self.threshold
        self.accumulated = {
            key: min(remainder * ratio, value * (1.0 - 1.0e-12))
            for key, remainder in self.accumulated.items()
        }
        self.threshold = value
        return self.threshold

    @staticmethod
    def _mode_region_participation(geometry: MembraneGeometry) -> Array:
        """Return mass-weighted regional participation for each fixed mode."""
        squared = geometry.vertex_area[:, None] * geometry.mode_shapes**2
        participation = np.zeros((geometry.mode_shapes.shape[1], 4), dtype=float)
        for region in range(4):
            participation[:, region] = np.sum(
                squared[geometry.regions == region], axis=0
            )
        totals = np.sum(participation, axis=1, keepdims=True)
        return participation / np.maximum(totals, 1.0e-12)

    def _continuous_field(
        self,
        rho: Array,
        hamiltonian: Array,
        geometry: MembraneGeometry,
    ) -> FieldBus:
        """Derive the always-on FIELD bus without thresholding or memory."""
        populations = np.maximum(np.real(np.diag(rho)), 0.0)
        coherence = np.abs(rho).copy()
        np.fill_diagonal(coherence, 0.0)
        local_coherence = np.sum(coherence, axis=1) / max(1, rho.shape[0] - 1)

        # Computational-basis eigenvalues of (ZI + IZ) / 2. The resulting
        # regional coordinate is an effective magnetization texture.
        magnetization_eigenvalues = np.array([1.0, 0.0, 0.0, -1.0])
        magnetization = magnetization_eigenvalues * populations
        hamiltonian_weights = np.abs(hamiltonian).copy()
        np.fill_diagonal(hamiltonian_weights, 0.0)
        weight_sum = np.sum(hamiltonian_weights, axis=1)
        magnetization_gradient = np.sum(
            hamiltonian_weights * (magnetization[None, :] - magnetization[:, None]),
            axis=1,
        ) / np.maximum(weight_sum, 1.0e-12)

        hamiltonian_bias = np.real(np.diag(hamiltonian)).copy()
        hamiltonian_bias -= float(np.mean(hamiltonian_bias))
        hamiltonian_bias /= max(float(np.max(np.abs(hamiltonian_bias))), 1.0e-12)

        participation = self._mode_region_participation(geometry)
        receptive_regions = np.clip(
            (4.0 * populations * (1.0 - populations) + 0.5 * local_coherence)
            / 1.5,
            0.0,
            1.0,
        )
        modal_susceptibility = np.clip(
            participation @ receptive_regions, 0.0, 1.0
        )
        regional_deformation = (
            0.11 * magnetization
            + 0.08 * magnetization_gradient
            + 0.07 * local_coherence
            + 0.045 * hamiltonian_bias
        )
        frequency_offsets = np.clip(
            participation @ regional_deformation, -0.22, 0.22
        )

        coherence_fraction = float(
            np.clip(np.sum(coherence) / max(1, rho.shape[0] - 1), 0.0, 1.0)
        )
        damping_ratio = np.clip(
            0.025
            + 0.22 * (1.0 - modal_susceptibility)
            + 0.12 * (1.0 - coherence_fraction),
            0.02,
            0.40,
        )
        quality_factor = 1.0 / (2.0 * damping_ratio)

        regional_phasor = np.sum(rho - np.diag(np.diag(rho)), axis=1)
        modal_phasor = participation @ regional_phasor
        phase_orientation = np.angle(modal_phasor)

        projected_coherence = np.abs(participation @ (rho - np.diag(np.diag(rho))) @ participation.T)
        projected_coherence = 0.5 * (projected_coherence + projected_coherence.T)
        np.fill_diagonal(projected_coherence, 0.0)
        coupling_peak = float(np.max(np.sum(projected_coherence, axis=1)))
        if coupling_peak > 1.0e-12:
            projected_coherence *= 0.12 / coupling_peak

        spectral_gradient = (
            np.gradient(frequency_offsets)
            if frequency_offsets.size > 1
            else np.zeros_like(frequency_offsets)
        )
        return FieldBus(
            regional_magnetization=magnetization,
            regional_magnetization_gradient=magnetization_gradient,
            regional_hamiltonian_bias=hamiltonian_bias,
            modal_frequency_offset_fraction=frequency_offsets,
            modal_susceptibility=modal_susceptibility,
            modal_damping_ratio=damping_ratio,
            modal_quality_factor=quality_factor,
            intermodal_coupling=projected_coherence,
            modal_phase_orientation=phase_orientation,
            spectral_gradient=spectral_gradient,
        )

    def observe(
        self,
        rho: Array,
        hamiltonian: Array,
        geometry: MembraneGeometry,
        *,
        time: float,
        dt: float,
    ) -> FlowFrame:
        rho = np.asarray(rho, dtype=np.complex128)
        hamiltonian = np.asarray(hamiltonian, dtype=np.complex128)
        if rho.shape != hamiltonian.shape or rho.ndim != 2 or rho.shape[0] != rho.shape[1]:
            raise ValueError("rho and Hamiltonian must be equal square matrices")
        if rho.shape[0] != 4:
            raise ValueError("v1 membrane geometry declares four density-basis regions")
        if not math.isfinite(dt) or dt < 0.0:
            raise ValueError("dt must be finite and nonnegative")
        divergence = np.zeros(4, dtype=float)
        edges: list[tuple[int, int]] = []
        currents: list[float] = []
        boundaries: list[BoundaryFlux] = []
        crossings: list[BoundaryCrossing] = []
        for left in range(4):
            for right in range(left + 1, 4):
                if abs(hamiltonian[left, right]) <= 1.0e-12:
                    continue
                signed = float(
                    -(2.0 / self.hbar)
                    * np.imag(hamiltonian[left, right] * rho[right, left])
                )
                direction = 1 if signed > 1.0e-12 else (-1 if signed < -1.0e-12 else 0)
                source, destination = (left, right) if direction >= 0 else (right, left)
                phase = float(np.angle(rho[source, destination]))
                contact = geometry.contact_vertex(source, destination, phase)
                magnitude = abs(signed)
                edges.append((left, right))
                currents.append(signed)
                divergence[left] += signed
                divergence[right] -= signed
                boundaries.append(
                    BoundaryFlux(
                        source=source,
                        destination=destination,
                        direction=direction,
                        signed_current=signed,
                        magnitude=magnitude,
                        phase=phase,
                        contact_vertex=contact,
                    )
                )
                key = (left, right)
                if direction != 0:
                    if self.last_direction.get(key) == direction:
                        self.persistence[key] = self.persistence.get(key, 0) + 1
                    else:
                        self.persistence[key] = 1
                    self.last_direction[key] = direction
                total = self.accumulated.get(key, 0.0) + magnitude * dt
                count = min(8, int((total + 1.0e-15) // self.threshold))
                self.accumulated[key] = max(0.0, total - count * self.threshold)
                for _ in range(count):
                    crossings.append(
                        BoundaryCrossing(
                            time=float(time), source=source, destination=destination,
                            direction=direction, magnitude=magnitude, phase=phase,
                            contact_vertex=contact,
                            persistence=self.persistence.get(key, 0),
                            transported_probability=self.threshold,
                        )
                    )
        current_array = np.asarray(currents, dtype=float)
        event_bus = EventBus(
            crossings=tuple(crossings),
            transported_probability=len(crossings) * self.threshold,
            threshold=self.threshold,
            accumulator_peak_fraction=float(np.clip(
                max(self.accumulated.values(), default=0.0) / self.threshold,
                0.0,
                1.0,
            )),
        )
        field_bus = self._continuous_field(rho, hamiltonian, geometry)
        return FlowFrame(
            time=float(time),
            edge_indices=np.asarray(edges, dtype=int).reshape((-1, 2)),
            currents=current_array,
            divergence=divergence,
            region_flux=-divergence,
            boundaries=tuple(boundaries),
            crossings=tuple(crossings),
            max_current=float(np.max(np.abs(current_array))) if current_array.size else 0.0,
            total_transport=float(np.sum(np.abs(current_array))),
            event_bus=event_bus,
            field_bus=field_bus,
        )


__all__ = [
    "BoundaryCrossing",
    "BoundaryFlux",
    "EventBus",
    "FieldBus",
    "FlowFrame",
    "QuantumMembraneFlow",
]
