from qmw.core.spec import ModuleSpec, PortSpec, ParameterSpec


def module_specs() -> list[ModuleSpec]:
    """A module's equation, units, assumptions and destinations travel together."""
    spatial = "space_1d: scaled periodic spatial grid"
    def port(name, quantity, unit, domain=spatial):
        return PortSpec(name, quantity, unit, domain)
    return [
        ModuleSpec("schrodinger", "Schrödinger evolution",
            r"i\hbar\partial_t\psi=\left[-\frac{\hbar^2}{2m}\partial_x^2+V(x,t)\right]\psi",
            "iℏ ∂ₜψ = [−ℏ²/(2m) ∂ₓ² + V(x,t)] ψ",
            (port("controls", "mass and potential parameters", "scaled units"),),
            (port("psi", "complex pure-state wavefunction", "scaled amplitude"),),
            (ParameterSpec("mass", "Mass m", .5, .1, 5, "scaled mass", "Controls kinetic dispersion; not audio gain"),),
            "Symmetric potential–kinetic–potential Fourier splitting evolves the spatial field.",
            ("density", "current", "energy", "energy_flux", "modes"),
            assumptions=("Periodic 1-D grid; real smooth potential; scaled ℏ=1",)),
        ModuleSpec("scalar", "Complex scalar-field evolution",
            r"\partial_t\Phi=\Pi,\quad\partial_t\Pi=\partial_x^2\Phi-2U'(|\Phi|^2)\Phi",
            "∂ₜΦ = Π;   ∂ₜΠ = ∂ₓ²Φ − 2U′(|Φ|²)Φ",
            (port("U", "U( |Φ|² )", "scaled energy density"),),
            (port("phi", "complex scalar field", "scaled field"), port("pi", "field velocity", "field / simulation time")),
            description="Velocity-Verlet evolution with the explicit ½ kinetic normalization. A rotating Gaussian is a field initializer, not a verified Q-ball.",
            destinations=("energy", "energy_flux", "regions", "modes"),
            assumptions=("Periodic 1-D domain; c=1; U(1)-symmetric potential; stable numerical timestep",)),
        ModuleSpec("lindblad", "Lindblad evolution",
            r"\dot\rho=-\frac{i}{\hbar}[H,\rho]+\sum_k\left(C_k\rho C_k^\dagger-\frac12\{C_k^\dagger C_k,\rho\}\right)",
            "ρ̇ = −i/ℏ [H,ρ] + Σₖ (CₖρCₖ† − ½{Cₖ†Cₖ,ρ})",
            (port("H", "Hermitian Hamiltonian", "scaled energy", "finite basis"), port("C", "collapse operators", "1/√simulation time", "finite basis")),
            (port("rho", "density matrix", "dimensionless", "finite basis"),),
            description="Finite-dimensional density-matrix evolution; the basis populations are not a spatial field.",
            destinations=("regions", "modes", "diagnostics"),
            assumptions=("Mixed states have no unique ψ phase or local spatial current",)),
        ModuleSpec("density", "Probability density / field magnitude",
            r"p(x,t)=|\psi(x,t)|^2,\quad \int p\,dx=1",
            "p(x,t) = |ψ(x,t)|²;    ∫p dx = 1",
            (port("psi", "wavefunction", "scaled amplitude"),),
            (port("probability_density", "probability per scaled length", "1 / scaled length"),),
            description="Pure-state density is integrated with the grid quadrature. Scalar |Φ|² is a field magnitude, not normalized probability; Lindblad diagonal entries are basis probabilities.",
            destinations=("regions", "diagnostics", "field visualization")),
        ModuleSpec("current", "Probability current",
            r"j=\frac{\hbar}{m}\operatorname{Im}(\psi^*\partial_x\psi)",
            "j = (ℏ/m) Im(ψ* ∂ₓψ)",
            (port("psi", "wavefunction", "scaled amplitude"),),
            (port("probability_current", "signed probability flow", "probability / simulation time"),),
            description="The spatial Fourier derivative uses the same periodic domain as the solver. Positive values move to increasing x.",
            destinations=("regions", "diagnostics", "flow visualization"),
            assumptions=("This equation is for a spatial Schrödinger wavefunction",)),
        ModuleSpec("energy", "Local energy density",
            r"e_K=\frac{\hbar^2}{2m}|\partial_x\psi|^2,\quad e_V=V|\psi|^2,\quad e=e_K+e_V",
            "eₖ = ℏ²/(2m)|∂ₓψ|²;   eᵥ = V|ψ|²;   e = eₖ + eᵥ",
            (port("psi", "wavefunction", "scaled amplitude"), port("V", "potential", "scaled energy")),
            (port("total_energy_density", "model-specific local energy", "scaled energy / scaled length"),),
            description="The scalar engine instead uses e=½|Π|²+½|∂ₓΦ|²+U. Each model owns its energy definition. Time-varying controls do external work.",
            destinations=("regions", "energy_flux", "diagnostics", "energy visualization")),
        ModuleSpec("energy_flux", "Energy flux",
            r"S_E=-\frac{\hbar^2}{m}\operatorname{Re}[(\partial_t\psi)^*\partial_x\psi],\quad\partial_t e+\partial_x S_E=(\partial_t V)p",
            "Sₑ = −ℏ²/m Re[(∂ₜψ)* ∂ₓψ];   ∂ₜe + ∂ₓSₑ = (∂ₜV)p",
            (port("psi", "wavefunction", "scaled amplitude"),),
            (port("energy_flux", "signed energy transport", "scaled energy / simulation time"),),
            description="Scalar fields use Sₑ=−Re(Π* ∂ₓΦ). Flux is transport; the external-work term is reported separately.",
            destinations=("regions", "events", "diagnostics")),
        ModuleSpec("regions", "Weighted regional projection",
            r"E_i=\sum_nw_i[n]e[n]\,\Delta x,\quad F_i=-\sum_nw_i[n]\partial_xS_E[n]\,\Delta x",
            "Eᵢ = Δx Σₙ wᵢ[n]e[n];   Fᵢ = −Δx Σₙ wᵢ[n]∂ₓSₑ[n]",
            (port("energy_flux", "energy transport", "scaled energy / simulation time"), port("energy_density", "local energy", "scaled energy / scaled length")),
            (port("regional_energy", "integrated region energy", "scaled energy", "16 regions"), port("incoming_energy_flux", "net energy arriving per region", "scaled energy / simulation time", "16 regions")),
            description="Partition masks sum to one, so the 16 regional integrals sum to the full field integral. Projection does not coarsen the solver.",
            destinations=("events", "sound", "regional visualization")),
        ModuleSpec("modes", "Weighted modal projection",
            r"B^\dagger W B=I,\quad c=B^\dagger W\psi,\quad M_j=|c_j|^2",
            "B†WB = I;   c = B†Wψ;   Mⱼ = |cⱼ|²",
            (port("psi", "wavefunction", "scaled amplitude"),),
            (port("populations", "named-basis modal activity", "dimensionless", "mode_index"),),
            description="A truncated basis captures only its declared fraction of norm. Eigenvalues retain their physical operator semantics; they are not audible Hz.",
            destinations=("events", "sound", "mode visualization")),
        ModuleSpec("events", "Flux threshold articulation",
            r"F_i>\theta_{\rm on},\quad F_i<\theta_{\rm off}\Rightarrow\mathrm{rearm},\quad \Delta t\geq t_{\rm refractory}",
            "Fᵢ > θₒₙ → event;   Fᵢ < θₒff → rearm;   Δt ≥ refractory time",
            (port("incoming_energy_flux", "regional incoming flux", "scaled energy / simulation time", "regions"),),
            (port("events", "timestamped articulations", "simulation time", "event stream"),),
            description="Hysteresis and a refractory interval avoid a new note at every numerical step. Event details retain the actual source, threshold and reason.",
            destinations=("sound", "event history"), classification="DETECTOR"),
        ModuleSpec("sound", "Harmonic pluck mapping",
            r"f_i=f_0(i+1),\quad A_i=g\sqrt{\min(F_i/F_{\rm ref},1)}",
            "fᵢ = f₀(i+1);   Aᵢ = g √min(source/Fᵣₑf, 1)",
            (port("events", "physical event magnitudes", "scaled simulation units", "event stream"),),
            (port("sound", "Hz, gain, decay and pan", "audio units", "sound controls"),),
            description="The fundamental, integer ratios, amplitude reference and audio decay are declared musical choices. Incoming flux triggers plucks; regional energy also sets inspection amplitudes.",
            destinations=("OSC → SuperCollider", "offline WAV"), classification="MUSICAL MAPPING",
            assumptions=("Eight harmonic partials with shorter upper-partial decays; no noise excitation",)),
        ModuleSpec("diagnostics", "Conservation and numerical checks",
            r"R_p=\partial_t p+\partial_xj,\quad R_E=\partial_t e+\partial_xS_E-P",
            "Rₚ = ∂ₜp + ∂ₓj;   Rₑ = ∂ₜe + ∂ₓSₑ − P",
            (port("observables", "model quantities and sources", "scaled units"),),
            (port("diagnostics", "residuals and invariant errors", "reported scaled units", "scalars"),),
            description="Norm, energy/work balance, charge, trace, positivity and continuity errors are distinct. Missing quantities are unavailable. Physical work and environmental dissipation are not labeled numerical error.",
            destinations=("diagnostic visualization", "JSON recording"), classification="VERIFICATION")
    ]
