"""A clock whose increments are generated by density-matrix displacement."""

from __future__ import annotations

from dataclasses import asdict, dataclass
import math

import numpy as np

from .core import density_matrix


def density_fidelity(rho: np.ndarray, sigma: np.ndarray) -> float:
    rho = density_matrix(rho)
    sigma = density_matrix(sigma)
    values, vectors = np.linalg.eigh(rho)
    root = (vectors * np.sqrt(np.clip(values, 0.0, None))) @ vectors.conj().T
    middle = root @ sigma @ root
    middle = 0.5 * (middle + middle.conj().T)
    value = np.sum(np.sqrt(np.clip(np.linalg.eigvalsh(middle), 0.0, None))) ** 2
    return float(np.clip(value, 0.0, 1.0))


@dataclass(frozen=True)
class DensityClockReading:
    source_revision: int
    record_index: int
    intrinsic_time: float
    delta_bures: float
    remainder: float
    phase: float
    coherence: float
    purity: float
    population_flux: float
    coherence_flux: float
    coherence_flux_ema: float
    coherence_gain: float
    hazard_increment: float
    negativity: float
    projection_error: float
    next_record_distance: float
    pulses: int

    def to_dict(self):
        return asdict(self)


class DensityMatrixClock:
    """Accumulate Bures angle and emit records at invariant arc intervals.

    The observation loop never advances ``record_index``. Only displacement
    of the supplied density operator can do that. The resulting unit is a
    configurable quantum-state distance, not a wall-clock second.
    """

    def __init__(
        self,
        distance_per_pulse: float = 0.025,
        max_pulses_per_update: int = 8,
        mode: str = "poisson",
        seed: int = 23,
        coherence_depth: float = 0.35,
        coherence_ema_alpha: float = 0.1,
    ) -> None:
        if distance_per_pulse <= 0:
            raise ValueError("distance_per_pulse must be positive")
        self.distance_per_pulse = float(distance_per_pulse)
        self.max_pulses_per_update = max(1, int(max_pulses_per_update))
        self.rng = np.random.default_rng(seed)
        self.mode = self._validate_mode(mode)
        self.coherence_depth = self._validate_coherence_depth(coherence_depth)
        if not 0.0 < coherence_ema_alpha <= 1.0:
            raise ValueError("coherence_ema_alpha must be in (0, 1]")
        self.coherence_ema_alpha = float(coherence_ema_alpha)
        self.coherence_flux_ema = 0.0
        self.previous: np.ndarray | None = None
        self.remainder = 0.0
        self.intrinsic_time = 0.0
        self.record_index = 0
        self.next_record_distance = self._draw_record_distance()

    @staticmethod
    def _validate_mode(value: str) -> str:
        value = str(value).strip().lower()
        if value not in {"poisson", "fixed"}:
            raise ValueError("clock mode must be 'poisson' or 'fixed'")
        return value

    def _draw_record_distance(self) -> float:
        if self.mode == "fixed":
            return self.distance_per_pulse
        return max(float(self.rng.exponential(self.distance_per_pulse)), 1e-12)

    def set_distance_per_pulse(self, value: float) -> float:
        value = float(value)
        if not np.isfinite(value) or value <= 0.0:
            raise ValueError("distance_per_pulse must be finite and positive")
        self.distance_per_pulse = value
        self.next_record_distance = self._draw_record_distance()
        return value

    def set_mode(self, value: str) -> str:
        self.mode = self._validate_mode(value)
        self.next_record_distance = self._draw_record_distance()
        return self.mode

    @staticmethod
    def _validate_coherence_depth(value: float) -> float:
        value = float(value)
        if not np.isfinite(value) or not 0.0 <= value <= 1.0:
            raise ValueError("coherence_depth must be between 0 and 1")
        return value

    def set_coherence_depth(self, value: float) -> float:
        self.coherence_depth = self._validate_coherence_depth(value)
        return self.coherence_depth

    @staticmethod
    def _phase_and_coherence(rho: np.ndarray) -> tuple[float, float]:
        off_diagonal = rho.copy()
        np.fill_diagonal(off_diagonal, 0.0)
        flat_index = int(np.argmax(np.abs(off_diagonal)))
        strongest = off_diagonal.flat[flat_index]
        coherence = float(np.sum(np.abs(off_diagonal)) / max(1, len(rho) - 1))
        phase = float(np.angle(strongest) % math.tau) if abs(strongest) > 1e-15 else 0.0
        return phase, coherence

    @staticmethod
    def _physical_projection(rho: np.ndarray) -> tuple[np.ndarray, float, float]:
        """Project a serialized/evolved matrix onto the density-operator cone.

        Live numerical engines and 32-bit OSC floats can introduce small
        negative eigenvalues. The size of the repair remains observable via
        ``negativity`` and ``projection_error`` rather than being hidden.
        """
        value = np.asarray(rho, dtype=np.complex128)
        if value.ndim != 2 or value.shape[0] != value.shape[1]:
            raise ValueError("rho must be a square matrix")
        hermitian = 0.5 * (value + value.conj().T)
        trace = float(np.trace(hermitian).real)
        if not np.isfinite(hermitian).all() or trace <= 1e-15:
            raise ValueError("rho is non-finite or has non-positive trace")
        hermitian /= trace
        eigenvalues, eigenvectors = np.linalg.eigh(hermitian)
        negativity = float(np.sum(np.clip(-eigenvalues, 0.0, None)))
        clipped = np.clip(eigenvalues, 0.0, None)
        if float(clipped.sum()) <= 1e-15:
            raise ValueError("rho has no positive spectral weight")
        projected = (eigenvectors * clipped) @ eigenvectors.conj().T
        projected /= np.trace(projected)
        error = float(np.linalg.norm(projected - hermitian))
        return projected, negativity, error

    def update(self, rho: np.ndarray, source_revision: int = 0) -> DensityClockReading:
        current, negativity, projection_error = self._physical_projection(rho)
        purity = float(np.trace(current @ current).real)
        phase, coherence = self._phase_and_coherence(current)
        delta = 0.0
        population_flux = 0.0
        coherence_flux = 0.0
        if self.previous is not None:
            fidelity = density_fidelity(self.previous, current)
            delta = float(math.acos(math.sqrt(np.clip(fidelity, 0.0, 1.0))))
            population_flux = float(0.5 * np.sum(np.abs(np.diag(current - self.previous).real)))
            off_delta = current - self.previous
            np.fill_diagonal(off_delta, 0.0)
            coherence_flux = float(np.linalg.norm(off_delta))

        if self.previous is None:
            coherence_gain = 1.0
        else:
            if self.coherence_flux_ema <= 1e-15:
                self.coherence_flux_ema = coherence_flux
            else:
                alpha = self.coherence_ema_alpha
                self.coherence_flux_ema = (
                    (1.0 - alpha) * self.coherence_flux_ema
                    + alpha * coherence_flux
                )
            if self.coherence_flux_ema <= 1e-15:
                normalized_flux = 1.0
            else:
                normalized_flux = float(
                    np.clip(coherence_flux / self.coherence_flux_ema, 0.25, 4.0)
                )
            coherence_gain = (
                1.0 - self.coherence_depth
                + self.coherence_depth * normalized_flux
            )

        self.intrinsic_time += delta
        hazard_increment = delta * coherence_gain
        self.remainder += hazard_increment
        pulses = 0
        while (
            self.remainder + 1e-15 >= self.next_record_distance
            and pulses < self.max_pulses_per_update
        ):
            self.remainder -= self.next_record_distance
            pulses += 1
            self.next_record_distance = self._draw_record_distance()
        self.record_index += pulses
        self.previous = current.copy()
        return DensityClockReading(
            source_revision=int(source_revision),
            record_index=self.record_index,
            intrinsic_time=self.intrinsic_time,
            delta_bures=delta,
            remainder=self.remainder,
            phase=phase,
            coherence=coherence,
            purity=purity,
            population_flux=population_flux,
            coherence_flux=coherence_flux,
            coherence_flux_ema=self.coherence_flux_ema,
            coherence_gain=coherence_gain,
            hazard_increment=hazard_increment,
            negativity=negativity,
            projection_error=projection_error,
            next_record_distance=self.next_record_distance,
            pulses=pulses,
        )
