"""NetworkX-to-quantum-circuit composition, notation, and audio experiment."""

from .core import (
    QuantumGraphCanonConfig,
    QuantumGraphCanonExperiment,
    build_default_experiment,
    build_default_source_graph,
    build_four_region_quotient_graph,
    build_graph_conditioned_density_snapshots,
    build_quantum_graph_canon_score,
    encode_quotient_graph,
    experiment_manifest,
)
from .qnn import (
    QuantumGraphQNNConfig,
    QuantumGraphQNNExperiment,
    QuantumGraphQNNResult,
    QuantumGraphSamplerQNN,
    build_qnn_conditioned_experiment,
    build_qnn_conditioned_score,
    build_topology_preserving_sampler_qnn,
    condition_graph_with_qnn,
    graph_qnn_input_vector,
    qnn_experiment_manifest,
    run_graph_sampler_qnn,
    seeded_untrained_weights,
)
from .wavetable_audio import (
    ArticulatedDensityWavetableConfig,
    ArticulatedDensityWavetableRenderResult,
    DensityWavetableRenderConfig,
    DensityWavetableRenderResult,
    articulated_density_wavetable_manifest,
    density_voice_parameters,
    density_wavetable_manifest,
    graph_qnn_voice_offsets,
    render_articulated_density_wavetable_bank,
    render_density_wavetable_bank,
    voice_wavetables_from_density,
    write_density_wavetable_wav,
)

__all__ = [
    "QuantumGraphCanonConfig",
    "QuantumGraphCanonExperiment",
    "build_default_experiment",
    "build_default_source_graph",
    "build_four_region_quotient_graph",
    "build_graph_conditioned_density_snapshots",
    "build_quantum_graph_canon_score",
    "encode_quotient_graph",
    "experiment_manifest",
    "QuantumGraphQNNConfig",
    "QuantumGraphQNNExperiment",
    "QuantumGraphQNNResult",
    "QuantumGraphSamplerQNN",
    "build_qnn_conditioned_experiment",
    "build_qnn_conditioned_score",
    "build_topology_preserving_sampler_qnn",
    "condition_graph_with_qnn",
    "graph_qnn_input_vector",
    "qnn_experiment_manifest",
    "run_graph_sampler_qnn",
    "seeded_untrained_weights",
    "DensityWavetableRenderConfig",
    "DensityWavetableRenderResult",
    "ArticulatedDensityWavetableConfig",
    "ArticulatedDensityWavetableRenderResult",
    "articulated_density_wavetable_manifest",
    "density_voice_parameters",
    "density_wavetable_manifest",
    "graph_qnn_voice_offsets",
    "render_articulated_density_wavetable_bank",
    "render_density_wavetable_bank",
    "voice_wavetables_from_density",
    "write_density_wavetable_wav",
]
