"""Physical/control model for the QMW Zeeman Resonator.

The optical Zeeman displacement is far above the range useful as an audible
modulator.  The model therefore keeps the physical displacement as metadata
and exposes a separate perceptual scale in audible Hz per tesla.  Relative
Landé-factor geometry, degeneracy, selection-rule families, and intensities
are preserved.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import sqrt
from typing import Final


BOHR_MAGNETON_OVER_H_HZ_PER_T: Final[float] = 13_996_245_550.0


def lande_g(l_value: float, s_value: float, j_value: float) -> float:
    """Return the LS-coupled Landé g factor.

    A J=0 level has no first-order Zeeman displacement and is assigned zero.
    """

    if j_value == 0.0:
        return 0.0
    jj = j_value * (j_value + 1.0)
    return 1.0 + (
        jj + s_value * (s_value + 1.0) - l_value * (l_value + 1.0)
    ) / (2.0 * jj)


@dataclass(frozen=True)
class RingComponent:
    """One symmetric pair generated by a quadrature ring-modulator voice."""

    shift_factor: float
    relative_strength: float
    polarization: str
    label: str

    def audible_shift_hz(self, field_t: float, spread_hz_per_t: float) -> float:
        return abs(self.shift_factor * field_t * spread_hz_per_t)

    def physical_shift_hz(self, field_t: float) -> float:
        return abs(self.shift_factor * field_t * BOHR_MAGNETON_OVER_H_HZ_PER_T)


@dataclass(frozen=True)
class ZeemanPreset:
    """A transition reduced to symmetric sideband pairs plus an optional π line."""

    key: str
    title: str
    lower_term: str
    upper_term: str
    lower_g: float
    upper_g: float
    components: tuple[RingComponent, ...]
    dry_pi_strength: float

    def normalized_amplitudes(self) -> tuple[float, ...]:
        """Return constant-power amplitudes for the ring-bank components."""

        if not self.components:
            return ()
        roots = tuple(sqrt(item.relative_strength) for item in self.components)
        norm = sqrt(sum(value * value for value in roots))
        return tuple(value / norm for value in roots)

    def state(
        self,
        field_t: float,
        spread_hz_per_t: float,
        carrier_hz: float,
    ) -> dict[str, object]:
        """Return a serializable snapshot for UI, OSC, or offline rendering."""

        amplitudes = self.normalized_amplitudes()
        voices = []
        for component, amplitude in zip(self.components, amplitudes):
            shift = component.audible_shift_hz(field_t, spread_hz_per_t)
            voices.append(
                {
                    "label": component.label,
                    "polarization": component.polarization,
                    "shift_factor": component.shift_factor,
                    "audible_shift_hz": shift,
                    "physical_shift_hz": component.physical_shift_hz(field_t),
                    "lower_hz": carrier_hz - shift,
                    "upper_hz": carrier_hz + shift,
                    "amplitude": amplitude,
                }
            )
        return {
            "preset": self.key,
            "title": self.title,
            "field_t": field_t,
            "carrier_hz": carrier_hz,
            "spread_hz_per_t": spread_hz_per_t,
            "dry_pi_strength": self.dry_pi_strength,
            "voices": voices,
        }


NORMAL_G = lande_g(1.0, 0.0, 1.0)
S_G = lande_g(0.0, 0.5, 0.5)
P_HALF_G = lande_g(1.0, 0.5, 0.5)
P_THREE_HALF_G = lande_g(1.0, 0.5, 1.5)


PRESETS: Final[dict[str, ZeemanPreset]] = {
    "normal": ZeemanPreset(
        key="normal",
        title="Normal Zeeman triplet",
        lower_term="1S0",
        upper_term="1P1",
        lower_g=0.0,
        upper_g=NORMAL_G,
        components=(
            RingComponent(1.0, 1.0, "sigma", "sigma- / sigma+"),
        ),
        dry_pi_strength=1.0,
    ),
    "sodium_d1": ZeemanPreset(
        key="sodium_d1",
        title="Anomalous sodium-like D1 quartet",
        lower_term="2S1/2",
        upper_term="2P1/2",
        lower_g=S_G,
        upper_g=P_HALF_G,
        components=(
            RingComponent(2.0 / 3.0, 1.0 / 3.0, "pi", "inner pi pair"),
            RingComponent(4.0 / 3.0, 2.0 / 3.0, "sigma", "outer sigma pair"),
        ),
        dry_pi_strength=0.0,
    ),
    "sodium_d2": ZeemanPreset(
        key="sodium_d2",
        title="Anomalous sodium-like D2 sextet",
        lower_term="2S1/2",
        upper_term="2P3/2",
        lower_g=S_G,
        upper_g=P_THREE_HALF_G,
        components=(
            RingComponent(1.0 / 3.0, 2.0 / 3.0, "pi", "inner pi pair"),
            RingComponent(1.0, 1.0, "sigma", "middle sigma pair"),
            RingComponent(5.0 / 3.0, 1.0 / 3.0, "sigma", "outer sigma pair"),
        ),
        dry_pi_strength=0.0,
    ),
}
