"""Composable state-transform and measurement architecture for QMW v4."""

from .core import (
    MeasurementProtocol,
    MeasurementRecord,
    SamplingMode,
    SamplingPolicy,
    SamplingResolution,
    StateTransform,
    UnitaryOperator,
    validate_density_matrix,
    validate_unitary,
)
from .experiment import (
    ObservableComparison,
    RepresentationExperiment,
    RepresentationExperimentResult,
    density_from_preset,
    save_experiment_result,
)
from .protocols import ClassicalShadowTomography, FullPauliTomography
from .transforms import (
    EpistropheBasis,
    FloquetOperator,
    GraphLaplacianBasis,
    GroverAmplifiedBasis,
    HadamardOperator,
    HamiltonianBasisTracker,
    HamiltonianEigenbasis,
    IsingHamiltonianSpec,
    IdentityOperator,
    QFTOperator,
    complete_graph_adjacency,
    cycle_graph_adjacency,
    path_graph_adjacency,
    transverse_ising_hamiltonian,
)
from .registry import (
    DEFAULT_TRANSFORMS,
    TransformRegistration,
    TransformRegistry,
    build_default_registry,
)

__all__ = [
    "DEFAULT_TRANSFORMS",
    "ClassicalShadowTomography",
    "EpistropheBasis",
    "FloquetOperator",
    "FullPauliTomography",
    "GraphLaplacianBasis",
    "GroverAmplifiedBasis",
    "HadamardOperator",
    "HamiltonianBasisTracker",
    "HamiltonianEigenbasis",
    "IdentityOperator",
    "IsingHamiltonianSpec",
    "MeasurementProtocol",
    "MeasurementRecord",
    "ObservableComparison",
    "QFTOperator",
    "RepresentationExperiment",
    "RepresentationExperimentResult",
    "SamplingMode",
    "SamplingPolicy",
    "SamplingResolution",
    "StateTransform",
    "TransformRegistration",
    "TransformRegistry",
    "UnitaryOperator",
    "build_default_registry",
    "complete_graph_adjacency",
    "cycle_graph_adjacency",
    "density_from_preset",
    "path_graph_adjacency",
    "save_experiment_result",
    "transverse_ising_hamiltonian",
    "validate_density_matrix",
    "validate_unitary",
]
