{
  "patcher": {
    "fileversion": 1,
    "appversion": {"major":8,"minor":0,"revision":0,"architecture":"x64","modernui":1},
    "classnamespace": "box",
    "rect": [120.0,120.0,1180.0,700.0],
    "gridsize": [15.0,15.0],
    "boxes": [
      {"box":{"id":"in1","maxclass":"inlet","index":1,"comment":"qubit 0 audio","numinlets":0,"numoutlets":1,"outlettype":["signal"],"patching_rect":[40.0,40.0,30.0,30.0]}},
      {"box":{"id":"in2","maxclass":"inlet","index":2,"comment":"qubit 1 audio","numinlets":0,"numoutlets":1,"outlettype":["signal"],"patching_rect":[90.0,40.0,30.0,30.0]}},
      {"box":{"id":"in3","maxclass":"inlet","index":3,"comment":"qubit 2 audio","numinlets":0,"numoutlets":1,"outlettype":["signal"],"patching_rect":[140.0,40.0,30.0,30.0]}},
      {"box":{"id":"in4","maxclass":"inlet","index":4,"comment":"qubit 3 audio","numinlets":0,"numoutlets":1,"outlettype":["signal"],"patching_rect":[190.0,40.0,30.0,30.0]}},
      {"box":{"id":"global_l","maxclass":"inlet","index":5,"comment":"global/convolution left","numinlets":0,"numoutlets":1,"outlettype":["signal"],"patching_rect":[250.0,40.0,30.0,30.0]}},
      {"box":{"id":"global_r","maxclass":"inlet","index":6,"comment":"global/convolution right","numinlets":0,"numoutlets":1,"outlettype":["signal"],"patching_rect":[300.0,40.0,30.0,30.0]}},
      {"box":{"id":"ctrl1","maxclass":"inlet","index":7,"comment":"qubit 0 Bloch XYZ","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[370.0,40.0,30.0,30.0]}},
      {"box":{"id":"ctrl2","maxclass":"inlet","index":8,"comment":"qubit 1 Bloch XYZ","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[420.0,40.0,30.0,30.0]}},
      {"box":{"id":"ctrl3","maxclass":"inlet","index":9,"comment":"qubit 2 Bloch XYZ","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[470.0,40.0,30.0,30.0]}},
      {"box":{"id":"ctrl4","maxclass":"inlet","index":10,"comment":"qubit 3 Bloch XYZ","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[520.0,40.0,30.0,30.0]}},
      {"box":{"id":"rate_in","maxclass":"inlet","index":11,"comment":"Spat update interval (ms)","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[580.0,40.0,30.0,30.0]}},
      {"box":{"id":"open_in","maxclass":"inlet","index":12,"comment":"open Spat5 window","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[1030.0,40.0,30.0,30.0]}},
      {"box":{"id":"title","maxclass":"comment","text":"Six sources → Spat5 third-order 3D Ambisonics (16ch ACN/SN3D)","patching_rect":[370.0,15.0,580.0,20.0]}},
      {"box":{"id":"c1","maxclass":"newobj","text":"qmw_qubit_spat_control /source/1/aed /source/1/aperture /source/1/yaw","patching_rect":[370.0,85.0,430.0,22.0]}},
      {"box":{"id":"c2","maxclass":"newobj","text":"qmw_qubit_spat_control /source/2/aed /source/2/aperture /source/2/yaw","patching_rect":[370.0,120.0,430.0,22.0]}},
      {"box":{"id":"c3","maxclass":"newobj","text":"qmw_qubit_spat_control /source/3/aed /source/3/aperture /source/3/yaw","patching_rect":[370.0,155.0,430.0,22.0]}},
      {"box":{"id":"c4","maxclass":"newobj","text":"qmw_qubit_spat_control /source/4/aed /source/4/aperture /source/4/yaw","patching_rect":[370.0,190.0,430.0,22.0]}},
      {"box":{"id":"oper","maxclass":"newobj","text":"spat5.oper @initwith \"/source/number 6, /source/1/label q0, /source/2/label q1, /source/3/label q2, /source/4/label q3, /source/5/label global-L, /source/6/label global-R, /source/5/aed 45 0 1, /source/6/aed -45 0 1, /source/5/aperture 100, /source/6/aperture 100, /source/*/aperture/visible 1, /source/*/constraint/circular 0\"","patching_rect":[370.0,245.0,760.0,55.0]}},
      {"box":{"id":"renderer","maxclass":"newobj","text":"spat5.spat~ @inputs 6 @internals 8 @outputs 16 @rooms 1 @initwith \"/panning/type hoa3d, /norm SN3D\"","patching_rect":[370.0,335.0,700.0,22.0]}},
      {"box":{"id":"loadbang","maxclass":"newobj","text":"loadbang","patching_rect":[815.0,85.0,60.0,22.0]}},
      {"box":{"id":"delay","maxclass":"newobj","text":"delay 750","patching_rect":[885.0,85.0,70.0,22.0]}},
      {"box":{"id":"open","maxclass":"message","text":"/window/open","patching_rect":[885.0,120.0,95.0,22.0]}},
      {"box":{"id":"out1","maxclass":"outlet","index":1,"comment":"ACN 0: W / Y00","numinlets":1,"numoutlets":0,"patching_rect":[370.0,430.0,30.0,30.0]}},
      {"box":{"id":"out2","maxclass":"outlet","index":2,"comment":"ACN 1: Y / Y1-1","numinlets":1,"numoutlets":0,"patching_rect":[415.0,430.0,30.0,30.0]}},
      {"box":{"id":"out3","maxclass":"outlet","index":3,"comment":"ACN 2: Z / Y10","numinlets":1,"numoutlets":0,"patching_rect":[460.0,430.0,30.0,30.0]}},
      {"box":{"id":"out4","maxclass":"outlet","index":4,"comment":"ACN 3: X / Y11","numinlets":1,"numoutlets":0,"patching_rect":[505.0,430.0,30.0,30.0]}},
      {"box":{"id":"out5","maxclass":"outlet","index":5,"comment":"ACN 4: V / Y2-2","numinlets":1,"numoutlets":0,"patching_rect":[550.0,430.0,30.0,30.0]}},
      {"box":{"id":"out6","maxclass":"outlet","index":6,"comment":"ACN 5: T / Y2-1","numinlets":1,"numoutlets":0,"patching_rect":[595.0,430.0,30.0,30.0]}},
      {"box":{"id":"out7","maxclass":"outlet","index":7,"comment":"ACN 6: R / Y20","numinlets":1,"numoutlets":0,"patching_rect":[640.0,430.0,30.0,30.0]}},
      {"box":{"id":"out8","maxclass":"outlet","index":8,"comment":"ACN 7: S / Y21","numinlets":1,"numoutlets":0,"patching_rect":[685.0,430.0,30.0,30.0]}},
      {"box":{"id":"out9","maxclass":"outlet","index":9,"comment":"ACN 8: U / Y22","numinlets":1,"numoutlets":0,"patching_rect":[730.0,430.0,30.0,30.0]}},
      {"box":{"id":"out10","maxclass":"outlet","index":10,"comment":"ACN 9: Q / Y3-3","numinlets":1,"numoutlets":0,"patching_rect":[775.0,430.0,30.0,30.0]}},
      {"box":{"id":"out11","maxclass":"outlet","index":11,"comment":"ACN 10: O / Y3-2","numinlets":1,"numoutlets":0,"patching_rect":[820.0,430.0,30.0,30.0]}},
      {"box":{"id":"out12","maxclass":"outlet","index":12,"comment":"ACN 11: M / Y3-1","numinlets":1,"numoutlets":0,"patching_rect":[865.0,430.0,30.0,30.0]}},
      {"box":{"id":"out13","maxclass":"outlet","index":13,"comment":"ACN 12: K / Y30","numinlets":1,"numoutlets":0,"patching_rect":[910.0,430.0,30.0,30.0]}},
      {"box":{"id":"out14","maxclass":"outlet","index":14,"comment":"ACN 13: L / Y31","numinlets":1,"numoutlets":0,"patching_rect":[955.0,430.0,30.0,30.0]}},
      {"box":{"id":"out15","maxclass":"outlet","index":15,"comment":"ACN 14: N / Y32","numinlets":1,"numoutlets":0,"patching_rect":[1000.0,430.0,30.0,30.0]}},
      {"box":{"id":"out16","maxclass":"outlet","index":16,"comment":"ACN 15: P / Y33","numinlets":1,"numoutlets":0,"patching_rect":[1045.0,430.0,30.0,30.0]}}
    ],
    "lines": [
      {"patchline":{"source":["ctrl1",0],"destination":["c1",0]}},
      {"patchline":{"source":["ctrl2",0],"destination":["c2",0]}},
      {"patchline":{"source":["ctrl3",0],"destination":["c3",0]}},
      {"patchline":{"source":["ctrl4",0],"destination":["c4",0]}},
      {"patchline":{"source":["rate_in",0],"destination":["c1",1]}},
      {"patchline":{"source":["rate_in",0],"destination":["c2",1]}},
      {"patchline":{"source":["rate_in",0],"destination":["c3",1]}},
      {"patchline":{"source":["rate_in",0],"destination":["c4",1]}},
      {"patchline":{"source":["c1",0],"destination":["oper",0]}},
      {"patchline":{"source":["c2",0],"destination":["oper",0]}},
      {"patchline":{"source":["c3",0],"destination":["oper",0]}},
      {"patchline":{"source":["c4",0],"destination":["oper",0]}},
      {"patchline":{"source":["oper",0],"destination":["renderer",0]}},
      {"patchline":{"source":["in1",0],"destination":["renderer",0]}},
      {"patchline":{"source":["in2",0],"destination":["renderer",1]}},
      {"patchline":{"source":["in3",0],"destination":["renderer",2]}},
      {"patchline":{"source":["in4",0],"destination":["renderer",3]}},
      {"patchline":{"source":["global_l",0],"destination":["renderer",4]}},
      {"patchline":{"source":["global_r",0],"destination":["renderer",5]}},
      {"patchline":{"source":["loadbang",0],"destination":["delay",0]}},
      {"patchline":{"source":["delay",0],"destination":["open",0]}},
      {"patchline":{"source":["open_in",0],"destination":["open",0]}},
      {"patchline":{"source":["open",0],"destination":["oper",0]}},
      {"patchline":{"source":["renderer",0],"destination":["out1",0]}},
      {"patchline":{"source":["renderer",1],"destination":["out2",0]}},
      {"patchline":{"source":["renderer",2],"destination":["out3",0]}},
      {"patchline":{"source":["renderer",3],"destination":["out4",0]}},
      {"patchline":{"source":["renderer",4],"destination":["out5",0]}},
      {"patchline":{"source":["renderer",5],"destination":["out6",0]}},
      {"patchline":{"source":["renderer",6],"destination":["out7",0]}},
      {"patchline":{"source":["renderer",7],"destination":["out8",0]}},
      {"patchline":{"source":["renderer",8],"destination":["out9",0]}},
      {"patchline":{"source":["renderer",9],"destination":["out10",0]}},
      {"patchline":{"source":["renderer",10],"destination":["out11",0]}},
      {"patchline":{"source":["renderer",11],"destination":["out12",0]}},
      {"patchline":{"source":["renderer",12],"destination":["out13",0]}},
      {"patchline":{"source":["renderer",13],"destination":["out14",0]}},
      {"patchline":{"source":["renderer",14],"destination":["out15",0]}},
      {"patchline":{"source":["renderer",15],"destination":["out16",0]}}
    ],
    "autosave": 0
  }
}
