{
  "patcher": {
    "fileversion": 1,
    "appversion": {"major":9,"minor":0,"revision":5,"architecture":"x64","modernui":1},
    "classnamespace": "box",
    "rect": [140.0,140.0,880.0,520.0],
    "gridsize": [15.0,15.0],
    "boxes": [
      {"box":{"id":"title","maxclass":"comment","text":"Bloch XYZ inlet → 180 ms vector slew → Spat AED, aperture and yaw","patching_rect":[30.0,20.0,600.0,20.0]}},
      {"box":{"id":"receive","maxclass":"inlet","index":1,"comment":"Bloch XYZ list","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[30.0,55.0,30.0,30.0]}},
      {"box":{"id":"grain_in","maxclass":"inlet","index":2,"comment":"Spat update interval (ms)","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[275.0,55.0,30.0,30.0]}},
      {"box":{"id":"trigger","maxclass":"newobj","text":"unpack f f f","patching_rect":[30.0,95.0,85.0,22.0]}},
      {"box":{"id":"ramp_x","maxclass":"message","text":"$1 180.","patching_rect":[30.0,130.0,65.0,22.0]}},
      {"box":{"id":"ramp_y","maxclass":"message","text":"$1 180.","patching_rect":[110.0,130.0,65.0,22.0]}},
      {"box":{"id":"ramp_z","maxclass":"message","text":"$1 180.","patching_rect":[190.0,130.0,65.0,22.0]}},
      {"box":{"id":"slew_x","maxclass":"newobj","text":"line 0. 20","patching_rect":[30.0,165.0,68.0,22.0]}},
      {"box":{"id":"slew_y","maxclass":"newobj","text":"line 0. 20","patching_rect":[110.0,165.0,68.0,22.0]}},
      {"box":{"id":"slew_z","maxclass":"newobj","text":"line 0. 20","patching_rect":[190.0,165.0,68.0,22.0]}},
      {"box":{"id":"vector","maxclass":"newobj","text":"pak f f f","patching_rect":[285.0,165.0,70.0,22.0]}},
      {"box":{"id":"vector_trigger","maxclass":"newobj","text":"t l l l l","patching_rect":[375.0,165.0,65.0,22.0]}},
      {"box":{"id":"radius","maxclass":"newobj","text":"expr min(1.,sqrt($f1*$f1+$f2*$f2+$f3*$f3))","patching_rect":[30.0,210.0,285.0,22.0]}},
      {"box":{"id":"distance","maxclass":"newobj","text":"expr 1.+1.5*(1.-$f1)","patching_rect":[30.0,245.0,145.0,22.0]}},
      {"box":{"id":"aperture","maxclass":"newobj","text":"expr 20.+140.*(1.-$f1)","patching_rect":[185.0,245.0,170.0,22.0]}},
      {"box":{"id":"elevation","maxclass":"newobj","text":"expr 90.-acos(max(-1.,min(1.,$f3/max(sqrt($f1*$f1+$f2*$f2+$f3*$f3),0.000001))))*57.2957795","patching_rect":[330.0,210.0,520.0,22.0]}},
      {"box":{"id":"azimuth","maxclass":"newobj","text":"expr atan2($f2,$f1)*57.2957795","patching_rect":[365.0,245.0,215.0,22.0]}},
      {"box":{"id":"aed","maxclass":"newobj","text":"pack f f f","patching_rect":[365.0,285.0,78.0,22.0]}},
      {"box":{"id":"paed","maxclass":"newobj","text":"prepend #1","patching_rect":[365.0,325.0,175.0,22.0]}},
      {"box":{"id":"paperture","maxclass":"newobj","text":"prepend #2","patching_rect":[30.0,325.0,200.0,22.0]}},
      {"box":{"id":"pyaw","maxclass":"newobj","text":"prepend #3","patching_rect":[550.0,325.0,175.0,22.0]}},
      {"box":{"id":"out","maxclass":"outlet","index":1,"comment":"Spat5 OSC messages","numinlets":1,"numoutlets":0,"patching_rect":[365.0,400.0,30.0,30.0]}}
    ],
    "lines": [
      {"patchline":{"source":["receive",0],"destination":["trigger",0]}},
      {"patchline":{"source":["trigger",0],"destination":["ramp_x",0]}},
      {"patchline":{"source":["trigger",1],"destination":["ramp_y",0]}},
      {"patchline":{"source":["trigger",2],"destination":["ramp_z",0]}},
      {"patchline":{"source":["ramp_x",0],"destination":["slew_x",0]}},
      {"patchline":{"source":["ramp_y",0],"destination":["slew_y",0]}},
      {"patchline":{"source":["ramp_z",0],"destination":["slew_z",0]}},
      {"patchline":{"source":["grain_in",0],"destination":["slew_x",2]}},
      {"patchline":{"source":["grain_in",0],"destination":["slew_y",2]}},
      {"patchline":{"source":["grain_in",0],"destination":["slew_z",2]}},
      {"patchline":{"source":["slew_x",0],"destination":["vector",0]}},
      {"patchline":{"source":["slew_y",0],"destination":["vector",1]}},
      {"patchline":{"source":["slew_z",0],"destination":["vector",2]}},
      {"patchline":{"source":["vector",0],"destination":["vector_trigger",0]}},
      {"patchline":{"source":["vector_trigger",3],"destination":["radius",0]}},
      {"patchline":{"source":["vector_trigger",2],"destination":["elevation",0]}},
      {"patchline":{"source":["vector_trigger",0],"destination":["azimuth",0]}},
      {"patchline":{"source":["radius",0],"destination":["distance",0]}},
      {"patchline":{"source":["radius",0],"destination":["aperture",0]}},
      {"patchline":{"source":["distance",0],"destination":["aed",2]}},
      {"patchline":{"source":["elevation",0],"destination":["aed",1]}},
      {"patchline":{"source":["azimuth",0],"destination":["aed",0]}},
      {"patchline":{"source":["aed",0],"destination":["paed",0]}},
      {"patchline":{"source":["aperture",0],"destination":["paperture",0]}},
      {"patchline":{"source":["azimuth",0],"destination":["pyaw",0]}},
      {"patchline":{"source":["paed",0],"destination":["out",0]}},
      {"patchline":{"source":["paperture",0],"destination":["out",0]}},
      {"patchline":{"source":["pyaw",0],"destination":["out",0]}}
    ],
    "autosave": 0
  }
}
