{
  "patcher": {
    "fileversion": 1,
    "appversion": {
      "major": 9,
      "minor": 0,
      "revision": 5,
      "architecture": "x64",
      "modernui": 1
    },
    "classnamespace": "box",
    "rect": [120.0, 120.0, 1120.0, 720.0],
    "gridsize": [15.0, 15.0],
    "boxes": [
      {"box":{"id":"in_l","maxclass":"inlet","index":1,"comment":"stereo input left","numinlets":0,"numoutlets":1,"outlettype":["signal"],"patching_rect":[40.0,40.0,30.0,30.0]}},
      {"box":{"id":"in_r","maxclass":"inlet","index":2,"comment":"stereo input right","numinlets":0,"numoutlets":1,"outlettype":["signal"],"patching_rect":[100.0,40.0,30.0,30.0]}},
      {"box":{"id":"in_x","maxclass":"inlet","index":3,"comment":"Bloch X","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[250.0,40.0,30.0,30.0]}},
      {"box":{"id":"in_y","maxclass":"inlet","index":4,"comment":"Bloch Y","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[310.0,40.0,30.0,30.0]}},
      {"box":{"id":"in_z","maxclass":"inlet","index":5,"comment":"Bloch Z","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[370.0,40.0,30.0,30.0]}},
      {"box":{"id":"in_amount","maxclass":"inlet","index":6,"comment":"spatial amount 0..1","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[900.0,40.0,30.0,30.0]}},
      {"box":{"id":"in_purity","maxclass":"inlet","index":7,"comment":"normalized purity","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[740.0,40.0,30.0,30.0]}},
      {"box":{"id":"in_yaw","maxclass":"inlet","index":8,"comment":"Bohmian local phase radians","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[800.0,40.0,30.0,30.0]}},
      {"box":{"id":"in_aperture_trim","maxclass":"inlet","index":9,"comment":"aperture trim degrees","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[680.0,40.0,30.0,30.0]}},
      {"box":{"id":"in_yaw_trim","maxclass":"inlet","index":10,"comment":"yaw trim degrees","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[860.0,40.0,30.0,30.0]}},
      {"box":{"id":"title","maxclass":"comment","text":"Global four-qubit field → one Spat5 AED source with equal-power bypass","patching_rect":[250.0,15.0,560.0,20.0]}},
      {"box":{"id":"vector","maxclass":"newobj","text":"pak f f f","patching_rect":[250.0,95.0,70.0,22.0]}},
      {"box":{"id":"vector_trigger","maxclass":"newobj","text":"t l l l","patching_rect":[250.0,130.0,55.0,22.0]}},
      {"box":{"id":"azimuth","maxclass":"newobj","text":"expr atan2($f2,$f1)*57.2957795","patching_rect":[250.0,185.0,215.0,22.0]}},
      {"box":{"id":"elevation","maxclass":"newobj","text":"expr 90.-acos(max(-1.,min(1.,$f3/max(sqrt($f1*$f1+$f2*$f2+$f3*$f3),0.000001))))*57.2957795","patching_rect":[475.0,185.0,570.0,22.0]}},
      {"box":{"id":"distance","maxclass":"newobj","text":"expr 1.+1.5*(1.-min(1.,sqrt($f1*$f1+$f2*$f2+$f3*$f3)))","patching_rect":[475.0,150.0,360.0,22.0]}},
      {"box":{"id":"aed","maxclass":"newobj","text":"pack f f f","patching_rect":[250.0,230.0,78.0,22.0]}},
      {"box":{"id":"aed_trigger","maxclass":"newobj","text":"t l","patching_rect":[250.0,265.0,35.0,22.0]}},
      {"box":{"id":"source_1","maxclass":"newobj","text":"prepend /source/1/aed","patching_rect":[250.0,300.0,165.0,22.0]}},
      {"box":{"id":"purity_clip","maxclass":"newobj","text":"clip 0. 1.","patching_rect":[610.0,95.0,68.0,22.0]}},
      {"box":{"id":"aperture_base","maxclass":"newobj","text":"expr 20.+140.*(1.-$f1)","patching_rect":[610.0,130.0,170.0,22.0]}},
      {"box":{"id":"aperture_pak","maxclass":"newobj","text":"pak f f","patching_rect":[610.0,165.0,60.0,22.0]}},
      {"box":{"id":"aperture","maxclass":"newobj","text":"expr min(180.,max(0.,$f1+$f2))","patching_rect":[680.0,165.0,205.0,22.0]}},
      {"box":{"id":"aperture_trigger","maxclass":"newobj","text":"t f f","patching_rect":[610.0,200.0,42.0,22.0]}},
      {"box":{"id":"aperture_1","maxclass":"newobj","text":"prepend /source/1/aperture","patching_rect":[610.0,230.0,190.0,22.0]}},
      {"box":{"id":"yaw_degrees","maxclass":"newobj","text":"* 57.2957795","patching_rect":[800.0,95.0,92.0,22.0]}},
      {"box":{"id":"yaw_pak","maxclass":"newobj","text":"pak f f","patching_rect":[800.0,130.0,60.0,22.0]}},
      {"box":{"id":"yaw_wrapped","maxclass":"newobj","text":"expr atan2(sin(($f1+$f2)*0.01745329252),cos(($f1+$f2)*0.01745329252))*57.2957795","patching_rect":[870.0,130.0,235.0,42.0]}},
      {"box":{"id":"yaw_trigger","maxclass":"newobj","text":"t f f","patching_rect":[805.0,200.0,42.0,22.0]}},
      {"box":{"id":"yaw_1","maxclass":"newobj","text":"prepend /source/1/yaw","patching_rect":[610.0,265.0,165.0,22.0]}},
      {"box":{"id":"oper","maxclass":"newobj","text":"spat5.oper @initwith \"/source/number 1, /source/1/aed 0. 0. 1., /source/1/aperture 20., /source/1/aperture/visible 1, /source/1/orientation/visible 1, /source/1/constraint/circular 0\"","patching_rect":[250.0,350.0,820.0,22.0]}},
      {"box":{"id":"renderer","maxclass":"newobj","text":"spat5.spat~ @inputs 1 @internals 8 @outputs 2 @rooms 1 @initwith \"/panning/type binaural\"","patching_rect":[250.0,410.0,610.0,22.0]}},
      {"box":{"id":"mono_sum","maxclass":"newobj","text":"+~","patching_rect":[40.0,365.0,35.0,22.0]}},
      {"box":{"id":"mono_gain","maxclass":"newobj","text":"*~ 0.5","patching_rect":[85.0,365.0,52.0,22.0]}},
      {"box":{"id":"amount_default","maxclass":"newobj","text":"loadmess 1.","patching_rect":[940.0,40.0,82.0,22.0]}},
      {"box":{"id":"amount_clip","maxclass":"newobj","text":"clip 0. 1.","patching_rect":[900.0,95.0,68.0,22.0]}},
      {"box":{"id":"amount_trigger","maxclass":"newobj","text":"t f f","patching_rect":[900.0,130.0,42.0,22.0]}},
      {"box":{"id":"wet_sqrt","maxclass":"newobj","text":"expr sqrt($f1)","patching_rect":[850.0,165.0,92.0,22.0]}},
      {"box":{"id":"dry_sqrt","maxclass":"newobj","text":"expr sqrt(max(0.,1.-$f1))","patching_rect":[950.0,165.0,165.0,22.0]}},
      {"box":{"id":"wet_pack","maxclass":"newobj","text":"pack 0. 80","patching_rect":[850.0,200.0,72.0,22.0]}},
      {"box":{"id":"dry_pack","maxclass":"newobj","text":"pack 0. 80","patching_rect":[950.0,200.0,72.0,22.0]}},
      {"box":{"id":"wet_line","maxclass":"newobj","text":"line~","patching_rect":[850.0,235.0,40.0,22.0]}},
      {"box":{"id":"dry_line","maxclass":"newobj","text":"line~","patching_rect":[950.0,235.0,40.0,22.0]}},
      {"box":{"id":"spat_l","maxclass":"newobj","text":"*~","patching_rect":[250.0,465.0,35.0,22.0]}},
      {"box":{"id":"spat_r","maxclass":"newobj","text":"*~","patching_rect":[430.0,465.0,35.0,22.0]}},
      {"box":{"id":"dry_l","maxclass":"newobj","text":"*~","patching_rect":[40.0,465.0,35.0,22.0]}},
      {"box":{"id":"dry_r","maxclass":"newobj","text":"*~","patching_rect":[100.0,465.0,35.0,22.0]}},
      {"box":{"id":"sum_l","maxclass":"newobj","text":"+~","patching_rect":[250.0,515.0,35.0,22.0]}},
      {"box":{"id":"sum_r","maxclass":"newobj","text":"+~","patching_rect":[430.0,515.0,35.0,22.0]}},
      {"box":{"id":"out_l","maxclass":"outlet","index":1,"comment":"binaural left","numinlets":1,"numoutlets":0,"patching_rect":[250.0,580.0,30.0,30.0]}},
      {"box":{"id":"out_r","maxclass":"outlet","index":2,"comment":"binaural right","numinlets":1,"numoutlets":0,"patching_rect":[430.0,580.0,30.0,30.0]}},
      {"box":{"id":"out_az","maxclass":"outlet","index":3,"comment":"azimuth degrees","numinlets":1,"numoutlets":0,"patching_rect":[610.0,580.0,30.0,30.0]}},
      {"box":{"id":"out_el","maxclass":"outlet","index":4,"comment":"elevation degrees","numinlets":1,"numoutlets":0,"patching_rect":[680.0,580.0,30.0,30.0]}},
      {"box":{"id":"out_dist","maxclass":"outlet","index":5,"comment":"distance metres","numinlets":1,"numoutlets":0,"patching_rect":[750.0,580.0,30.0,30.0]}},
      {"box":{"id":"out_aperture","maxclass":"outlet","index":6,"comment":"aperture degrees","numinlets":1,"numoutlets":0,"patching_rect":[820.0,580.0,30.0,30.0]}},
      {"box":{"id":"out_yaw","maxclass":"outlet","index":7,"comment":"yaw degrees","numinlets":1,"numoutlets":0,"patching_rect":[890.0,580.0,30.0,30.0]}}
    ],
    "lines": [
      {"patchline":{"source":["in_x",0],"destination":["vector",0]}},
      {"patchline":{"source":["in_y",0],"destination":["vector",1]}},
      {"patchline":{"source":["in_z",0],"destination":["vector",2]}},
      {"patchline":{"source":["vector",0],"destination":["vector_trigger",0]}},
      {"patchline":{"source":["vector_trigger",2],"destination":["distance",0]}},
      {"patchline":{"source":["vector_trigger",1],"destination":["elevation",0]}},
      {"patchline":{"source":["vector_trigger",0],"destination":["azimuth",0]}},
      {"patchline":{"source":["distance",0],"destination":["aed",2]}},
      {"patchline":{"source":["elevation",0],"destination":["aed",1]}},
      {"patchline":{"source":["azimuth",0],"destination":["aed",0]}},
      {"patchline":{"source":["aed",0],"destination":["aed_trigger",0]}},
      {"patchline":{"source":["aed_trigger",0],"destination":["source_1",0]}},
      {"patchline":{"source":["source_1",0],"destination":["oper",0]}},
      {"patchline":{"source":["in_purity",0],"destination":["purity_clip",0]}},
      {"patchline":{"source":["purity_clip",0],"destination":["aperture_base",0]}},
      {"patchline":{"source":["aperture_base",0],"destination":["aperture_pak",0]}},
      {"patchline":{"source":["in_aperture_trim",0],"destination":["aperture_pak",1]}},
      {"patchline":{"source":["aperture_pak",0],"destination":["aperture",0]}},
      {"patchline":{"source":["aperture",0],"destination":["aperture_trigger",0]}},
      {"patchline":{"source":["aperture_trigger",0],"destination":["aperture_1",0]}},
      {"patchline":{"source":["aperture_trigger",1],"destination":["out_aperture",0]}},
      {"patchline":{"source":["aperture_1",0],"destination":["oper",0]}},
      {"patchline":{"source":["in_yaw",0],"destination":["yaw_degrees",0]}},
      {"patchline":{"source":["yaw_degrees",0],"destination":["yaw_pak",0]}},
      {"patchline":{"source":["in_yaw_trim",0],"destination":["yaw_pak",1]}},
      {"patchline":{"source":["yaw_pak",0],"destination":["yaw_wrapped",0]}},
      {"patchline":{"source":["yaw_wrapped",0],"destination":["yaw_trigger",0]}},
      {"patchline":{"source":["yaw_trigger",0],"destination":["yaw_1",0]}},
      {"patchline":{"source":["yaw_trigger",1],"destination":["out_yaw",0]}},
      {"patchline":{"source":["yaw_1",0],"destination":["oper",0]}},
      {"patchline":{"source":["oper",0],"destination":["renderer",0]}},
      {"patchline":{"source":["in_l",0],"destination":["mono_sum",0]}},
      {"patchline":{"source":["in_r",0],"destination":["mono_sum",1]}},
      {"patchline":{"source":["mono_sum",0],"destination":["mono_gain",0]}},
      {"patchline":{"source":["mono_gain",0],"destination":["renderer",0]}},
      {"patchline":{"source":["in_amount",0],"destination":["amount_clip",0]}},
      {"patchline":{"source":["amount_default",0],"destination":["amount_clip",0]}},
      {"patchline":{"source":["amount_clip",0],"destination":["amount_trigger",0]}},
      {"patchline":{"source":["amount_trigger",0],"destination":["wet_sqrt",0]}},
      {"patchline":{"source":["amount_trigger",1],"destination":["dry_sqrt",0]}},
      {"patchline":{"source":["wet_sqrt",0],"destination":["wet_pack",0]}},
      {"patchline":{"source":["dry_sqrt",0],"destination":["dry_pack",0]}},
      {"patchline":{"source":["wet_pack",0],"destination":["wet_line",0]}},
      {"patchline":{"source":["dry_pack",0],"destination":["dry_line",0]}},
      {"patchline":{"source":["renderer",0],"destination":["spat_l",0]}},
      {"patchline":{"source":["renderer",1],"destination":["spat_r",0]}},
      {"patchline":{"source":["wet_line",0],"destination":["spat_l",1]}},
      {"patchline":{"source":["wet_line",0],"destination":["spat_r",1]}},
      {"patchline":{"source":["in_l",0],"destination":["dry_l",0]}},
      {"patchline":{"source":["in_r",0],"destination":["dry_r",0]}},
      {"patchline":{"source":["dry_line",0],"destination":["dry_l",1]}},
      {"patchline":{"source":["dry_line",0],"destination":["dry_r",1]}},
      {"patchline":{"source":["spat_l",0],"destination":["sum_l",0]}},
      {"patchline":{"source":["dry_l",0],"destination":["sum_l",1]}},
      {"patchline":{"source":["spat_r",0],"destination":["sum_r",0]}},
      {"patchline":{"source":["dry_r",0],"destination":["sum_r",1]}},
      {"patchline":{"source":["sum_l",0],"destination":["out_l",0]}},
      {"patchline":{"source":["sum_r",0],"destination":["out_r",0]}},
      {"patchline":{"source":["azimuth",0],"destination":["out_az",0]}},
      {"patchline":{"source":["elevation",0],"destination":["out_el",0]}},
      {"patchline":{"source":["distance",0],"destination":["out_dist",0]}}
    ],
    "autosave": 0
  }
}
