(() => {
  "use strict";
  const CONTRACT="qmw_metric.shader_frame.v1", MAGIC=[81,77,87,70,1,0,0,0];
  const product=a=>a.reduce((x,y)=>x*y,1);
  function nest(values,shape){if(shape.length===1)return Array.from(values);const step=product(shape.slice(1)),out=[];for(let i=0;i<shape[0];i++)out.push(nest(values.subarray(i*step,(i+1)*step),shape.slice(1)));return out}
  async function inflate(bytes){if(!window.DecompressionStream)throw new Error("This browser lacks DecompressionStream for qmw binary frames");const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream("deflate"));return new Uint8Array(await new Response(stream).arrayBuffer())}
  async function decodeBinary(buffer){const bytes=new Uint8Array(buffer);if(bytes.length<16||MAGIC.some((v,i)=>bytes[i]!==v))throw new Error("invalid QMWF envelope");const view=new DataView(buffer),headerSize=view.getUint32(8,true),bodySize=view.getUint32(12,true);if(bytes.length!==16+headerSize+bodySize)throw new Error("truncated QMWF envelope");const manifest=JSON.parse(new TextDecoder().decode(bytes.slice(16,16+headerSize)));let raw=bytes.slice(16+headerSize);if(manifest.encoding==="f32le+zlib")raw=await inflate(raw);else if(manifest.encoding!=="f32le")throw new Error("unsupported QMWF encoding");if(raw.byteLength!==manifest.raw_nbytes)throw new Error("QMWF length mismatch");const arrays={};for(const[name,spec]of Object.entries(manifest.arrays)){const copy=raw.slice(spec.offset,spec.offset+spec.nbytes),values=new Float32Array(copy.buffer,copy.byteOffset,spec.nbytes/4);arrays[name]=nest(values,spec.shape)}return{contract:manifest.contract,revision:manifest.revision,source_revision:manifest.source_revision,time:manifest.time,model_label:manifest.model_label,arrays}}
  function validate(p){if(p.contract!==CONTRACT)throw new Error("unsupported QMW live contract");if(!Number.isInteger(p.revision)||p.revision<0||!Number.isInteger(p.source_revision)||p.source_revision<0)throw new Error("invalid QMW revisions");if(!p.arrays||!Array.isArray(p.arrays.density)||!Array.isArray(p.arrays.trajectory_positions))throw new Error("incomplete QMW live arrays")}
  class QMWLiveFrameClient{
    constructor(url,onFrame,onStatus=()=>{}){this.url=url;this.onFrame=onFrame;this.onStatus=onStatus;this.socket=null;this.timer=null;this.closed=false;this.backoff=250;this.lastRevision=-1;this.lastSourceRevision=-1}
    connect(){this.closed=false;this.onStatus("connecting");const ws=new WebSocket(this.url);this.socket=ws;ws.binaryType="arraybuffer";ws.onopen=()=>{this.backoff=250;this.onStatus("live")};ws.onmessage=async e=>{try{if(typeof e.data==="string"){const msg=JSON.parse(e.data);if(msg.type==="hello")return;await this.accept(msg)}else await this.accept(await decodeBinary(e.data))}catch(error){this.onStatus(`rejected: ${error.message}`)}};ws.onerror=()=>ws.close();ws.onclose=()=>{if(this.closed)return;this.onStatus("reconnecting");this.timer=setTimeout(()=>this.connect(),this.backoff);this.backoff=Math.min(5000,this.backoff*2)}}
    async accept(payload){validate(payload);if(payload.revision<=this.lastRevision||payload.source_revision<this.lastSourceRevision){this.onStatus("stale frame rejected");return false}this.lastRevision=payload.revision;this.lastSourceRevision=payload.source_revision;await this.onFrame(payload);return true}
    close(){this.closed=true;clearTimeout(this.timer);this.socket?.close();this.onStatus("offline")}
  }
  window.QMWLiveFrameClient=QMWLiveFrameClient;
})();
