"""Read-only ordered Pauli-path commutator observer.

For two declared Hermitian Pauli operations this module observes
``K = -i [A, B]``.  It does not evolve a state, choose a future operation, or
send an audio/control message.  The ledger is an auditable record of the order
in which its caller supplied operations.
"""

from __future__ import annotations

from dataclasses import dataclass
import math

import numpy as np

from .pauli_basis import normalize_pauli_label, pauli_matrix
from .pauli_decompose import PauliTerm, pauli_decomposition


@dataclass(frozen=True)
class PauliPathOperation:
    """One explicitly weighted Hermitian Pauli generator ``strength * P``."""

    label: str
    strength: float = 1.0

    def __post_init__(self) -> None:
        label = normalize_pauli_label(self.label)
        if not math.isfinite(float(self.strength)):
            raise ValueError("Pauli operation strength must be finite.")
        object.__setattr__(self, "label", label)
        object.__setattr__(self, "strength", float(self.strength))

    @property
    def matrix(self) -> np.ndarray:
        return self.strength * pauli_matrix(self.label)


@dataclass(frozen=True)
class NonAbelianCommutatorFrame:
    """One revisioned, ordered observation of ``-i[A_k, A_(k+1)]``."""

    source_revision: int
    logical_time: float
    sequence_index: int
    left: PauliPathOperation
    right: PauliPathOperation
    generator: np.ndarray
    frobenius_norm: float
    normalized_hilbert_schmidt_norm: float
    generated_terms: tuple[PauliTerm, ...]
    provenance: str = "read_only_ordered_pauli_commutator_observer_v1"

    def __post_init__(self) -> None:
        if int(self.source_revision) < 0 or int(self.sequence_index) < 0:
            raise ValueError("commutator revision and sequence_index must be nonnegative.")
        if not math.isfinite(float(self.logical_time)):
            raise ValueError("commutator logical_time must be finite.")
        matrix = np.asarray(self.generator, dtype=np.complex128)
        if matrix.ndim != 2 or matrix.shape[0] != matrix.shape[1] or matrix.shape[0] < 2:
            raise ValueError("commutator generator must be a square nontrivial matrix.")
        if not np.all(np.isfinite(matrix)) or not np.allclose(matrix, matrix.conj().T, atol=1.0e-9, rtol=0.0):
            raise ValueError("-i[A, B] must be finite and Hermitian.")
        if not math.isfinite(float(self.frobenius_norm)) or self.frobenius_norm < 0.0:
            raise ValueError("commutator Frobenius norm must be finite and nonnegative.")
        if not math.isfinite(float(self.normalized_hilbert_schmidt_norm)) or self.normalized_hilbert_schmidt_norm < 0.0:
            raise ValueError("normalized commutator norm must be finite and nonnegative.")
        copied = np.array(matrix, copy=True)
        copied.flags.writeable = False
        object.__setattr__(self, "source_revision", int(self.source_revision))
        object.__setattr__(self, "logical_time", float(self.logical_time))
        object.__setattr__(self, "sequence_index", int(self.sequence_index))
        object.__setattr__(self, "generator", copied)
        object.__setattr__(self, "generated_terms", tuple(self.generated_terms))

    @property
    def is_commuting(self) -> bool:
        return math.isclose(self.normalized_hilbert_schmidt_norm, 0.0, abs_tol=1.0e-12)


def observe_ordered_pauli_commutator(
    left: PauliPathOperation,
    right: PauliPathOperation,
    *, source_revision: int, logical_time: float, sequence_index: int = 0,
    tolerance: float = 1.0e-10,
) -> NonAbelianCommutatorFrame:
    """Observe the Hermitian relation generated by one ordered Pauli pair."""

    if not isinstance(left, PauliPathOperation) or not isinstance(right, PauliPathOperation):
        raise ValueError("commutator observer requires explicit PauliPathOperation values.")
    if len(left.label) != len(right.label):
        raise ValueError("ordered Pauli operations must act on the same qubit count.")
    if not math.isfinite(float(tolerance)) or tolerance < 0.0:
        raise ValueError("commutator tolerance must be finite and nonnegative.")
    generator = -1j * (left.matrix @ right.matrix - right.matrix @ left.matrix)
    generator = np.asarray(generator, dtype=np.complex128)
    # Numerical round-off is removed symmetrically, never by discarding an
    # order-dependent imaginary contribution.
    generator = 0.5 * (generator + generator.conj().T)
    dimension = generator.shape[0]
    frobenius = float(np.linalg.norm(generator, ord="fro"))
    normalized = frobenius / math.sqrt(dimension)
    return NonAbelianCommutatorFrame(
        source_revision=source_revision, logical_time=logical_time, sequence_index=sequence_index,
        left=left, right=right, generator=generator,
        frobenius_norm=frobenius, normalized_hilbert_schmidt_norm=normalized,
        generated_terms=pauli_decomposition(generator, tolerance=tolerance),
    )


class OrderedPauliPathLedger:
    """Append-only observer ledger; it has no operation-selection policy."""

    def __init__(self) -> None:
        self._frames: list[NonAbelianCommutatorFrame] = []

    @property
    def frames(self) -> tuple[NonAbelianCommutatorFrame, ...]:
        return tuple(self._frames)

    def append(
        self, left: PauliPathOperation, right: PauliPathOperation, *,
        source_revision: int, logical_time: float,
    ) -> NonAbelianCommutatorFrame:
        """Observe and append one pair in caller-provided order."""

        if self._frames:
            previous = self._frames[-1]
            if int(source_revision) < previous.source_revision:
                raise ValueError("path ledger source_revision must not move backwards.")
            if float(logical_time) < previous.logical_time:
                raise ValueError("path ledger logical_time must not move backwards.")
        frame = observe_ordered_pauli_commutator(
            left, right, source_revision=source_revision, logical_time=logical_time,
            sequence_index=len(self._frames),
        )
        self._frames.append(frame)
        return frame


__all__ = [
    "NonAbelianCommutatorFrame", "OrderedPauliPathLedger", "PauliPathOperation",
    "observe_ordered_pauli_commutator",
]
