"""Continuous quantum monitoring and quantum-derived rhythm, version 1.

This module keeps three operations distinct:

* ``GateOp`` is a scheduled coherent transformation.
* ``MeasureOp`` is a scheduled discrete instrument that produces one outcome.
* ``MonitorOp`` opens a continuous observation interval in which jump times
  are generated by the conditional quantum dynamics.

The circuit and ZX views are lenses on the same immutable operation objects.
They do not own separate copies of musical events.  A monitored jump updates
``rho`` before observables, rhythm projection, and sound-facing excitation are
computed.

The implementation is a simulator.  Its events are not detector observations
and are never relabelled as hardware evidence.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
import csv
import hashlib
from html import escape
import json
import math
from math import comb
from pathlib import Path
from types import MappingProxyType
from typing import Callable, Literal, Mapping, Sequence, TypeAlias
import wave

import numpy as np
from numpy.typing import NDArray


ComplexMatrix: TypeAlias = NDArray[np.complex128]
RealVector: TypeAlias = NDArray[np.float64]

SIGMA_X = np.array([[0.0, 1.0], [1.0, 0.0]], dtype=np.complex128)
SIGMA_Y = np.array([[0.0, -1j], [1j, 0.0]], dtype=np.complex128)
SIGMA_Z = np.array([[1.0, 0.0], [0.0, -1.0]], dtype=np.complex128)
SIGMA_MINUS = np.array([[0.0, 1.0], [0.0, 0.0]], dtype=np.complex128)

APS_COUNTING_REFERENCE = "https://doi.org/10.1103/PhysRevLett.128.087701"
TEMPORAL_TOMOGRAPHY_REFERENCE = "https://arxiv.org/abs/2103.13973"
WIGNER_MEASUREMENT_REFERENCE = "https://doi.org/10.1119/1.1969254"


def _label(value: str, name: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{name} must be a nonempty string")
    return value.strip()


def _finite(value: float, name: str, *, minimum: float | None = None) -> float:
    result = float(value)
    if not math.isfinite(result):
        raise ValueError(f"{name} must be finite")
    if minimum is not None and result < minimum:
        raise ValueError(f"{name} must be >= {minimum}")
    return result


def _targets(values: Sequence[int]) -> tuple[int, ...]:
    targets = tuple(int(value) for value in values)
    if not targets or any(value < 0 for value in targets):
        raise ValueError("targets must contain nonnegative qubit indices")
    if len(set(targets)) != len(targets):
        raise ValueError("targets must be unique")
    return targets


def _immutable_array(value: object, dtype: np.dtype | type) -> np.ndarray:
    """Copy an array onto a bytes-backed buffer whose write flag cannot reopen."""

    prepared = np.ascontiguousarray(np.asarray(value, dtype=dtype))
    return np.frombuffer(prepared.tobytes(), dtype=prepared.dtype).reshape(prepared.shape)


def _matrix(value: ComplexMatrix, name: str) -> ComplexMatrix:
    matrix = np.asarray(value, dtype=np.complex128)
    if matrix.ndim != 2 or matrix.shape[0] != matrix.shape[1]:
        raise ValueError(f"{name} must be a square matrix")
    if matrix.shape[0] < 1 or not np.all(np.isfinite(matrix)):
        raise ValueError(f"{name} must be a finite nonempty matrix")
    return _immutable_array(matrix, np.complex128)


def _operator_dimension_for_targets(matrix: ComplexMatrix, targets: tuple[int, ...], name: str) -> None:
    expected = 2 ** len(targets)
    if matrix.shape != (expected, expected):
        raise ValueError(f"{name} shape must be {expected}x{expected} for {len(targets)} targets")


def _density(value: ComplexMatrix, name: str = "rho", tolerance: float = 1e-9) -> ComplexMatrix:
    state = _matrix(value, name)
    if not np.allclose(state, state.conj().T, atol=tolerance, rtol=0.0):
        raise ValueError(f"{name} must be Hermitian")
    trace = complex(np.trace(state))
    if abs(trace.imag) > tolerance or trace.real <= 0.0:
        raise ValueError(f"{name} must have positive real trace")
    normalized = np.asarray(state / trace.real, dtype=np.complex128)
    minimum = float(np.linalg.eigvalsh(normalized).min())
    if minimum < -tolerance:
        raise ValueError(f"{name} must be positive semidefinite; minimum eigenvalue={minimum}")
    return _immutable_array(normalized, np.complex128)


@dataclass(frozen=True)
class GateOp:
    event_id: str
    time_s: float
    targets: tuple[int, ...]
    unitary: ComplexMatrix

    def __post_init__(self) -> None:
        object.__setattr__(self, "event_id", _label(self.event_id, "event_id"))
        object.__setattr__(self, "time_s", _finite(self.time_s, "time_s", minimum=0.0))
        targets = _targets(self.targets)
        unitary = _matrix(self.unitary, "unitary")
        _operator_dimension_for_targets(unitary, targets, "unitary")
        identity = np.eye(unitary.shape[0], dtype=np.complex128)
        if not np.allclose(unitary.conj().T @ unitary, identity, atol=1e-10, rtol=0.0):
            raise ValueError("unitary must satisfy U^dagger U = I")
        object.__setattr__(self, "targets", targets)
        object.__setattr__(self, "unitary", unitary)


@dataclass(frozen=True)
class MeasureOp:
    """One scheduled selective/nonselective instrument opportunity.

    The Kraus groups define possible outcomes.  This object does not imply
    that a particular outcome has already been registered.
    """

    event_id: str
    time_s: float
    targets: tuple[int, ...]
    kraus_operators: tuple[ComplexMatrix, ...]

    def __post_init__(self) -> None:
        object.__setattr__(self, "event_id", _label(self.event_id, "event_id"))
        object.__setattr__(self, "time_s", _finite(self.time_s, "time_s", minimum=0.0))
        targets = _targets(self.targets)
        operators = tuple(_matrix(value, "kraus operator") for value in self.kraus_operators)
        if not operators:
            raise ValueError("MeasureOp requires at least one Kraus operator")
        for operator in operators:
            _operator_dimension_for_targets(operator, targets, "kraus operator")
        completeness = sum(
            (operator.conj().T @ operator for operator in operators),
            np.zeros_like(operators[0]),
        )
        if not np.allclose(
            completeness,
            np.eye(operators[0].shape[0]),
            atol=1e-10,
            rtol=0.0,
        ):
            raise ValueError("MeasureOp Kraus operators must be trace preserving")
        object.__setattr__(self, "targets", targets)
        object.__setattr__(self, "kraus_operators", operators)


@dataclass(frozen=True)
class JumpChannel:
    name: str
    operator: ComplexMatrix

    def __post_init__(self) -> None:
        object.__setattr__(self, "name", _label(self.name, "channel name"))
        object.__setattr__(self, "operator", _matrix(self.operator, "jump operator"))


@dataclass(frozen=True)
class MonitorOp:
    """A programmed observation span; events inside it remain emergent."""

    event_id: str
    start_s: float
    stop_s: float
    channels: tuple[JumpChannel, ...]

    def __post_init__(self) -> None:
        object.__setattr__(self, "event_id", _label(self.event_id, "event_id"))
        start = _finite(self.start_s, "start_s", minimum=0.0)
        stop = _finite(self.stop_s, "stop_s", minimum=0.0)
        if stop <= start:
            raise ValueError("MonitorOp stop_s must be greater than start_s")
        channels = tuple(self.channels)
        if not channels or any(not isinstance(channel, JumpChannel) for channel in channels):
            raise ValueError("MonitorOp requires one or more JumpChannel values")
        dimensions = {channel.operator.shape for channel in channels}
        if len(dimensions) != 1:
            raise ValueError("all monitor channels must use one Hilbert-space dimension")
        if len({channel.name for channel in channels}) != len(channels):
            raise ValueError("monitor channel names must be unique")
        object.__setattr__(self, "start_s", start)
        object.__setattr__(self, "stop_s", stop)
        object.__setattr__(self, "channels", channels)


ProcessOp: TypeAlias = GateOp | MeasureOp | MonitorOp


@dataclass(frozen=True)
class QuantumPerformanceGraph:
    """Shared operation identities rendered by circuit, ZX, and time lenses."""

    operations: tuple[ProcessOp, ...]
    compiler_provenance: str = "shared_circuit_zx_temporal_graph_v1"

    def __post_init__(self) -> None:
        operations = tuple(self.operations)
        if not operations:
            raise ValueError("QuantumPerformanceGraph requires operations")
        if any(not isinstance(operation, (GateOp, MeasureOp, MonitorOp)) for operation in operations):
            raise TypeError("graph operations must be GateOp, MeasureOp, or MonitorOp")
        ids = tuple(operation.event_id for operation in operations)
        if len(set(ids)) != len(ids):
            raise ValueError("each graph operation must own one unique event_id")
        object.__setattr__(self, "operations", operations)
        object.__setattr__(
            self,
            "compiler_provenance",
            _label(self.compiler_provenance, "compiler_provenance"),
        )


@dataclass(frozen=True)
class QuantumEvent:
    """One simulated conditional jump, distinct from a detector record."""

    event_id: str
    time_s: float
    source_id: str
    channel: str
    rate_hz: float
    probability: float
    backaction_norm: float
    rho_before: ComplexMatrix
    rho_after: ComplexMatrix
    origin: Literal["simulated_quantum_trajectory"] = "simulated_quantum_trajectory"
    detector_state_before: int | None = None
    detector_state_after: int | None = None
    record_confidence: float | None = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "event_id", _label(self.event_id, "event_id"))
        object.__setattr__(self, "source_id", _label(self.source_id, "source_id"))
        object.__setattr__(self, "channel", _label(self.channel, "channel"))
        object.__setattr__(self, "time_s", _finite(self.time_s, "time_s", minimum=0.0))
        object.__setattr__(self, "rate_hz", _finite(self.rate_hz, "rate_hz", minimum=0.0))
        probability = _finite(self.probability, "probability", minimum=0.0)
        if probability > 1.0:
            raise ValueError("probability must lie in [0, 1]")
        object.__setattr__(self, "probability", probability)
        object.__setattr__(
            self,
            "backaction_norm",
            _finite(self.backaction_norm, "backaction_norm", minimum=0.0),
        )
        before = _density(self.rho_before, "rho_before")
        after = _density(self.rho_after, "rho_after")
        if before.shape != after.shape:
            raise ValueError("event density matrices must have matching shapes")
        object.__setattr__(self, "rho_before", before)
        object.__setattr__(self, "rho_after", after)
        if self.origin != "simulated_quantum_trajectory":
            raise ValueError("v1 only emits explicitly simulated trajectory events")
        if (
            self.detector_state_before is not None
            or self.detector_state_after is not None
            or self.record_confidence is not None
        ):
            raise ValueError(
                "simulated trajectory events cannot claim detector states or record confidence"
            )

    def to_record(self, *, include_matrices: bool = True) -> dict[str, object]:
        record: dict[str, object] = {
            "event_id": self.event_id,
            "time_s": self.time_s,
            "source_id": self.source_id,
            "channel": self.channel,
            "rate_hz": self.rate_hz,
            "probability": self.probability,
            "backaction_norm": self.backaction_norm,
            "origin": self.origin,
            "detector_state_before": self.detector_state_before,
            "detector_state_after": self.detector_state_after,
            "record_confidence": self.record_confidence,
        }
        if include_matrices:
            record["rho_before"] = _complex_record(self.rho_before)
            record["rho_after"] = _complex_record(self.rho_after)
        return record


def stabilize_density_matrix(rho: ComplexMatrix, tolerance: float = 1e-9) -> ComplexMatrix:
    """Remove roundoff non-Hermiticity without repairing physical negativity."""

    state = np.asarray(rho, dtype=np.complex128)
    if state.ndim != 2 or state.shape[0] != state.shape[1] or not np.all(np.isfinite(state)):
        raise ValueError("density matrix must be finite and square")
    state = 0.5 * (state + state.conj().T)
    trace = complex(np.trace(state))
    if abs(trace.imag) > tolerance or trace.real <= 0.0:
        raise ValueError("density matrix has nonpositive or complex trace")
    state = state / trace.real
    minimum = float(np.linalg.eigvalsh(state).min())
    if minimum < -tolerance:
        raise ValueError(f"density matrix lost positivity: {minimum}")
    return _immutable_array(state, np.complex128)


class QuantumTrajectoryEngine:
    """First-order Monte Carlo wave-function evolution for density matrices."""

    def __init__(self, seed: int | None = None, maximum_step_probability: float = 0.05):
        self.seed = None if seed is None else int(seed)
        self.rng = np.random.default_rng(self.seed)
        maximum = _finite(maximum_step_probability, "maximum_step_probability", minimum=0.0)
        if maximum <= 0.0 or maximum > 1.0:
            raise ValueError("maximum_step_probability must lie in (0, 1]")
        self.maximum_step_probability = maximum
        self.event_count = 0

    def step(
        self,
        *,
        rho: ComplexMatrix,
        hamiltonian: ComplexMatrix,
        channels: tuple[JumpChannel, ...],
        time_s: float,
        dt_s: float,
        source_id: str,
    ) -> tuple[ComplexMatrix, QuantumEvent | None]:
        state = _density(rho)
        hamiltonian_matrix = _matrix(hamiltonian, "hamiltonian")
        if hamiltonian_matrix.shape != state.shape:
            raise ValueError("hamiltonian and rho dimensions must match")
        if not np.allclose(
            hamiltonian_matrix,
            hamiltonian_matrix.conj().T,
            atol=1e-10,
            rtol=0.0,
        ):
            raise ValueError("hamiltonian must be Hermitian")
        declared_channels = tuple(channels)
        if not declared_channels or any(not isinstance(channel, JumpChannel) for channel in declared_channels):
            raise ValueError("step requires one or more JumpChannel values")
        if any(channel.operator.shape != state.shape for channel in declared_channels):
            raise ValueError("jump channel and rho dimensions must match")
        time = _finite(time_s, "time_s", minimum=0.0)
        dt = _finite(dt_s, "dt_s", minimum=0.0)
        if dt <= 0.0:
            raise ValueError("dt_s must be positive")
        source = _label(source_id, "source_id")

        rates = np.asarray(
            [
                float(np.trace(channel.operator @ state @ channel.operator.conj().T).real)
                for channel in declared_channels
            ],
            dtype=float,
        )
        if not np.all(np.isfinite(rates)) or float(rates.min()) < -1e-10:
            raise ValueError("jump rates must be finite and nonnegative")
        rates = np.maximum(rates, 0.0)
        probabilities = dt * rates
        total_probability = float(probabilities.sum())
        if total_probability > self.maximum_step_probability:
            raise ValueError(
                "time step is too large for reliable jump simulation: "
                f"total probability {total_probability:.8g} exceeds {self.maximum_step_probability:.8g}"
            )

        if total_probability > 0.0 and float(self.rng.random()) < total_probability:
            weights = probabilities / total_probability
            index = int(self.rng.choice(len(declared_channels), p=weights))
            channel = declared_channels[index]
            numerator = channel.operator @ state @ channel.operator.conj().T
            denominator = complex(np.trace(numerator))
            if denominator.real <= 0.0 or abs(denominator.imag) > 1e-9:
                raise RuntimeError("selected jump has no normalizable posterior")
            state_after = stabilize_density_matrix(numerator / denominator.real)
            self.event_count += 1
            event = QuantumEvent(
                event_id=f"{source}:jump:{self.event_count:06d}",
                time_s=time + dt,
                source_id=source,
                channel=channel.name,
                rate_hz=float(rates[index]),
                probability=float(probabilities[index]),
                backaction_norm=float(np.linalg.norm(state_after - state)),
                rho_before=state,
                rho_after=state_after,
            )
            return state_after, event

        loss = sum(
            (channel.operator.conj().T @ channel.operator for channel in declared_channels),
            np.zeros_like(state),
        )
        effective_hamiltonian = hamiltonian_matrix - 0.5j * loss
        no_jump = np.eye(state.shape[0], dtype=np.complex128) - 1j * effective_hamiltonian * dt
        state_after = no_jump @ state @ no_jump.conj().T
        return stabilize_density_matrix(state_after), None


@dataclass(frozen=True)
class ResonatorExcitation:
    onset_s: float
    amplitude: float
    source: str
    event_id: str
    source_time_s: float
    time_scale: float

    def __post_init__(self) -> None:
        object.__setattr__(self, "onset_s", _finite(self.onset_s, "onset_s", minimum=0.0))
        object.__setattr__(self, "amplitude", _finite(self.amplitude, "amplitude", minimum=0.0))
        object.__setattr__(self, "source", _label(self.source, "source"))
        object.__setattr__(self, "event_id", _label(self.event_id, "event_id"))
        object.__setattr__(
            self, "source_time_s", _finite(self.source_time_s, "source_time_s", minimum=0.0)
        )
        scale = _finite(self.time_scale, "time_scale", minimum=0.0)
        if scale <= 0.0:
            raise ValueError("time_scale must be positive")
        object.__setattr__(self, "time_scale", scale)


class QuantumRhythmProjector:
    """Preserve event timing up to one declared uniform dilation."""

    def __init__(self, time_scale: float = 1.0, amplitude: float = 1.0):
        self.time_scale = _finite(time_scale, "time_scale", minimum=0.0)
        self.amplitude = _finite(amplitude, "amplitude", minimum=0.0)
        if self.time_scale <= 0.0:
            raise ValueError("time_scale must be positive")

    def project(self, event: QuantumEvent) -> ResonatorExcitation:
        if not isinstance(event, QuantumEvent):
            raise TypeError("project requires a QuantumEvent")
        return ResonatorExcitation(
            onset_s=self.time_scale * event.time_s,
            amplitude=self.amplitude,
            source=event.channel,
            event_id=event.event_id,
            source_time_s=event.time_s,
            time_scale=self.time_scale,
        )

    def process(self, event: QuantumEvent | None) -> tuple[ResonatorExcitation, ...]:
        return () if event is None else (self.project(event),)


ObservableFunction: TypeAlias = Callable[[ComplexMatrix], Mapping[str, float]]


def qubit_observables(rho: ComplexMatrix) -> Mapping[str, float]:
    state = _density(rho)
    if state.shape != (2, 2):
        raise ValueError("qubit_observables requires a 2x2 density matrix")
    return {
        "population_ground": float(state[0, 0].real),
        "population_excited": float(state[1, 1].real),
        "pauli_x": float(np.trace(state @ SIGMA_X).real),
        "pauli_y": float(np.trace(state @ SIGMA_Y).real),
        "pauli_z": float(np.trace(state @ SIGMA_Z).real),
        "purity": float(np.trace(state @ state).real),
    }


@dataclass(frozen=True)
class QMWTemporalFrame:
    """One synchronized frame after conditional measurement backaction."""

    time_s: float
    revision: int
    rho: ComplexMatrix
    quantum_event: QuantumEvent | None
    observables: Mapping[str, float]
    excitations: tuple[ResonatorExcitation, ...]
    source_id: str
    causal_order: tuple[str, ...] = (
        "quantum_measurement_and_backaction",
        "observables",
        "rhythm_projection",
        "sound",
    )
    provenance: str = "qmw_temporal_frame_simulated_monitor_v1"

    def __post_init__(self) -> None:
        object.__setattr__(self, "time_s", _finite(self.time_s, "time_s", minimum=0.0))
        if isinstance(self.revision, bool) or int(self.revision) != self.revision or self.revision < 0:
            raise ValueError("revision must be a nonnegative integer")
        object.__setattr__(self, "revision", int(self.revision))
        object.__setattr__(self, "rho", _density(self.rho))
        if self.quantum_event is not None and not isinstance(self.quantum_event, QuantumEvent):
            raise TypeError("quantum_event must be QuantumEvent or None")
        values = {str(key): _finite(value, f"observable {key}") for key, value in self.observables.items()}
        object.__setattr__(self, "observables", MappingProxyType(values))
        excitations = tuple(self.excitations)
        if any(not isinstance(value, ResonatorExcitation) for value in excitations):
            raise TypeError("excitations must contain ResonatorExcitation values")
        object.__setattr__(self, "excitations", excitations)
        object.__setattr__(self, "source_id", _label(self.source_id, "source_id"))
        expected = (
            "quantum_measurement_and_backaction",
            "observables",
            "rhythm_projection",
            "sound",
        )
        if tuple(self.causal_order) != expected:
            raise ValueError("QMWTemporalFrame causal order is fixed in v1")


def advance_monitored_frame(
    *,
    engine: QuantumTrajectoryEngine,
    rho: ComplexMatrix,
    hamiltonian: ComplexMatrix,
    monitor: MonitorOp,
    time_s: float,
    dt_s: float,
    revision: int,
    projector: QuantumRhythmProjector,
    observable_function: ObservableFunction = qubit_observables,
) -> QMWTemporalFrame:
    """Advance one monitor tick in the required causal order."""

    if time_s < monitor.start_s or time_s + dt_s > monitor.stop_s + 1e-12:
        raise ValueError("monitor tick must lie entirely inside the MonitorOp span")
    state_after, event = engine.step(
        rho=rho,
        hamiltonian=hamiltonian,
        channels=monitor.channels,
        time_s=time_s,
        dt_s=dt_s,
        source_id=monitor.event_id,
    )
    observables = observable_function(state_after)
    excitations = projector.process(event)
    return QMWTemporalFrame(
        time_s=time_s + dt_s,
        revision=revision,
        rho=state_after,
        quantum_event=event,
        observables=observables,
        excitations=excitations,
        source_id=monitor.event_id,
    )


def inter_event_intervals(events: Sequence[QuantumEvent]) -> RealVector:
    times = np.asarray([event.time_s for event in events], dtype=float)
    if times.size > 1 and np.any(np.diff(times) < 0.0):
        raise ValueError("events must be ordered by time")
    return np.diff(times)


def counts_per_window(
    events: Sequence[QuantumEvent], *, window_s: float, duration_s: float, start_s: float = 0.0
) -> NDArray[np.int64]:
    window = _finite(window_s, "window_s", minimum=0.0)
    duration = _finite(duration_s, "duration_s", minimum=0.0)
    start = _finite(start_s, "start_s", minimum=0.0)
    if window <= 0.0 or duration <= 0.0:
        raise ValueError("window_s and duration_s must be positive")
    number = duration / window
    rounded = int(round(number))
    if rounded < 1 or not math.isclose(number, rounded, rel_tol=0.0, abs_tol=1e-10):
        raise ValueError("duration_s must contain an integer number of equal counting windows")
    times = np.asarray([event.time_s for event in events], dtype=float)
    if times.size and (float(times.min()) < start - 1e-12 or float(times.max()) > start + duration + 1e-12):
        raise ValueError("event lies outside the declared counting span")
    edges = start + np.arange(rounded + 1, dtype=float) * window
    counts, _ = np.histogram(times, bins=edges)
    return counts.astype(np.int64, copy=False)


def factorial_cumulants(counts: NDArray[np.integer], maximum_order: int) -> RealVector:
    values = np.asarray(counts)
    if values.ndim != 1 or values.size < 1:
        raise ValueError("counts must be a nonempty one-dimensional array")
    if not np.issubdtype(values.dtype, np.integer) or np.any(values < 0):
        raise ValueError("counts must contain nonnegative integers")
    if isinstance(maximum_order, bool) or int(maximum_order) != maximum_order or maximum_order < 1:
        raise ValueError("maximum_order must be a positive integer")
    order_limit = int(maximum_order)
    factorial_moments = np.zeros(order_limit + 1, dtype=float)
    cumulants = np.zeros(order_limit + 1, dtype=float)
    factorial_moments[0] = 1.0
    float_counts = values.astype(float)
    for order in range(1, order_limit + 1):
        falling = np.ones_like(float_counts)
        for k in range(order):
            falling *= float_counts - k
        factorial_moments[order] = float(falling.mean())
    for order in range(1, order_limit + 1):
        value = factorial_moments[order]
        for k in range(1, order):
            value -= comb(order - 1, k - 1) * cumulants[k] * factorial_moments[order - k]
        cumulants[order] = value
    return cumulants[1:]


@dataclass(frozen=True)
class DetectorModel:
    """Declared independent missed-event and false-positive model.

    ``efficiency`` is independent Bernoulli thinning of true events. False
    events are an independent Poisson process. Under those assumptions the
    first factorial cumulant loses the false-event mean and higher orders scale
    by efficiency**order. This is a correction model, not detector evidence.
    """

    efficiency: float = 1.0
    false_event_rate_hz: float = 0.0

    def __post_init__(self) -> None:
        efficiency = _finite(self.efficiency, "detector efficiency", minimum=0.0)
        false_rate = _finite(self.false_event_rate_hz, "false event rate", minimum=0.0)
        if efficiency <= 0.0 or efficiency > 1.0:
            raise ValueError("detector efficiency must lie in (0, 1]")
        object.__setattr__(self, "efficiency", efficiency)
        object.__setattr__(self, "false_event_rate_hz", false_rate)


def detector_corrected_factorial_cumulants(
    observed: Sequence[float], *, window_s: float, model: DetectorModel
) -> RealVector:
    """Invert the declared thinning-plus-Poisson-background cumulant model."""

    if not isinstance(model, DetectorModel):
        raise TypeError("model must be a DetectorModel")
    window = _finite(window_s, "window_s", minimum=0.0)
    if window <= 0.0:
        raise ValueError("window_s must be positive")
    values = np.asarray(observed, dtype=float)
    if values.ndim != 1 or values.size < 1 or not np.all(np.isfinite(values)):
        raise ValueError("observed cumulants must be a finite nonempty vector")
    corrected = np.empty_like(values)
    corrected[0] = (values[0] - model.false_event_rate_hz * window) / model.efficiency
    for index in range(1, len(values)):
        corrected[index] = values[index] / model.efficiency ** (index + 1)
    return _immutable_array(corrected, np.float64)


def bootstrap_factorial_cumulants(
    counts: NDArray[np.integer],
    maximum_order: int,
    *,
    resamples: int = 2000,
    seed: int = 271828,
) -> NDArray[np.float64]:
    """Return deterministic percentile 95% intervals from counting windows."""

    values = np.asarray(counts)
    # Reuse the strict value/order validation before allocating the bootstrap.
    factorial_cumulants(values, maximum_order)
    if isinstance(resamples, bool) or int(resamples) != resamples or resamples < 100:
        raise ValueError("resamples must be an integer of at least 100")
    rng = np.random.default_rng(int(seed))
    estimates = np.empty((int(resamples), int(maximum_order)), dtype=float)
    for index in range(int(resamples)):
        sample = rng.choice(values, size=values.size, replace=True)
        estimates[index] = factorial_cumulants(sample, maximum_order)
    intervals = np.percentile(estimates, (2.5, 97.5), axis=0).T
    return _immutable_array(intervals, np.float64)


def poisson_count_diagnostics(counts: NDArray[np.integer]) -> Mapping[str, object]:
    """Compare window counts with a fitted Poisson reference without overclaiming."""

    values = np.asarray(counts)
    factorial_cumulants(values, 1)
    mean = float(values.mean())
    variance = float(values.var(ddof=1)) if values.size > 1 else 0.0
    fano = None if mean == 0.0 else variance / mean
    observed_maximum = int(values.max(initial=0))
    support_maximum = max(observed_maximum, int(math.ceil(mean + 8.0 * math.sqrt(mean) + 10.0)))
    support = np.arange(support_maximum + 1, dtype=int)
    poisson = np.empty(support_maximum + 1, dtype=float)
    poisson[0] = math.exp(-mean)
    for index in range(1, len(poisson)):
        poisson[index] = poisson[index - 1] * mean / index
    observed = np.bincount(values, minlength=len(poisson)).astype(float) / values.size
    tail = max(0.0, 1.0 - float(poisson.sum()))
    total_variation = 0.5 * (float(np.sum(np.abs(observed - poisson))) + tail)
    if values.size < 30:
        inference = "descriptive_only_fewer_than_30_windows"
    elif fano is not None and abs(fano - 1.0) <= 0.2:
        inference = "approximately_poisson_by_dispersion_only"
    else:
        inference = "dispersion_departs_from_poisson_reference"
    return MappingProxyType(
        {
            "window_count": int(values.size),
            "mean_count": mean,
            "sample_variance": variance,
            "fano_factor": fano,
            "poisson_total_variation_distance": total_variation,
            "poisson_fit_parameter": "empirical_mean_count",
            "inference": inference,
            "claim_boundary": "irregularity or dispersion alone does not establish nonclassical timing",
        }
    )


@dataclass(frozen=True)
class FullCountingStatistics:
    window_s: float
    duration_s: float
    counts: NDArray[np.int64]
    count_values: NDArray[np.int64]
    probabilities: RealVector
    factorial_cumulants: RealVector
    factorial_cumulant_ci95: NDArray[np.float64]
    poisson_diagnostics: Mapping[str, object]
    detector_model: DetectorModel
    detector_corrected_factorial_cumulants: RealVector
    bootstrap_seed: int
    bootstrap_resamples: int
    provenance: str = "simulated_event_stream_nonoverlapping_windows_v1"

    def __post_init__(self) -> None:
        window = _finite(self.window_s, "window_s", minimum=0.0)
        duration = _finite(self.duration_s, "duration_s", minimum=0.0)
        if window <= 0.0 or duration <= 0.0:
            raise ValueError("counting window and duration must be positive")
        counts = np.asarray(self.counts, dtype=np.int64)
        count_values = np.asarray(self.count_values, dtype=np.int64)
        probabilities = np.asarray(self.probabilities, dtype=float)
        cumulants = np.asarray(self.factorial_cumulants, dtype=float)
        intervals = np.asarray(self.factorial_cumulant_ci95, dtype=float)
        corrected = np.asarray(self.detector_corrected_factorial_cumulants, dtype=float)
        if counts.ndim != 1 or counts.size < 1 or np.any(counts < 0):
            raise ValueError("counts must be a nonempty nonnegative vector")
        if count_values.ndim != 1 or probabilities.shape != count_values.shape:
            raise ValueError("count values and probabilities must be matching vectors")
        if cumulants.ndim != 1 or cumulants.size < 1:
            raise ValueError("factorial cumulants must be a nonempty vector")
        if intervals.shape != (cumulants.size, 2) or not np.all(np.isfinite(intervals)):
            raise ValueError("factorial cumulant intervals must have shape (orders, 2)")
        if corrected.shape != cumulants.shape or not np.all(np.isfinite(corrected)):
            raise ValueError("detector-corrected cumulants must match observed orders")
        if not isinstance(self.poisson_diagnostics, Mapping) or not isinstance(self.detector_model, DetectorModel):
            raise TypeError("counting diagnostics and DetectorModel are required")
        if isinstance(self.bootstrap_seed, bool) or int(self.bootstrap_seed) != self.bootstrap_seed:
            raise ValueError("bootstrap_seed must be an integer")
        if isinstance(self.bootstrap_resamples, bool) or int(self.bootstrap_resamples) != self.bootstrap_resamples or self.bootstrap_resamples < 100:
            raise ValueError("bootstrap_resamples must be an integer of at least 100")
        if np.any(probabilities < 0.0) or not math.isclose(
            float(probabilities.sum()), 1.0, rel_tol=0.0, abs_tol=1e-12
        ):
            raise ValueError("count probabilities must form a normalized distribution")
        counts = _immutable_array(counts, np.int64)
        count_values = _immutable_array(count_values, np.int64)
        probabilities = _immutable_array(probabilities, np.float64)
        cumulants = _immutable_array(cumulants, np.float64)
        intervals = _immutable_array(intervals, np.float64)
        corrected = _immutable_array(corrected, np.float64)
        object.__setattr__(self, "window_s", window)
        object.__setattr__(self, "duration_s", duration)
        object.__setattr__(self, "counts", counts)
        object.__setattr__(self, "count_values", count_values)
        object.__setattr__(self, "probabilities", probabilities)
        object.__setattr__(self, "factorial_cumulants", cumulants)
        object.__setattr__(self, "factorial_cumulant_ci95", intervals)
        object.__setattr__(self, "poisson_diagnostics", MappingProxyType(dict(self.poisson_diagnostics)))
        object.__setattr__(self, "detector_corrected_factorial_cumulants", corrected)
        object.__setattr__(self, "bootstrap_seed", int(self.bootstrap_seed))
        object.__setattr__(self, "bootstrap_resamples", int(self.bootstrap_resamples))
        object.__setattr__(self, "provenance", _label(self.provenance, "provenance"))

    def to_record(self) -> dict[str, object]:
        return {
            "window_s": self.window_s,
            "duration_s": self.duration_s,
            "counts": self.counts.tolist(),
            "P_N": {
                str(int(count)): float(probability)
                for count, probability in zip(self.count_values, self.probabilities)
            },
            "factorial_cumulants": self.factorial_cumulants.tolist(),
            "factorial_cumulant_ci95": self.factorial_cumulant_ci95.tolist(),
            "poisson_diagnostics": dict(self.poisson_diagnostics),
            "detector_model": asdict(self.detector_model),
            "detector_corrected_factorial_cumulants": self.detector_corrected_factorial_cumulants.tolist(),
            "detector_correction_assumptions": "independent Bernoulli thinning plus independent Poisson false events",
            "bootstrap": {"seed": self.bootstrap_seed, "resamples": self.bootstrap_resamples, "interval": "percentile_95"},
            "orders": list(range(1, len(self.factorial_cumulants) + 1)),
            "provenance": self.provenance,
        }


def full_counting_statistics(
    events: Sequence[QuantumEvent],
    *,
    window_s: float,
    duration_s: float,
    maximum_order: int = 4,
    start_s: float = 0.0,
    detector_model: DetectorModel = DetectorModel(),
    bootstrap_seed: int = 271828,
    bootstrap_resamples: int = 2000,
) -> FullCountingStatistics:
    counts = counts_per_window(events, window_s=window_s, duration_s=duration_s, start_s=start_s)
    values = np.arange(int(counts.max(initial=0)) + 1, dtype=np.int64)
    probabilities = np.bincount(counts, minlength=len(values)).astype(float) / counts.size
    cumulants = factorial_cumulants(counts, maximum_order)
    return FullCountingStatistics(
        window_s=float(window_s),
        duration_s=float(duration_s),
        counts=counts,
        count_values=values,
        probabilities=probabilities,
        factorial_cumulants=cumulants,
        factorial_cumulant_ci95=bootstrap_factorial_cumulants(
            counts, maximum_order, resamples=bootstrap_resamples, seed=bootstrap_seed
        ),
        poisson_diagnostics=poisson_count_diagnostics(counts),
        detector_model=detector_model,
        detector_corrected_factorial_cumulants=detector_corrected_factorial_cumulants(
            cumulants, window_s=window_s, model=detector_model
        ),
        bootstrap_seed=bootstrap_seed,
        bootstrap_resamples=bootstrap_resamples,
    )


@dataclass(frozen=True)
class DrivenQubitExperimentConfig:
    duration_s: float = 10.0
    dt_s: float = 0.0005
    rabi_hz: float = 3.0
    decay_rate_hz: float = 4.0
    seed: int = 42
    counting_window_s: float = 0.5
    monitor_id: str = "monitor-001"

    def __post_init__(self) -> None:
        duration = _finite(self.duration_s, "duration_s", minimum=0.0)
        dt = _finite(self.dt_s, "dt_s", minimum=0.0)
        rabi = _finite(self.rabi_hz, "rabi_hz", minimum=0.0)
        decay = _finite(self.decay_rate_hz, "decay_rate_hz", minimum=0.0)
        window = _finite(self.counting_window_s, "counting_window_s", minimum=0.0)
        if min(duration, dt, rabi, decay, window) <= 0.0:
            raise ValueError("experiment rates, durations, dt, and counting window must be positive")
        steps = duration / dt
        if not math.isclose(steps, round(steps), rel_tol=0.0, abs_tol=1e-9):
            raise ValueError("duration_s must contain an integer number of dt_s steps")
        windows = duration / window
        if not math.isclose(windows, round(windows), rel_tol=0.0, abs_tol=1e-9):
            raise ValueError("duration_s must contain an integer number of counting windows")
        object.__setattr__(self, "duration_s", duration)
        object.__setattr__(self, "dt_s", dt)
        object.__setattr__(self, "rabi_hz", rabi)
        object.__setattr__(self, "decay_rate_hz", decay)
        object.__setattr__(self, "counting_window_s", window)
        object.__setattr__(self, "seed", int(self.seed))
        object.__setattr__(self, "monitor_id", _label(self.monitor_id, "monitor_id"))


@dataclass(frozen=True)
class DrivenQubitExperimentResult:
    config: DrivenQubitExperimentConfig
    graph: QuantumPerformanceGraph
    events: tuple[QuantumEvent, ...]
    event_frames: tuple[QMWTemporalFrame, ...]
    final_rho: ComplexMatrix
    statistics: FullCountingStatistics

    def __post_init__(self) -> None:
        if not isinstance(self.config, DrivenQubitExperimentConfig):
            raise TypeError("config must be DrivenQubitExperimentConfig")
        if not isinstance(self.graph, QuantumPerformanceGraph):
            raise TypeError("graph must be QuantumPerformanceGraph")
        events = tuple(self.events)
        frames = tuple(self.event_frames)
        if any(not isinstance(value, QuantumEvent) for value in events):
            raise TypeError("events must contain QuantumEvent values")
        if any(not isinstance(value, QMWTemporalFrame) for value in frames):
            raise TypeError("event_frames must contain QMWTemporalFrame values")
        if len(events) != len(frames):
            raise ValueError("each event must have one synchronized event frame")
        if any(frame.quantum_event is not event for frame, event in zip(frames, events)):
            raise ValueError("event frames must retain the exact event identities")
        object.__setattr__(self, "events", events)
        object.__setattr__(self, "event_frames", frames)
        object.__setattr__(self, "final_rho", _density(self.final_rho, "final_rho"))
        if not isinstance(self.statistics, FullCountingStatistics):
            raise TypeError("statistics must be FullCountingStatistics")

    @property
    def dwell_times_s(self) -> RealVector:
        return inter_event_intervals(self.events)


def driven_qubit_model(config: DrivenQubitExperimentConfig) -> tuple[ComplexMatrix, MonitorOp, ComplexMatrix]:
    omega = 2.0 * math.pi * config.rabi_hz
    hamiltonian = 0.5 * omega * SIGMA_X
    channel = JumpChannel("decay", math.sqrt(config.decay_rate_hz) * SIGMA_MINUS)
    monitor = MonitorOp(config.monitor_id, 0.0, config.duration_s, (channel,))
    rho_initial = np.array([[1.0, 0.0], [0.0, 0.0]], dtype=np.complex128)
    return hamiltonian, monitor, rho_initial


def run_driven_qubit_experiment(
    config: DrivenQubitExperimentConfig = DrivenQubitExperimentConfig(),
) -> DrivenQubitExperimentResult:
    hamiltonian, monitor, rho = driven_qubit_model(config)
    graph = QuantumPerformanceGraph((monitor,))
    engine = QuantumTrajectoryEngine(seed=config.seed)
    projector = QuantumRhythmProjector(time_scale=1.0, amplitude=1.0)
    events: list[QuantumEvent] = []
    event_frames: list[QMWTemporalFrame] = []
    number_of_steps = int(round(config.duration_s / config.dt_s))
    for step_index in range(number_of_steps):
        frame = advance_monitored_frame(
            engine=engine,
            rho=rho,
            hamiltonian=hamiltonian,
            monitor=monitor,
            time_s=step_index * config.dt_s,
            dt_s=config.dt_s,
            revision=step_index + 1,
            projector=projector,
        )
        rho = frame.rho
        if frame.quantum_event is not None:
            events.append(frame.quantum_event)
            event_frames.append(frame)
    statistics = full_counting_statistics(
        events,
        window_s=config.counting_window_s,
        duration_s=config.duration_s,
        maximum_order=4,
    )
    return DrivenQubitExperimentResult(
        config=config,
        graph=graph,
        events=tuple(events),
        event_frames=tuple(event_frames),
        final_rho=rho,
        statistics=statistics,
    )


@dataclass(frozen=True)
class FixedResonator:
    frequency_hz: float = 440.0
    decay_s: float = 0.35
    sample_rate_hz: int = 12_000
    tail_decay_constants: float = 7.0

    def __post_init__(self) -> None:
        frequency = _finite(self.frequency_hz, "frequency_hz", minimum=0.0)
        decay = _finite(self.decay_s, "decay_s", minimum=0.0)
        tail = _finite(self.tail_decay_constants, "tail_decay_constants", minimum=0.0)
        if min(frequency, decay, tail) <= 0.0:
            raise ValueError("resonator frequency, decay, and tail must be positive")
        if isinstance(self.sample_rate_hz, bool) or int(self.sample_rate_hz) != self.sample_rate_hz:
            raise ValueError("sample_rate_hz must be an integer")
        sample_rate = int(self.sample_rate_hz)
        if sample_rate < 2 * frequency:
            raise ValueError("sample rate must exceed the Nyquist rate")
        object.__setattr__(self, "frequency_hz", frequency)
        object.__setattr__(self, "decay_s", decay)
        object.__setattr__(self, "tail_decay_constants", tail)
        object.__setattr__(self, "sample_rate_hz", sample_rate)

    def render(self, excitations: Sequence[ResonatorExcitation]) -> NDArray[np.float32]:
        declared = tuple(excitations)
        if any(not isinstance(value, ResonatorExcitation) for value in declared):
            raise TypeError("resonator input must contain ResonatorExcitation values")
        tail_s = self.tail_decay_constants * self.decay_s
        last_onset = max((event.onset_s for event in declared), default=0.0)
        sample_count = max(1, int(math.ceil((last_onset + tail_s) * self.sample_rate_hz)) + 1)
        output = np.zeros(sample_count, dtype=np.float32)
        response_count = int(math.ceil(tail_s * self.sample_rate_hz)) + 1
        time = np.arange(response_count, dtype=float) / self.sample_rate_hz
        response = np.exp(-time / self.decay_s) * np.sin(2.0 * math.pi * self.frequency_hz * time)
        for excitation in declared:
            start = int(round(excitation.onset_s * self.sample_rate_hz))
            stop = min(sample_count, start + response_count)
            output[start:stop] += np.asarray(
                excitation.amplitude * response[: stop - start], dtype=np.float32
            )
        return output


def _complex_record(matrix: ComplexMatrix) -> dict[str, object]:
    return {"real": np.asarray(matrix).real.tolist(), "imag": np.asarray(matrix).imag.tolist()}


def _operation_record(operation: ProcessOp) -> dict[str, object]:
    if isinstance(operation, GateOp):
        return {
            "kind": "gate",
            "event_id": operation.event_id,
            "time_s": operation.time_s,
            "targets": list(operation.targets),
            "unitary": _complex_record(operation.unitary),
        }
    if isinstance(operation, MeasureOp):
        return {
            "kind": "measure",
            "event_id": operation.event_id,
            "time_s": operation.time_s,
            "targets": list(operation.targets),
            "kraus_operators": [_complex_record(value) for value in operation.kraus_operators],
        }
    return {
        "kind": "monitor",
        "event_id": operation.event_id,
        "start_s": operation.start_s,
        "stop_s": operation.stop_s,
        "channels": [
            {"name": channel.name, "operator": _complex_record(channel.operator)}
            for channel in operation.channels
        ],
    }


def render_temporal_svg(
    graph: QuantumPerformanceGraph,
    events: Sequence[QuantumEvent],
    *,
    width: int = 1400,
    height: int = 430,
) -> str:
    """Render synchronized circuit, ZX, and temporal lenses as one SVG."""

    monitors = tuple(value for value in graph.operations if isinstance(value, MonitorOp))
    if not monitors:
        raise ValueError("temporal SVG requires at least one MonitorOp")
    start = min(value.start_s for value in monitors)
    stop = max(value.stop_s for value in monitors)
    left, right = 175.0, float(width - 55)
    span = stop - start

    def x_at(time_s: float) -> float:
        return left + (float(time_s) - start) / span * (right - left)

    palette = {"background": "#0b1020", "panel": "#141d32", "text": "#e8edf7",
               "muted": "#8ea0bd", "monitor": "#53d8c4", "event": "#ffbf69",
               "zx": "#bb86fc", "grid": "#2a3854"}
    lines = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        f'<rect width="100%" height="100%" fill="{palette["background"]}"/>',
        f'<text x="40" y="42" fill="{palette["text"]}" font-family="system-ui,sans-serif" font-size="24" font-weight="700">QMW monitored trajectory 001</text>',
        f'<text x="40" y="68" fill="{palette["muted"]}" font-family="system-ui,sans-serif" font-size="14">One process graph, three synchronized lenses - monitor span programmed; jump times emergent and unquantized.</text>',
    ]
    for y in (115, 215, 315):
        lines.append(f'<rect x="30" y="{y - 30}" width="{width - 60}" height="80" rx="10" fill="{palette["panel"]}"/>')
        lines.append(f'<line x1="{left}" y1="{y}" x2="{right}" y2="{y}" stroke="{palette["grid"]}" stroke-width="2"/>')
    labels = ((115, "Circuit lens"), (215, "ZX lens"), (315, "Temporal lens"))
    for y, label in labels:
        lines.append(f'<text x="48" y="{y + 5}" fill="{palette["text"]}" font-family="system-ui,sans-serif" font-size="15">{label}</text>')
    for monitor in monitors:
        x1, x2 = x_at(monitor.start_s), x_at(monitor.stop_s)
        identifier = escape(monitor.event_id)
        lines.append(f'<path d="M{x1:.2f},125 V102 H{x2:.2f} V125" fill="none" stroke="{palette["monitor"]}" stroke-width="4"/>')
        lines.append(f'<text x="{(x1 + x2) / 2:.2f}" y="98" text-anchor="middle" fill="{palette["monitor"]}" font-family="ui-monospace,monospace" font-size="13">MonitorOp {identifier}</text>')
        midpoint = (x1 + x2) / 2
        lines.append(f'<circle cx="{midpoint:.2f}" cy="215" r="20" fill="none" stroke="{palette["zx"]}" stroke-width="4"/>')
        lines.append(f'<text x="{midpoint:.2f}" y="220" text-anchor="middle" fill="{palette["text"]}" font-family="ui-monospace,monospace" font-size="12">MON</text>')
        lines.append(f'<text x="{midpoint:.2f}" y="248" text-anchor="middle" fill="{palette["zx"]}" font-family="ui-monospace,monospace" font-size="12">same id: {identifier}</text>')
        lines.append(f'<line x1="{x1:.2f}" y1="305" x2="{x2:.2f}" y2="305" stroke="{palette["monitor"]}" stroke-width="8" stroke-linecap="round" opacity="0.55"/>')
    for event in events:
        if not start <= event.time_s <= stop:
            raise ValueError("event lies outside rendered monitor span")
        x = x_at(event.time_s)
        lines.append(f'<line x1="{x:.2f}" y1="286" x2="{x:.2f}" y2="334" stroke="{palette["event"]}" stroke-width="2"/>')
        lines.append(f'<circle cx="{x:.2f}" cy="305" r="4" fill="{palette["event"]}"/>')
    for fraction in np.linspace(0.0, 1.0, 6):
        time = start + fraction * span
        x = x_at(time)
        lines.append(f'<text x="{x:.2f}" y="363" text-anchor="middle" fill="{palette["muted"]}" font-family="ui-monospace,monospace" font-size="12">{time:.3g} s</text>')
    lines.append(f'<text x="48" y="402" fill="{palette["muted"]}" font-family="system-ui,sans-serif" font-size="13">Events: {len(events)} | origin: simulated conditional trajectory | no beat grid | no detector reconstruction</text>')
    lines.append("</svg>")
    return "\n".join(lines) + "\n"


def _write_pcm16(path: Path, samples: NDArray[np.floating], sample_rate_hz: int, gain: float) -> None:
    scaled = np.clip(np.asarray(samples, dtype=float) * gain, -1.0, 1.0)
    pcm = np.asarray(np.round(scaled * 32767.0), dtype="<i2")
    with wave.open(str(path), "wb") as stream:
        stream.setnchannels(1)
        stream.setsampwidth(2)
        stream.setframerate(sample_rate_hz)
        stream.writeframes(pcm.tobytes())


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def export_driven_qubit_experiment(
    result: DrivenQubitExperimentResult,
    output_directory: str | Path,
    *,
    time_scales: Sequence[float] = (1.0, 10.0, 100.0),
    render_audio: bool = True,
    resonator: FixedResonator = FixedResonator(),
) -> Path:
    """Export replayable data, counting statistics, SVG, and WAV comparisons."""

    output = Path(output_directory).expanduser().resolve()
    output.mkdir(parents=True, exist_ok=True)
    scales = tuple(_finite(value, "time scale", minimum=0.0) for value in time_scales)
    if not scales or any(value <= 0.0 for value in scales) or len(set(scales)) != len(scales):
        raise ValueError("time_scales must contain unique positive values")

    events_path = output / "quantum_events.csv"
    with events_path.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(
            stream,
            fieldnames=(
                "event_id", "time_s", "interval_from_previous_s", "source_id", "channel",
                "rate_hz", "step_probability", "backaction_norm", "origin",
            ),
        )
        writer.writeheader()
        previous: float | None = None
        for event in result.events:
            writer.writerow(
                {
                    "event_id": event.event_id,
                    "time_s": f"{event.time_s:.12g}",
                    "interval_from_previous_s": "" if previous is None else f"{event.time_s - previous:.12g}",
                    "source_id": event.source_id,
                    "channel": event.channel,
                    "rate_hz": f"{event.rate_hz:.12g}",
                    "step_probability": f"{event.probability:.12g}",
                    "backaction_norm": f"{event.backaction_norm:.12g}",
                    "origin": event.origin,
                }
            )
            previous = event.time_s

    dwell_path = output / "dwell_times.csv"
    with dwell_path.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.writer(stream)
        writer.writerow(("interval_index", "start_event_id", "stop_event_id", "dwell_time_s"))
        for index, (first, second) in enumerate(zip(result.events, result.events[1:]), start=1):
            writer.writerow((index, first.event_id, second.event_id, f"{second.time_s - first.time_s:.12g}"))

    statistics_path = output / "full_counting_statistics.json"
    statistics_path.write_text(
        json.dumps(result.statistics.to_record(), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    timeline_path = output / "circuit_zx_temporal_timeline.svg"
    timeline_path.write_text(render_temporal_svg(result.graph, result.events), encoding="utf-8")

    schedules: dict[str, list[ResonatorExcitation]] = {}
    generated_paths: list[Path] = [events_path, dwell_path, statistics_path, timeline_path]
    for scale in scales:
        key = f"{scale:g}x"
        projected = [QuantumRhythmProjector(scale, 1.0).project(event) for event in result.events]
        schedules[key] = projected
        schedule_path = output / f"resonator_excitations_{key}.csv"
        with schedule_path.open("w", newline="", encoding="utf-8") as stream:
            writer = csv.DictWriter(
                stream,
                fieldnames=("event_id", "source_time_s", "onset_s", "time_scale", "amplitude", "source"),
            )
            writer.writeheader()
            for excitation in projected:
                writer.writerow(asdict(excitation))
        generated_paths.append(schedule_path)

    if render_audio:
        rendered = {key: resonator.render(values) for key, values in schedules.items()}
        global_peak = max((float(np.max(np.abs(value), initial=0.0)) for value in rendered.values()), default=0.0)
        gain = 0.9 / global_peak if global_peak > 0.0 else 1.0
        for key, samples in rendered.items():
            audio_path = output / f"fixed_resonator_{key}.wav"
            _write_pcm16(audio_path, samples, resonator.sample_rate_hz, gain)
            generated_paths.append(audio_path)
    else:
        gain = None

    manifest = {
        "schema": "qmw_quantum_temporal_monitor_experiment_001_v1",
        "scientific_scope": {
            "process": "simulated driven one-qubit conditional quantum-jump trajectory",
            "rhythm_origin": "emergent simulated jump timestamps",
            "not_claimed": [
                "hardware observation",
                "detector reconstruction",
                "uniquely nonclassical timing inferred from irregularity alone",
                "temporal quantum tomography implementation",
                "resolution of the measurement problem",
            ],
            "causal_order": list(QMWTemporalFrame.causal_order),
        },
        "references": {
            "counting_statistics_and_detector_errors": APS_COUNTING_REFERENCE,
            "history_dependent_temporal_tomography_boundary": TEMPORAL_TOMOGRAPHY_REFERENCE,
            "unitary_correlation_vs_selective_outcome_boundary": WIGNER_MEASUREMENT_REFERENCE,
        },
        "config": asdict(result.config),
        "performance_graph": {
            "compiler_provenance": result.graph.compiler_provenance,
            "operations": [_operation_record(value) for value in result.graph.operations],
        },
        "event_count": len(result.events),
        "events": [event.to_record(include_matrices=True) for event in result.events],
        "final_rho": _complex_record(result.final_rho),
        "counting_statistics": result.statistics.to_record(),
        "time_scales": list(scales),
        "projection": {
            "amplitude": 1.0,
            "quantization": None,
            "meter": None,
            "resonator_frequency_hz": resonator.frequency_hz,
            "resonator_decay_s": resonator.decay_s,
            "sample_rate_hz": resonator.sample_rate_hz,
            "shared_audio_gain": gain,
        },
        "files": {
            path.name: {"sha256": _sha256(path), "bytes": path.stat().st_size}
            for path in generated_paths
        },
    }
    manifest_path = output / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return manifest_path


__all__ = [
    "APS_COUNTING_REFERENCE",
    "ComplexMatrix",
    "DetectorModel",
    "DrivenQubitExperimentConfig",
    "DrivenQubitExperimentResult",
    "FixedResonator",
    "FullCountingStatistics",
    "GateOp",
    "JumpChannel",
    "MeasureOp",
    "MonitorOp",
    "QMWTemporalFrame",
    "QuantumEvent",
    "QuantumPerformanceGraph",
    "QuantumRhythmProjector",
    "QuantumTrajectoryEngine",
    "ResonatorExcitation",
    "advance_monitored_frame",
    "bootstrap_factorial_cumulants",
    "counts_per_window",
    "detector_corrected_factorial_cumulants",
    "driven_qubit_model",
    "export_driven_qubit_experiment",
    "factorial_cumulants",
    "full_counting_statistics",
    "inter_event_intervals",
    "poisson_count_diagnostics",
    "qubit_observables",
    "render_temporal_svg",
    "run_driven_qubit_experiment",
    "stabilize_density_matrix",
]
