"""Authoritative QMW runtime frame and deterministic scheduler contracts."""

from .frame import (
    CANONICAL_RUNTIME_STEPS,
    DirtyFlags,
    FrameRevisions,
    QMWFrame,
    RuntimePhase,
    RuntimeStep,
    RuntimeTriggers,
    steps_for_phase,
)
from .scheduler import (
    QMWRuntimeScheduler,
    RuntimeStepError,
    TickResult,
)
from .qmw_flow_bridge import qmw_frame_from_authoritative_flow
from .quantum_field_adapter import (
    QuantumFieldRuntimeAdapter,
    register_quantum_field_engine,
)
from .quench_adapter import QuenchRuntimeAdapter, register_quench_engine
from .memory_matrix_adapter import (
    MemoryDensityProjector,
    MemoryMatrixRuntimeAdapter,
    register_memory_matrix_engine,
)
from .quantum_engine_adapter import (
    QuantumEngineRuntimeAdapter,
    QuantumGeneratorControlBatch,
    QuantumValidationFrame,
    register_quantum_engine,
    validate_quantum_frame,
)
from .flow_geometry_adapter import (
    FlowGeometryRuntimeAdapter,
    FlowGeometryRuntimeConfig,
    GeometryEigenmodeFrame,
    HilbertBasisProjectionFrame,
    register_flow_geometry,
)
from .error_recovery_adapter import (
    ErrorRecoveryRuntimeAdapter,
    register_error_recovery_engine,
)
from .sound_spatial_adapter import (
    FixedModalExcitationProvider,
    MidSideStereoDescriptorObserver,
    ModalExcitationProvider,
    SoundCapabilityUnavailable,
    SoundDescriptorRenderer,
    SoundSpatialRuntimeAdapter,
    SoundSpatialRuntimeConfig,
    SpatialDescriptorObserver,
    V3AcousticDescriptorRenderer,
    V3ModalExcitationFrame,
    register_sound_spatial,
)
from .measurement_feedback_adapter import (
    AcquiredMeasurement,
    FeedbackMapper,
    MeasurementFeedbackConfig,
    MeasurementFeedbackQueue,
    MeasurementFeedbackRuntimeAdapter,
    MeasurementOrigin,
    MeasurementProvider,
    MeasurementRequest,
    MeasurementRuntimeFrame,
    QueuedMeasurementFeedback,
    SelectedMeasurement,
    TransferMeasurementQuality,
    TransferMeasurementValidation,
    TransferMemoryEstimateUpdate,
    register_measurement_feedback,
)

__all__ = [
    "CANONICAL_RUNTIME_STEPS",
    "DirtyFlags",
    "ErrorRecoveryRuntimeAdapter",
    "FixedModalExcitationProvider",
    "FlowGeometryRuntimeAdapter",
    "FlowGeometryRuntimeConfig",
    "FeedbackMapper",
    "FrameRevisions",
    "GeometryEigenmodeFrame",
    "HilbertBasisProjectionFrame",
    "MeasurementFeedbackConfig",
    "MeasurementFeedbackQueue",
    "MeasurementFeedbackRuntimeAdapter",
    "MeasurementOrigin",
    "MeasurementProvider",
    "MeasurementRequest",
    "MeasurementRuntimeFrame",
    "MidSideStereoDescriptorObserver",
    "ModalExcitationProvider",
    "QMWFrame",
    "QMWRuntimeScheduler",
    "QuantumEngineRuntimeAdapter",
    "QuantumGeneratorControlBatch",
    "QuantumValidationFrame",
    "QueuedMeasurementFeedback",
    "MemoryDensityProjector",
    "MemoryMatrixRuntimeAdapter",
    "QuantumFieldRuntimeAdapter",
    "QuenchRuntimeAdapter",
    "RuntimePhase",
    "RuntimeStep",
    "RuntimeStepError",
    "RuntimeTriggers",
    "SelectedMeasurement",
    "SoundCapabilityUnavailable",
    "SoundDescriptorRenderer",
    "SoundSpatialRuntimeAdapter",
    "SoundSpatialRuntimeConfig",
    "SpatialDescriptorObserver",
    "TickResult",
    "TransferMeasurementQuality",
    "TransferMeasurementValidation",
    "TransferMemoryEstimateUpdate",
    "V3AcousticDescriptorRenderer",
    "V3ModalExcitationFrame",
    "AcquiredMeasurement",
    "steps_for_phase",
    "qmw_frame_from_authoritative_flow",
    "register_flow_geometry",
    "register_error_recovery_engine",
    "register_quantum_field_engine",
    "register_quench_engine",
    "register_memory_matrix_engine",
    "register_measurement_feedback",
    "register_quantum_engine",
    "register_sound_spatial",
    "validate_quantum_frame",
]
