{
  "patcher": {
    "fileversion": 1,
    "appversion": {"major": 9, "minor": 0, "revision": 0, "architecture": "x64", "modernui": 1},
    "rect": [100.0, 70.0, 1180.0, 720.0],
    "gridsize": [15.0, 15.0],
    "boxes": [
      {"box":{"id":"title","maxclass":"comment","text":"BLOCH × ELEMENTS EMERGENT RESONATOR v1.1","fontsize":19.0,"fontface":1,"patching_rect":[40.0,25.0,650.0,30.0]}},
      {"box":{"id":"subtitle","maxclass":"comment","text":"Plain gen~ repair: eleven physical modes, native udpreceive decoding, built-in test strike","fontsize":13.0,"patching_rect":[40.0,60.0,800.0,22.0]}},
      {"box":{"id":"instructions","maxclass":"comment","text":"1. Click speaker.  2. Click LOCAL TEST STRIKE.  3. Run StartBlochQuenchEvents.command --port 7491. The event lamp proves OSC independently of audio.","linecount":2,"patching_rect":[40.0,95.0,820.0,42.0]}},
      {"box":{"id":"udp","maxclass":"newobj","text":"udpreceive 7491","numinlets":0,"numoutlets":1,"outlettype":["anything"],"patching_rect":[40.0,165.0,105.0,22.0]}},
      {"box":{"id":"nativeosc","maxclass":"comment","text":"udpreceive decodes OSC natively (no oscparse / OSC-route)","patching_rect":[165.0,165.0,355.0,22.0]}},
      {"box":{"id":"route","maxclass":"newobj","text":"route /qmw/bloch/event","numinlets":2,"numoutlets":2,"patching_rect":[40.0,225.0,175.0,22.0]}},
      {"box":{"id":"statefork","maxclass":"newobj","text":"t l l b","numinlets":1,"numoutlets":3,"patching_rect":[40.0,285.0,55.0,22.0]}},
      {"box":{"id":"converter","maxclass":"newobj","text":"js qmw_bloch_event_to_gen.js","numinlets":1,"numoutlets":1,"patching_rect":[40.0,345.0,205.0,22.0]}},
      {"box":{"id":"unpack","maxclass":"newobj","text":"unpack i i f f f f f","numinlets":1,"numoutlets":7,"patching_rect":[265.0,345.0,145.0,22.0]}},
      {"box":{"id":"nativeamp","maxclass":"newobj","text":"prepend eventamp","numinlets":1,"numoutlets":1,"patching_rect":[430.0,345.0,112.0,22.0]}},
      {"box":{"id":"iddelay","maxclass":"newobj","text":"pipe 1","numinlets":1,"numoutlets":1,"patching_rect":[430.0,305.0,45.0,22.0]}},
      {"box":{"id":"nativeid","maxclass":"newobj","text":"prepend eventid","numinlets":1,"numoutlets":1,"patching_rect":[490.0,305.0,105.0,22.0]}},
      {"box":{"id":"flash","maxclass":"button","numinlets":1,"numoutlets":1,"patching_rect":[430.0,165.0,28.0,28.0]}},
      {"box":{"id":"flashlabel","maxclass":"comment","text":"OSC EVENT","fontface":1,"patching_rect":[470.0,168.0,95.0,22.0]}},
      {"box":{"id":"eventclick","maxclass":"newobj","text":"click~","numinlets":1,"numoutlets":1,"outlettype":["signal"],"patching_rect":[535.0,265.0,45.0,22.0]}},
      {"box":{"id":"localtest","maxclass":"message","text":"999 0 0. 0.95 0.2 4.5 0.3 0.02 0.04 0.08 0.12 0.16 0.18 0.15 0.1 0.07 0.05 0.03 -2.4 -1.8 -1.2 -0.6 -0.2 0. 0.3 0.8 1.2 1.7 2.2 0.2 0.3 0.4 0.6 0.8 1. 0.8 0.6 0.4 0.3 0.2","linecount":3,"patching_rect":[40.0,420.0,520.0,62.0]}},
      {"box":{"id":"testlabel","maxclass":"comment","text":"LOCAL TEST STRIKE — bypasses Python and UDP","fontface":1,"patching_rect":[40.0,490.0,330.0,22.0]}},
      {"box":{"id":"eventid","maxclass":"number","numinlets":1,"numoutlets":2,"patching_rect":[265.0,285.0,62.0,22.0]}},
      {"box":{"id":"kind","maxclass":"number","numinlets":1,"numoutlets":2,"patching_rect":[340.0,285.0,52.0,22.0]}},
      {"box":{"id":"loadbang","maxclass":"newobj","text":"loadbang","patching_rect":[640.0,145.0,60.0,22.0]}},
      {"box":{"id":"dspstart","maxclass":"message","text":"1","patching_rect":[715.0,145.0,32.0,22.0]}},
      {"box":{"id":"dspnote","maxclass":"comment","text":"DSP auto-start","patching_rect":[760.0,145.0,100.0,22.0]}},
      {"box":{"id":"defaults","maxclass":"message","text":"fundamental 92, geometry 0.42, brightness 0.68, damping 0.72, position 0.37, state_geometry 0.35, quantum_color 0.78, strike_ms 2.8, amp 0.72","linecount":2,"patching_rect":[640.0,180.0,500.0,42.0]}},
      {"box":{"id":"string","maxclass":"message","text":"geometry 0.25, brightness 0.65, damping 0.78, position 0.37","patching_rect":[640.0,240.0,395.0,22.0]}},
      {"box":{"id":"bell","maxclass":"message","text":"geometry 0.72, brightness 0.84, damping 0.86, position 0.22","patching_rect":[640.0,272.0,395.0,22.0]}},
      {"box":{"id":"membrane","maxclass":"message","text":"geometry 0.08, brightness 0.52, damping 0.67, position 0.61","patching_rect":[640.0,304.0,395.0,22.0]}},
      {"box":{"id":"presetlabel","maxclass":"comment","text":"string-like                 bell-like                    membrane-like","patching_rect":[640.0,334.0,450.0,22.0]}},
      {"box":{"id":"gen","maxclass":"newobj","text":"gen~ qmw_bloch_elements_resonator_v3","numinlets":1,"numoutlets":2,"outlettype":["signal","signal"],"patching_rect":[640.0,385.0,235.0,22.0]}},
      {"box":{"id":"genlabel","maxclass":"comment","text":"real radiation                              imaginary radiation","patching_rect":[640.0,420.0,390.0,22.0]}},
      {"box":{"id":"leftmeter","maxclass":"meter~","numinlets":1,"numoutlets":1,"patching_rect":[690.0,465.0,18.0,115.0]}},
      {"box":{"id":"rightmeter","maxclass":"meter~","numinlets":1,"numoutlets":1,"patching_rect":[870.0,465.0,18.0,115.0]}},
      {"box":{"id":"dac","maxclass":"ezdac~","numinlets":2,"numoutlets":0,"patching_rect":[770.0,615.0,48.0,48.0]}},
      {"box":{"id":"diagnostic","maxclass":"comment","text":"DIAGNOSTIC\nLocal test silent + meters still: Gen compile/audio path\nLocal test sounds + OSC lamp dark: sender/port\nOSC lamp flashes + meters still: event mapping\nMeters move + no sound: audio device/routing","linecount":6,"patching_rect":[40.0,545.0,450.0,125.0]}},
      {"box":{"id":"credit","maxclass":"comment","text":"Elements-inspired modal spacing, loss, Q, and pickup concepts. Emilie Gillet (2014), MIT. See THIRD_PARTY_ELEMENTS_NOTICE.md.","linecount":2,"patching_rect":[640.0,680.0,500.0,40.0]}}
    ],
    "lines": [
      {"patchline":{"source":["udp",0],"destination":["route",0]}},
      {"patchline":{"source":["route",0],"destination":["statefork",0]}},
      {"patchline":{"source":["statefork",0],"destination":["converter",0]}},
      {"patchline":{"source":["statefork",1],"destination":["unpack",0]}},
      {"patchline":{"source":["statefork",2],"destination":["flash",0]}},
      {"patchline":{"source":["statefork",2],"destination":["eventclick",0]}},
      {"patchline":{"source":["eventclick",0],"destination":["gen",0]}},
      {"patchline":{"source":["localtest",0],"destination":["statefork",0]}},
      {"patchline":{"source":["converter",0],"destination":["gen",0]}},
      {"patchline":{"source":["unpack",0],"destination":["eventid",0]}},
      {"patchline":{"source":["unpack",1],"destination":["kind",0]}},
      {"patchline":{"source":["unpack",3],"destination":["nativeamp",0]}},
      {"patchline":{"source":["nativeamp",0],"destination":["gen",0]}},
      {"patchline":{"source":["unpack",0],"destination":["iddelay",0]}},
      {"patchline":{"source":["iddelay",0],"destination":["nativeid",0]}},
      {"patchline":{"source":["nativeid",0],"destination":["gen",0]}},
      {"patchline":{"source":["loadbang",0],"destination":["defaults",0]}},
      {"patchline":{"source":["loadbang",0],"destination":["dspstart",0]}},
      {"patchline":{"source":["dspstart",0],"destination":["dac",0]}},
      {"patchline":{"source":["defaults",0],"destination":["gen",0]}},
      {"patchline":{"source":["string",0],"destination":["gen",0]}},
      {"patchline":{"source":["bell",0],"destination":["gen",0]}},
      {"patchline":{"source":["membrane",0],"destination":["gen",0]}},
      {"patchline":{"source":["gen",0],"destination":["leftmeter",0]}},
      {"patchline":{"source":["gen",1],"destination":["rightmeter",0]}},
      {"patchline":{"source":["gen",0],"destination":["dac",0]}},
      {"patchline":{"source":["gen",1],"destination":["dac",1]}}
    ],
    "dependency_cache": [
      {"name":"qmw_bloch_elements_resonator_v3.gendsp","type":"JSON"},
      {"name":"qmw_bloch_event_to_gen.js","type":"TEXT"}
    ]
  }
}
