{
  "patcher": {
    "fileversion": 1,
    "appversion": {"major":9,"minor":0,"revision":0,"architecture":"x64","modernui":1},
    "classnamespace":"box",
    "rect":[120.0,100.0,1260.0,720.0],
    "boxes":[
      {"box":{"id":"real","maxclass":"inlet","index":1,"comment":"real quadrature","numinlets":0,"numoutlets":1,"outlettype":["signal"],"patching_rect":[40.0,45.0,30.0,30.0]}},
      {"box":{"id":"imag","maxclass":"inlet","index":2,"comment":"imaginary quadrature","numinlets":0,"numoutlets":1,"outlettype":["signal"],"patching_rect":[100.0,45.0,30.0,30.0]}},
      {"box":{"id":"state","maxclass":"inlet","index":3,"comment":"q energy","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[175.0,45.0,30.0,30.0]}},
      {"box":{"id":"openin","maxclass":"inlet","index":4,"comment":"open Spat","numinlets":0,"numoutlets":1,"outlettype":[""],"patching_rect":[1110.0,45.0,30.0,30.0]}},
      {"box":{"id":"title","maxclass":"comment","text":"Complex Bloch field → quadrature cross + slowed phase orbit → Spat5 HOA3","fontsize":14.0,"fontface":1,"patching_rect":[245.0,20.0,690.0,22.0]}},
      {"box":{"id":"realminus","maxclass":"newobj","text":"*~ -1.","numinlets":2,"numoutlets":1,"outlettype":["signal"],"patching_rect":[40.0,110.0,50.0,22.0]}},
      {"box":{"id":"imagminus","maxclass":"newobj","text":"*~ -1.","numinlets":2,"numoutlets":1,"outlettype":["signal"],"patching_rect":[100.0,145.0,50.0,22.0]}},
      {"box":{"id":"orbitsum","maxclass":"newobj","text":"+~","numinlets":2,"numoutlets":1,"outlettype":["signal"],"patching_rect":[175.0,110.0,35.0,22.0]}},
      {"box":{"id":"orbitgain","maxclass":"newobj","text":"*~ 0.32","numinlets":2,"numoutlets":1,"outlettype":["signal"],"patching_rect":[175.0,145.0,58.0,22.0]}},
      {"box":{"id":"unpack","maxclass":"newobj","text":"unpack f f","numinlets":1,"numoutlets":2,"patching_rect":[275.0,85.0,70.0,22.0]}},
      {"box":{"id":"qoffset","maxclass":"newobj","text":"* 180.","numinlets":2,"numoutlets":1,"patching_rect":[275.0,125.0,50.0,22.0]}},
      {"box":{"id":"rate","maxclass":"newobj","text":"expr -1.*(0.025+0.18*abs($f1-1.5448614))","numinlets":1,"numoutlets":1,"patching_rect":[355.0,125.0,270.0,22.0]}},
      {"box":{"id":"ratesig","maxclass":"newobj","text":"sig~","numinlets":1,"numoutlets":1,"outlettype":["signal"],"patching_rect":[355.0,165.0,38.0,22.0]}},
      {"box":{"id":"phasor","maxclass":"newobj","text":"phasor~","numinlets":2,"numoutlets":1,"outlettype":["signal"],"patching_rect":[410.0,165.0,55.0,22.0]}},
      {"box":{"id":"snapshot","maxclass":"newobj","text":"snapshot~ 20","numinlets":2,"numoutlets":1,"patching_rect":[485.0,165.0,85.0,22.0]}},
      {"box":{"id":"degrees","maxclass":"newobj","text":"* 360.","numinlets":2,"numoutlets":1,"patching_rect":[590.0,165.0,55.0,22.0]}},
      {"box":{"id":"azoffset","maxclass":"newobj","text":"+ 0.","numinlets":2,"numoutlets":1,"patching_rect":[665.0,165.0,45.0,22.0]}},
      {"box":{"id":"aed","maxclass":"newobj","text":"pack f 0. 1.","numinlets":3,"numoutlets":1,"patching_rect":[730.0,165.0,80.0,22.0]}},
      {"box":{"id":"prepaed","maxclass":"newobj","text":"prepend /source/5/aed","numinlets":1,"numoutlets":1,"patching_rect":[830.0,165.0,155.0,22.0]}},
      {"box":{"id":"oper","maxclass":"newobj","text":"spat5.oper @initwith \"/source/number 5, /source/1/label real-east, /source/2/label real-west, /source/3/label imag-north, /source/4/label imag-south, /source/5/label phase-orbit, /source/1/aed 90 0 1, /source/2/aed -90 0 1, /source/3/aed 0 0 1, /source/4/aed 180 0 1, /source/5/aed 0 0 1, /source/*/aperture 18, /source/*/constraint/circular 0\"","numinlets":1,"numoutlets":1,"patching_rect":[275.0,235.0,900.0,55.0]}},
      {"box":{"id":"renderer","maxclass":"newobj","text":"spat5.spat~ @inputs 5 @internals 8 @outputs 16 @rooms 1 @initwith \"/panning/type hoa3d, /norm SN3D\"","numinlets":6,"numoutlets":16,"outlettype":["signal","signal","signal","signal","signal","signal","signal","signal","signal","signal","signal","signal","signal","signal","signal","signal"],"patching_rect":[275.0,330.0,720.0,22.0]}},
      {"box":{"id":"loadbang","maxclass":"newobj","text":"loadbang","patching_rect":[1010.0,105.0,60.0,22.0]}},
      {"box":{"id":"delay","maxclass":"newobj","text":"delay 750","patching_rect":[1080.0,105.0,68.0,22.0]}},
      {"box":{"id":"open","maxclass":"message","text":"/window/open","patching_rect":[1060.0,145.0,90.0,22.0]}},
      {"box":{"id":"out1","maxclass":"outlet","index":1,"comment":"ACN 0","patching_rect":[275.0,430.0,30.0,30.0]}},
      {"box":{"id":"out2","maxclass":"outlet","index":2,"comment":"ACN 1","patching_rect":[325.0,430.0,30.0,30.0]}},
      {"box":{"id":"out3","maxclass":"outlet","index":3,"comment":"ACN 2","patching_rect":[375.0,430.0,30.0,30.0]}},
      {"box":{"id":"out4","maxclass":"outlet","index":4,"comment":"ACN 3","patching_rect":[425.0,430.0,30.0,30.0]}},
      {"box":{"id":"out5","maxclass":"outlet","index":5,"patching_rect":[475.0,430.0,30.0,30.0]}},
      {"box":{"id":"out6","maxclass":"outlet","index":6,"patching_rect":[525.0,430.0,30.0,30.0]}},
      {"box":{"id":"out7","maxclass":"outlet","index":7,"patching_rect":[575.0,430.0,30.0,30.0]}},
      {"box":{"id":"out8","maxclass":"outlet","index":8,"patching_rect":[625.0,430.0,30.0,30.0]}},
      {"box":{"id":"out9","maxclass":"outlet","index":9,"patching_rect":[675.0,430.0,30.0,30.0]}},
      {"box":{"id":"out10","maxclass":"outlet","index":10,"patching_rect":[725.0,430.0,30.0,30.0]}},
      {"box":{"id":"out11","maxclass":"outlet","index":11,"patching_rect":[775.0,430.0,30.0,30.0]}},
      {"box":{"id":"out12","maxclass":"outlet","index":12,"patching_rect":[825.0,430.0,30.0,30.0]}},
      {"box":{"id":"out13","maxclass":"outlet","index":13,"patching_rect":[875.0,430.0,30.0,30.0]}},
      {"box":{"id":"out14","maxclass":"outlet","index":14,"patching_rect":[925.0,430.0,30.0,30.0]}},
      {"box":{"id":"out15","maxclass":"outlet","index":15,"patching_rect":[975.0,430.0,30.0,30.0]}},
      {"box":{"id":"out16","maxclass":"outlet","index":16,"patching_rect":[1025.0,430.0,30.0,30.0]}},
      {"box":{"id":"note","maxclass":"comment","text":"Sources 1–4 are polarity-opposed dipoles; source 5 orbits clockwise at a compressed energy rate, with q as azimuth offset.","patching_rect":[275.0,500.0,760.0,22.0]}}
    ],
    "lines":[
      {"patchline":{"source":["real",0],"destination":["renderer",0]}},{"patchline":{"source":["real",0],"destination":["realminus",0]}},{"patchline":{"source":["realminus",0],"destination":["renderer",1]}},
      {"patchline":{"source":["imag",0],"destination":["renderer",2]}},{"patchline":{"source":["imag",0],"destination":["imagminus",0]}},{"patchline":{"source":["imagminus",0],"destination":["renderer",3]}},
      {"patchline":{"source":["real",0],"destination":["orbitsum",0]}},{"patchline":{"source":["imag",0],"destination":["orbitsum",1]}},{"patchline":{"source":["orbitsum",0],"destination":["orbitgain",0]}},{"patchline":{"source":["orbitgain",0],"destination":["renderer",4]}},
      {"patchline":{"source":["state",0],"destination":["unpack",0]}},{"patchline":{"source":["unpack",0],"destination":["qoffset",0]}},{"patchline":{"source":["qoffset",0],"destination":["azoffset",1]}},{"patchline":{"source":["unpack",1],"destination":["rate",0]}},{"patchline":{"source":["rate",0],"destination":["ratesig",0]}},{"patchline":{"source":["ratesig",0],"destination":["phasor",0]}},{"patchline":{"source":["phasor",0],"destination":["snapshot",0]}},{"patchline":{"source":["snapshot",0],"destination":["degrees",0]}},{"patchline":{"source":["degrees",0],"destination":["azoffset",0]}},{"patchline":{"source":["azoffset",0],"destination":["aed",0]}},{"patchline":{"source":["aed",0],"destination":["prepaed",0]}},{"patchline":{"source":["prepaed",0],"destination":["oper",0]}},
      {"patchline":{"source":["oper",0],"destination":["renderer",0]}},{"patchline":{"source":["loadbang",0],"destination":["delay",0]}},{"patchline":{"source":["delay",0],"destination":["open",0]}},{"patchline":{"source":["openin",0],"destination":["open",0]}},{"patchline":{"source":["open",0],"destination":["oper",0]}},
      {"patchline":{"source":["renderer",0],"destination":["out1",0]}},{"patchline":{"source":["renderer",1],"destination":["out2",0]}},{"patchline":{"source":["renderer",2],"destination":["out3",0]}},{"patchline":{"source":["renderer",3],"destination":["out4",0]}},{"patchline":{"source":["renderer",4],"destination":["out5",0]}},{"patchline":{"source":["renderer",5],"destination":["out6",0]}},{"patchline":{"source":["renderer",6],"destination":["out7",0]}},{"patchline":{"source":["renderer",7],"destination":["out8",0]}},{"patchline":{"source":["renderer",8],"destination":["out9",0]}},{"patchline":{"source":["renderer",9],"destination":["out10",0]}},{"patchline":{"source":["renderer",10],"destination":["out11",0]}},{"patchline":{"source":["renderer",11],"destination":["out12",0]}},{"patchline":{"source":["renderer",12],"destination":["out13",0]}},{"patchline":{"source":["renderer",13],"destination":["out14",0]}},{"patchline":{"source":["renderer",14],"destination":["out15",0]}},{"patchline":{"source":["renderer",15],"destination":["out16",0]}}
    ],
    "dependency_cache":[{"name":"spat5.oper.mxo","type":"iLaX"},{"name":"spat5.spat~.mxo","type":"iLaX"}],
    "autosave":0
  }
}
