{
  "patcher": {
    "fileversion": 1,
    "appversion": {"major": 9, "minor": 0, "revision": 0, "architecture": "x64", "modernui": 1},
    "rect": [100.0, 70.0, 1240.0, 760.0],
    "gridsize": [15.0, 15.0],
    "boxes": [
      {"box":{"id":"title","maxclass":"comment","text":"BLOCH × ELEMENTS EMERGENT RESONATOR v1","fontsize":19.0,"fontface":1,"patching_rect":[40.0,25.0,620.0,30.0]}},
      {"box":{"id":"subtitle","maxclass":"comment","text":"Fixed-H quench events strike a sixteen-mode Elements-inspired physical body","fontsize":13.0,"patching_rect":[40.0,60.0,700.0,22.0]}},
      {"box":{"id":"instructions","maxclass":"comment","text":"No internal clock or position LFO. Enable DSP, then run StartBlochQuenchEvents.command. Try the three material messages while events ring.","linecount":2,"patching_rect":[40.0,95.0,790.0,42.0]}},
      {"box":{"id":"udp","maxclass":"newobj","text":"udpreceive 7490","numinlets":0,"numoutlets":1,"outlettype":["anything"],"patching_rect":[40.0,165.0,105.0,22.0]}},
      {"box":{"id":"route","maxclass":"newobj","text":"route /qmw/bloch/event","numinlets":2,"numoutlets":2,"patching_rect":[40.0,285.0,175.0,22.0]}},
      {"box":{"id":"fork","maxclass":"newobj","text":"t l l b","numinlets":1,"numoutlets":3,"patching_rect":[40.0,325.0,55.0,22.0]}},
      {"box":{"id":"converter","maxclass":"newobj","text":"js qmw_bloch_event_to_gen.js","numinlets":1,"numoutlets":1,"patching_rect":[40.0,365.0,205.0,22.0]}},
      {"box":{"id":"unpack","maxclass":"newobj","text":"unpack i i f f f f f","numinlets":1,"numoutlets":7,"patching_rect":[265.0,365.0,145.0,22.0]}},
      {"box":{"id":"flash","maxclass":"button","numinlets":1,"numoutlets":1,"patching_rect":[430.0,165.0,28.0,28.0]}},
      {"box":{"id":"flashlabel","maxclass":"comment","text":"INTRINSIC EVENT","fontface":1,"patching_rect":[470.0,168.0,130.0,22.0]}},
      {"box":{"id":"eventid","maxclass":"number","numinlets":1,"numoutlets":2,"patching_rect":[40.0,430.0,62.0,22.0]}},
      {"box":{"id":"kind","maxclass":"number","numinlets":1,"numoutlets":2,"patching_rect":[115.0,430.0,52.0,22.0]}},
      {"box":{"id":"simtime","maxclass":"flonum","numinlets":1,"numoutlets":2,"patching_rect":[180.0,430.0,70.0,22.0]}},
      {"box":{"id":"eventamp","maxclass":"flonum","numinlets":1,"numoutlets":2,"patching_rect":[265.0,430.0,62.0,22.0]}},
      {"box":{"id":"fidelity","maxclass":"flonum","numinlets":1,"numoutlets":2,"patching_rect":[340.0,430.0,62.0,22.0]}},
      {"box":{"id":"participation","maxclass":"flonum","numinlets":1,"numoutlets":2,"patching_rect":[415.0,430.0,62.0,22.0]}},
      {"box":{"id":"current","maxclass":"flonum","numinlets":1,"numoutlets":2,"patching_rect":[490.0,430.0,62.0,22.0]}},
      {"box":{"id":"labels","maxclass":"comment","text":"event       kind       sim t          strike       fidelity       modes       current direction","patching_rect":[40.0,460.0,565.0,22.0]}},
      {"box":{"id":"loadbang","maxclass":"newobj","text":"loadbang","patching_rect":[655.0,160.0,60.0,22.0]}},
      {"box":{"id":"defaults","maxclass":"message","text":"fundamental 92, geometry 0.42, brightness 0.68, damping 0.72, position 0.37, state_geometry 0.35, quantum_color 0.78, strike_ms 2.8, amp 0.72","linecount":2,"patching_rect":[655.0,195.0,510.0,42.0]}},
      {"box":{"id":"materiallabel","maxclass":"comment","text":"ELEMENTS-INSPIRED MATERIAL PRESETS","fontface":1,"patching_rect":[655.0,250.0,280.0,22.0]}},
      {"box":{"id":"string","maxclass":"message","text":"geometry 0.25, brightness 0.65, damping 0.78, position 0.37","patching_rect":[655.0,280.0,395.0,22.0]}},
      {"box":{"id":"bell","maxclass":"message","text":"geometry 0.72, brightness 0.84, damping 0.86, position 0.22","patching_rect":[655.0,312.0,395.0,22.0]}},
      {"box":{"id":"membrane","maxclass":"message","text":"geometry 0.08, brightness 0.52, damping 0.67, position 0.61","patching_rect":[655.0,344.0,395.0,22.0]}},
      {"box":{"id":"gen","maxclass":"newobj","text":"mc.gen~ @gen qmw_bloch_elements_mode16_mc @chans 16","numinlets":1,"numoutlets":2,"outlettype":["multichannelsignal","multichannelsignal"],"patching_rect":[655.0,395.0,365.0,22.0]}},
      {"box":{"id":"realmixed","maxclass":"newobj","text":"mc.mixdown~ 1 @autogain 1","numinlets":1,"numoutlets":1,"outlettype":["multichannelsignal"],"patching_rect":[655.0,440.0,170.0,22.0]}},
      {"box":{"id":"imagmixed","maxclass":"newobj","text":"mc.mixdown~ 1 @autogain 1","numinlets":1,"numoutlets":1,"outlettype":["multichannelsignal"],"patching_rect":[860.0,440.0,170.0,22.0]}},
      {"box":{"id":"realunpack","maxclass":"newobj","text":"mc.unpack~ 1","numinlets":1,"numoutlets":1,"outlettype":["signal"],"patching_rect":[655.0,480.0,88.0,22.0]}},
      {"box":{"id":"imagunpack","maxclass":"newobj","text":"mc.unpack~ 1","numinlets":1,"numoutlets":1,"outlettype":["signal"],"patching_rect":[860.0,480.0,88.0,22.0]}},
      {"box":{"id":"leftmeter","maxclass":"meter~","numinlets":1,"numoutlets":1,"patching_rect":[690.0,520.0,18.0,110.0]}},
      {"box":{"id":"rightmeter","maxclass":"meter~","numinlets":1,"numoutlets":1,"patching_rect":[900.0,520.0,18.0,110.0]}},
      {"box":{"id":"dac","maxclass":"ezdac~","numinlets":2,"numoutlets":0,"patching_rect":[785.0,650.0,48.0,48.0]}},
      {"box":{"id":"mapping","maxclass":"comment","text":"STATE → MATERIAL\nparticipation → brightness\nfidelity loss → resonance memory\ncurrent → pickup position\ncomplex coefficient phase → real/imaginary radiation\npopulation velocity → high-mode loss\n\nElements' internal stereo LFO is deliberately absent.","linecount":9,"patching_rect":[40.0,520.0,420.0,170.0]}},
      {"box":{"id":"credit","maxclass":"comment","text":"Adapted from the MIT-licensed Mutable Instruments Elements resonator by Emilie Gillet. See THIRD_PARTY_ELEMENTS_NOTICE.md.","linecount":2,"patching_rect":[655.0,715.0,520.0,40.0]}}
    ],
    "lines": [
      {"patchline":{"source":["udp",0],"destination":["route",0]}},
      {"patchline":{"source":["route",0],"destination":["fork",0]}},
      {"patchline":{"source":["fork",0],"destination":["converter",0]}},
      {"patchline":{"source":["fork",1],"destination":["unpack",0]}},
      {"patchline":{"source":["fork",2],"destination":["flash",0]}},
      {"patchline":{"source":["converter",0],"destination":["gen",0]}},
      {"patchline":{"source":["unpack",0],"destination":["eventid",0]}},
      {"patchline":{"source":["unpack",1],"destination":["kind",0]}},
      {"patchline":{"source":["unpack",2],"destination":["simtime",0]}},
      {"patchline":{"source":["unpack",3],"destination":["eventamp",0]}},
      {"patchline":{"source":["unpack",4],"destination":["fidelity",0]}},
      {"patchline":{"source":["unpack",5],"destination":["participation",0]}},
      {"patchline":{"source":["unpack",6],"destination":["current",0]}},
      {"patchline":{"source":["loadbang",0],"destination":["defaults",0]}},
      {"patchline":{"source":["defaults",0],"destination":["gen",0]}},
      {"patchline":{"source":["string",0],"destination":["gen",0]}},
      {"patchline":{"source":["bell",0],"destination":["gen",0]}},
      {"patchline":{"source":["membrane",0],"destination":["gen",0]}},
      {"patchline":{"source":["gen",0],"destination":["realmixed",0]}},
      {"patchline":{"source":["gen",1],"destination":["imagmixed",0]}},
      {"patchline":{"source":["realmixed",0],"destination":["realunpack",0]}},
      {"patchline":{"source":["imagmixed",0],"destination":["imagunpack",0]}},
      {"patchline":{"source":["realunpack",0],"destination":["leftmeter",0]}},
      {"patchline":{"source":["imagunpack",0],"destination":["rightmeter",0]}},
      {"patchline":{"source":["realunpack",0],"destination":["dac",0]}},
      {"patchline":{"source":["imagunpack",0],"destination":["dac",1]}}
    ],
    "dependency_cache": [
      {"name":"qmw_bloch_elements_mode16_mc.gendsp","type":"JSON"},
      {"name":"qmw_bloch_event_to_gen.js","type":"TEXT"}
    ]
  }
}
